/* AUTOGENERATED FILE - DO NOT MODIFY */
#include "atomic_inst.hh"
#include "archstate.hh"
#include "lanetypes.hh"
#include "debug.hh"
#include <string>

namespace basim {

/* dummy Instruction */
Cycles exeInstDummy(ArchState& ast, EncInst inst) {
  BASIM_WARNING("INSTRUCTION EXE NOT IMPLEMENTED, ENCODED INSTRUCTION = 0x%08x", inst);
  return Cycles(0);
}

std::string disasmInstDummy(EncInst inst) {
  std::string disasm_str = "DUMMY";
  char buffer[16];
  snprintf(buffer, sizeof(buffer), "0x%08x", inst);
  disasm_str += " " + std::string(buffer);
  return disasm_str;
}

EncInst constrInstDummy() {
  BASIM_WARNING("INSTRUCTION CONSTR NOT IMPLEMENTED");
  return static_cast<EncInst>(0);
}

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
