from linker.EFAProgram import efaProgram
from linker.EFAsections.StaticDataSection import staticDataType

@efaProgram
def efaProgram_LMCache(efa):

    ## init_null_state
    init_null_state = efa.State("init_null_state")
    efa.add_state(init_null_state)
    efa.add_initId(init_null_state.state_id)

    ## Broadcast__broadcast_global
    Broadcast__broadcast_global = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_global")
    Broadcast__broadcast_global.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global.writeAction("movir X16 128")
    Broadcast__broadcast_global.writeAction("bgt X25 X16 GenLinkableBroadcast_jhkxr_max_child_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global.writeAction("beqi X16 0 GenLinkableBroadcast_jhkxr_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global.writeAction("jmp GenLinkableBroadcast_jhkxr_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_jhkxr_max_child_modular_eq_zero: mov_imm2reg X25 128")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_jhkxr_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global.writeAction("evlb X28 Broadcast__broadcast_node")
    Broadcast__broadcast_global.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_jhkxr_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global.writeAction("sendops_wret X28 Broadcast__broadcast_global_fin X8 8 X16")
    Broadcast__broadcast_global.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global.writeAction("blt X17 X25 GenLinkableBroadcast_jhkxr_broadcast_loop")
    Broadcast__broadcast_global.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global.writeAction("yield")

    ## Broadcast__broadcast_node
    Broadcast__broadcast_node = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_node")
    Broadcast__broadcast_node.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node.writeAction("movir X16 32")
    Broadcast__broadcast_node.writeAction("bgt X25 X16 GenLinkableBroadcast_jhkxr_max_child_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node.writeAction("beqi X16 0 GenLinkableBroadcast_jhkxr_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node.writeAction("jmp GenLinkableBroadcast_jhkxr_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_jhkxr_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_jhkxr_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node.writeAction("evlb X28 Broadcast__broadcast_ud")
    Broadcast__broadcast_node.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_jhkxr_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node.writeAction("sendops_wret X28 Broadcast__broadcast_node_fin X8 8 X16")
    Broadcast__broadcast_node.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node.writeAction("blt X17 X25 GenLinkableBroadcast_jhkxr_broadcast_loop")
    Broadcast__broadcast_node.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node.writeAction("yield")

    ## Broadcast__broadcast_ud
    Broadcast__broadcast_ud = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_ud")
    Broadcast__broadcast_ud.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud.writeAction("movir X25 64")
    Broadcast__broadcast_ud.writeAction("bgt X8 X25 GenLinkableBroadcast_jhkxr_modular_eq_zero")
    Broadcast__broadcast_ud.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud.writeAction("GenLinkableBroadcast_jhkxr_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud.writeAction("GenLinkableBroadcast_jhkxr_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud.writeAction("sendops_wret X28 Broadcast__broadcast_ud_fin X10 6 X16")
    Broadcast__broadcast_ud.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud.writeAction("blt X17 X25 GenLinkableBroadcast_jhkxr_broadcast_loop")
    Broadcast__broadcast_ud.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud.writeAction("yield")

    ## Broadcast__broadcast_ud_fin
    Broadcast__broadcast_ud_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_ud_fin")
    Broadcast__broadcast_ud_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin.writeAction("blt X26 X25 GenLinkableBroadcast_jhkxr_continue")
    Broadcast__broadcast_ud_fin.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_ud_fin.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin.writeAction("GenLinkableBroadcast_jhkxr_continue: yield")

    ## Broadcast__broadcast_node_fin
    Broadcast__broadcast_node_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_node_fin")
    Broadcast__broadcast_node_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin.writeAction("blt X26 X25 GenLinkableBroadcast_jhkxr_continue")
    Broadcast__broadcast_node_fin.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin.writeAction("GenLinkableBroadcast_jhkxr_continue: yield")

    ## Broadcast__broadcast_global_fin
    Broadcast__broadcast_global_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_global_fin")
    Broadcast__broadcast_global_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin.writeAction("beq X26 X25 GenLinkableBroadcast_jhkxr_global_bcst_finish")
    Broadcast__broadcast_global_fin.writeAction("yield")
    Broadcast__broadcast_global_fin.writeAction("GenLinkableBroadcast_jhkxr_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad
    Broadcast__broadcast_value_to_scratchpad = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_value_to_scratchpad")
    Broadcast__broadcast_value_to_scratchpad.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad.writeAction("yieldt")

    ## linkable_lm_cache__broadcast_global
    linkable_lm_cache__broadcast_global = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_global")
    linkable_lm_cache__broadcast_global.writeAction("print ' '")
    linkable_lm_cache__broadcast_global.writeAction("addi X9 X20 0")
    linkable_lm_cache__broadcast_global.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Event <linkable_lm_cache::broadcast_global> ev_word = %lu num_lanes = %ld init_ev_word = %lu' X0 EQT X8 X20")
    linkable_lm_cache__broadcast_global.writeAction("addi X8 X27 0")
    linkable_lm_cache__broadcast_global.writeAction("sri X27 X25 11")
    linkable_lm_cache__broadcast_global.writeAction("movir X16 128")
    linkable_lm_cache__broadcast_global.writeAction("bgt X25 X16 GenLinkableLMCache_rdxyv_max_child_modular_eq_zero")
    linkable_lm_cache__broadcast_global.writeAction("andi X27 X16 2047")
    linkable_lm_cache__broadcast_global.writeAction("beqi X16 0 GenLinkableLMCache_rdxyv_modular_eq_zero")
    linkable_lm_cache__broadcast_global.writeAction("addi X25 X25 1")
    linkable_lm_cache__broadcast_global.writeAction("jmp GenLinkableLMCache_rdxyv_modular_eq_zero")
    linkable_lm_cache__broadcast_global.writeAction("GenLinkableLMCache_rdxyv_max_child_modular_eq_zero: mov_imm2reg X25 128")
    linkable_lm_cache__broadcast_global.writeAction("GenLinkableLMCache_rdxyv_modular_eq_zero: evi X2 X28 255 4")
    linkable_lm_cache__broadcast_global.writeAction("evlb X28 linkable_lm_cache__broadcast_node")
    linkable_lm_cache__broadcast_global.writeAction("mov_imm2reg X17 0")
    linkable_lm_cache__broadcast_global.writeAction("GenLinkableLMCache_rdxyv_broadcast_loop: lshift X17 X16 11")
    linkable_lm_cache__broadcast_global.writeAction("add X0 X16 X16")
    linkable_lm_cache__broadcast_global.writeAction("ev X28 X28 X16 X16 8")
    linkable_lm_cache__broadcast_global.writeAction("sendops_wret X28 linkable_lm_cache__broadcast_global_fin X8 8 X16")
    linkable_lm_cache__broadcast_global.writeAction("addi X17 X17 1")
    linkable_lm_cache__broadcast_global.writeAction("blt X17 X25 GenLinkableLMCache_rdxyv_broadcast_loop")
    linkable_lm_cache__broadcast_global.writeAction("mov_imm2reg X26 0")
    linkable_lm_cache__broadcast_global.writeAction("yield")

    ## linkable_lm_cache__broadcast_node
    linkable_lm_cache__broadcast_node = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_node")
    linkable_lm_cache__broadcast_node.writeAction("addi X1 X29 0")
    linkable_lm_cache__broadcast_node.writeAction("sri X8 X25 6")
    linkable_lm_cache__broadcast_node.writeAction("movir X16 32")
    linkable_lm_cache__broadcast_node.writeAction("bgt X25 X16 GenLinkableLMCache_rdxyv_max_child_modular_eq_zero")
    linkable_lm_cache__broadcast_node.writeAction("andi X8 X16 63")
    linkable_lm_cache__broadcast_node.writeAction("beqi X16 0 GenLinkableLMCache_rdxyv_modular_eq_zero")
    linkable_lm_cache__broadcast_node.writeAction("addi X25 X25 1")
    linkable_lm_cache__broadcast_node.writeAction("jmp GenLinkableLMCache_rdxyv_modular_eq_zero")
    linkable_lm_cache__broadcast_node.writeAction("GenLinkableLMCache_rdxyv_max_child_modular_eq_zero: mov_imm2reg X25 32")
    linkable_lm_cache__broadcast_node.writeAction("GenLinkableLMCache_rdxyv_modular_eq_zero: evi X2 X28 255 4")
    linkable_lm_cache__broadcast_node.writeAction("evlb X28 linkable_lm_cache__broadcast_ud")
    linkable_lm_cache__broadcast_node.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Broadcast to %ld updowns' X0 X25")
    linkable_lm_cache__broadcast_node.writeAction("mov_imm2reg X17 0")
    linkable_lm_cache__broadcast_node.writeAction("GenLinkableLMCache_rdxyv_broadcast_loop: lshift X17 X16 6")
    linkable_lm_cache__broadcast_node.writeAction("add X0 X16 X16")
    linkable_lm_cache__broadcast_node.writeAction("ev X28 X28 X16 X16 8")
    linkable_lm_cache__broadcast_node.writeAction("sendops_wret X28 linkable_lm_cache__broadcast_node_fin X8 8 X16")
    linkable_lm_cache__broadcast_node.writeAction("addi X17 X17 1")
    linkable_lm_cache__broadcast_node.writeAction("blt X17 X25 GenLinkableLMCache_rdxyv_broadcast_loop")
    linkable_lm_cache__broadcast_node.writeAction("mov_imm2reg X26 0")
    linkable_lm_cache__broadcast_node.writeAction("yield")

    ## linkable_lm_cache__broadcast_ud
    linkable_lm_cache__broadcast_ud = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_ud")
    linkable_lm_cache__broadcast_ud.writeAction("addi X1 X29 0")
    linkable_lm_cache__broadcast_ud.writeAction("movir X25 64")
    linkable_lm_cache__broadcast_ud.writeAction("bgt X8 X25 GenLinkableLMCache_rdxyv_modular_eq_zero")
    linkable_lm_cache__broadcast_ud.writeAction("addi X8 X25 0")
    linkable_lm_cache__broadcast_ud.writeAction("GenLinkableLMCache_rdxyv_modular_eq_zero: evi X2 X28 255 4")
    linkable_lm_cache__broadcast_ud.writeAction("ev X28 X28 X9 X9 1")
    linkable_lm_cache__broadcast_ud.writeAction("mov_imm2reg X17 0")
    linkable_lm_cache__broadcast_ud.writeAction("GenLinkableLMCache_rdxyv_broadcast_loop: add X0 X17 X16")
    linkable_lm_cache__broadcast_ud.writeAction("ev X28 X28 X16 X16 8")
    linkable_lm_cache__broadcast_ud.writeAction("sendops_wret X28 linkable_lm_cache__broadcast_ud_fin X10 6 X16")
    linkable_lm_cache__broadcast_ud.writeAction("addi X17 X17 1")
    linkable_lm_cache__broadcast_ud.writeAction("blt X17 X25 GenLinkableLMCache_rdxyv_broadcast_loop")
    linkable_lm_cache__broadcast_ud.writeAction("mov_imm2reg X26 0")
    linkable_lm_cache__broadcast_ud.writeAction("yield")

    ## linkable_lm_cache__broadcast_ud_fin
    linkable_lm_cache__broadcast_ud_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_ud_fin")
    linkable_lm_cache__broadcast_ud_fin.writeAction("addi X26 X26 1")
    linkable_lm_cache__broadcast_ud_fin.writeAction("blt X26 X25 GenLinkableLMCache_rdxyv_continue")
    linkable_lm_cache__broadcast_ud_fin.writeAction("sendr_reply X0 X2 X16")
    linkable_lm_cache__broadcast_ud_fin.writeAction("yield_terminate")
    linkable_lm_cache__broadcast_ud_fin.writeAction("GenLinkableLMCache_rdxyv_continue: yield")

    ## linkable_lm_cache__broadcast_node_fin
    linkable_lm_cache__broadcast_node_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_node_fin")
    linkable_lm_cache__broadcast_node_fin.writeAction("addi X26 X26 1")
    linkable_lm_cache__broadcast_node_fin.writeAction("blt X26 X25 GenLinkableLMCache_rdxyv_continue")
    linkable_lm_cache__broadcast_node_fin.writeAction("sendr_reply X0 X2 X16")
    linkable_lm_cache__broadcast_node_fin.writeAction("yield_terminate")
    linkable_lm_cache__broadcast_node_fin.writeAction("GenLinkableLMCache_rdxyv_continue: yield")

    ## linkable_lm_cache__broadcast_global_fin
    linkable_lm_cache__broadcast_global_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_global_fin")
    linkable_lm_cache__broadcast_global_fin.writeAction("addi X26 X26 1")
    linkable_lm_cache__broadcast_global_fin.writeAction("beq X26 X25 GenLinkableLMCache_rdxyv_global_bcst_finish")
    linkable_lm_cache__broadcast_global_fin.writeAction("yield")
    linkable_lm_cache__broadcast_global_fin.writeAction("GenLinkableLMCache_rdxyv_global_bcst_finish: sendr_reply X0 X2 X16")
    linkable_lm_cache__broadcast_global_fin.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Finish broadcast init_ev_word = %lu, return to continuation %ld.' X0 X20 X29 ")
    linkable_lm_cache__broadcast_global_fin.writeAction("yieldt")

    ## linkable_lm_cache__broadcast_value_to_scratchpad
    linkable_lm_cache__broadcast_value_to_scratchpad = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__broadcast_value_to_scratchpad")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("sri X8 X16 32")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("add X7 X16 X16")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("andi X8 X17 15")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Event <linkable_lm_cache::broadcast_value_to_scratchpad> copy %ld words to lm_addr = %lu(0x%lx)' X0 X17 X16 X16")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("bcpyol X9 X16 X17")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("sendr_reply X1 X2 X16")
    linkable_lm_cache__broadcast_value_to_scratchpad.writeAction("yieldt")

    ## linkable_lm_cache__cache_init
    linkable_lm_cache__cache_init = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__cache_init")
    linkable_lm_cache__cache_init.writeAction("print ' '")
    linkable_lm_cache__cache_init.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Event <linkable_lm_cache::cache_init> ev_word=%ld' X0 EQT")
    linkable_lm_cache__cache_init.writeAction("addi X1 X16 0")
    linkable_lm_cache__cache_init.writeAction("addi X2 X19 0")
    linkable_lm_cache__cache_init.writeAction("evlb X19 linkable_lm_cache____cache_init_finish")
    linkable_lm_cache__cache_init.writeAction("evi X2 X20 255 4")
    linkable_lm_cache__cache_init.writeAction("evlb X20 linkable_lm_cache__broadcast_global")
    linkable_lm_cache__cache_init.writeAction("addi X7 X17 1472")
    linkable_lm_cache__cache_init.writeAction("movrl X8 0(X17) 0 8")
    linkable_lm_cache__cache_init.writeAction("addi X2 X18 0")
    linkable_lm_cache__cache_init.writeAction("evlb X18 linkable_lm_cache____cache_init_lane")
    linkable_lm_cache__cache_init.writeAction("movrl X18 8(X17) 0 8")
    linkable_lm_cache__cache_init.writeAction("movrl X8  16(X17) 0 8")
    linkable_lm_cache__cache_init.writeAction("movrl X0  24(X17) 0 8")
    linkable_lm_cache__cache_init.writeAction("addi X17 X21 32")
    linkable_lm_cache__cache_init.writeAction("bcpyoli X9 X21 2")
    linkable_lm_cache__cache_init.writeAction("send_wcont X20 X19 X17 8")
    linkable_lm_cache__cache_init.writeAction("yield")

    ## linkable_lm_cache____cache_init_lane
    linkable_lm_cache____cache_init_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_init_lane")
    linkable_lm_cache____cache_init_lane.writeAction("addi X7 X20 1536")
    linkable_lm_cache____cache_init_lane.writeAction("subi X8 X21 1")
    linkable_lm_cache____cache_init_lane.writeAction("movrl X21 0(X20) 0 8")
    linkable_lm_cache____cache_init_lane.writeAction("addi X7 X20 1544")
    linkable_lm_cache____cache_init_lane.writeAction("movrl X9 0(X20) 0 8")
    linkable_lm_cache____cache_init_lane.writeAction("addi X7 X20 1552")
    linkable_lm_cache____cache_init_lane.writeAction("bcpyoli X10 X20 2")
    linkable_lm_cache____cache_init_lane.writeAction("movir X16 -1")
    linkable_lm_cache____cache_init_lane.writeAction("movir X19 32")
    linkable_lm_cache____cache_init_lane.writeAction("addi X7 X17 1600")
    linkable_lm_cache____cache_init_lane.writeAction("mov_imm2reg X18 0")
    linkable_lm_cache____cache_init_lane.writeAction("GenLinkableLMCache_rdxyv_init_cache_loop: movwrl X16 X17(X18,1,1)")
    linkable_lm_cache____cache_init_lane.writeAction("blt X18 X19 GenLinkableLMCache_rdxyv_init_cache_loop")
    linkable_lm_cache____cache_init_lane.writeAction("sendr_reply X0 X16 X17")
    linkable_lm_cache____cache_init_lane.writeAction("yield_terminate")

    ## linkable_lm_cache____cache_init_finish
    linkable_lm_cache____cache_init_finish = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_init_finish")
    linkable_lm_cache____cache_init_finish.writeAction("sendr_wcont X16 X2 X8 X17")
    linkable_lm_cache____cache_init_finish.writeAction("yieldt")

    ## linkable_lm_cache__cache_get
    linkable_lm_cache__cache_get = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__cache_get")
    linkable_lm_cache__cache_get.writeAction("print ' '")
    linkable_lm_cache__cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Event <linkable_lm_cache::cache_get> ev_word = %lu income_cont = %lu' X0 EQT X1")
    linkable_lm_cache__cache_get.writeAction("addi X7 X16 1536")
    linkable_lm_cache__cache_get.writeAction("movlr 0(X16) X17 1 8")
    linkable_lm_cache__cache_get.writeAction("movlr  8(X16) X19 0 8")
    linkable_lm_cache__cache_get.writeAction("movir X18 0")
    linkable_lm_cache__cache_get.writeAction("hash X8 X18")
    linkable_lm_cache__cache_get.writeAction("and X18 X17 X18")
    linkable_lm_cache__cache_get.writeAction("add X18 X19 X18")
    linkable_lm_cache__cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Send key = [%ld] to lane %ld' X0 X8 X18")
    linkable_lm_cache__cache_get.writeAction("evi X2 X31 255 4")
    linkable_lm_cache__cache_get.writeAction("evlb X31 linkable_lm_cache____cache_get")
    linkable_lm_cache__cache_get.writeAction("ev X31  X31  X18 X18 8")
    linkable_lm_cache__cache_get.writeAction("sendops_wcont X31 X1 X8 2")
    linkable_lm_cache__cache_get.writeAction("yieldt")

    ## linkable_lm_cache____cache_get
    linkable_lm_cache____cache_get = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_get")
    linkable_lm_cache____cache_get.writeAction("print ' '")
    linkable_lm_cache____cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get] Event <linkable_lm_cache::__cache_get> key = %ld cont = %lu' X0 X8 X1")
    linkable_lm_cache____cache_get.writeAction("movir X23 32")
    linkable_lm_cache____cache_get.writeAction("mod X8 X23 X19")
    linkable_lm_cache____cache_get.writeAction("muli X19 X16 16")
    linkable_lm_cache____cache_get.writeAction("add X7 X16 X16")
    linkable_lm_cache____cache_get.writeAction("addi X16 X16 1600")
    linkable_lm_cache____cache_get.writeAction("movlr 0(X16) X17 0 8")
    linkable_lm_cache____cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get] Get incoming key = %ld Cached key = %ld at cache index %ld lm_addr = %lu(0x%lx)' X0 X8 X17 X19 X16")
    linkable_lm_cache____cache_get.writeAction("sri X17 X23 63")
    linkable_lm_cache____cache_get.writeAction("beqi X23 0 GenLinkableLMCache_rdxyv_cache_active_miss")
    linkable_lm_cache____cache_get.writeAction("movir X19 1")
    linkable_lm_cache____cache_get.writeAction("sli X19 X19 63")
    linkable_lm_cache____cache_get.writeAction("add X19 X8 X19")
    linkable_lm_cache____cache_get.writeAction("beq X19 X17 GenLinkableLMCache_rdxyv_cache_get_hit")
    linkable_lm_cache____cache_get.writeAction("jmp GenLinkableLMCache_rdxyv_cache_get_miss")
    linkable_lm_cache____cache_get.writeAction("GenLinkableLMCache_rdxyv_cache_active_miss: evi X2 X31 255 4")
    linkable_lm_cache____cache_get.writeAction("sendops_wcont X31 X1 X8 2")
    linkable_lm_cache____cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get] Cache get miss key = %ld, cache entry occupied/pending on an update.' X0 X8")
    linkable_lm_cache____cache_get.writeAction("yieldt")
    linkable_lm_cache____cache_get.writeAction("GenLinkableLMCache_rdxyv_cache_get_hit: move X8 0(X16) 0 8")
    linkable_lm_cache____cache_get.writeAction("move 8(X16) X22 0 8")
    linkable_lm_cache____cache_get.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get] Cache hit key = %ld, cached values = [%ld]' X0 X8 X22")
    linkable_lm_cache____cache_get.writeAction("movir X31 -1")
    linkable_lm_cache____cache_get.writeAction("sri X31 X31 1")
    linkable_lm_cache____cache_get.writeAction("send_wcont X1 X31 X16 2")
    linkable_lm_cache____cache_get.writeAction("move X19 0(X16) 0 8")
    linkable_lm_cache____cache_get.writeAction("yieldt")
    linkable_lm_cache____cache_get.writeAction("GenLinkableLMCache_rdxyv_cache_get_miss: print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get] Cache miss. Get values for key = %ld' X0 X8")
    linkable_lm_cache____cache_get.writeAction("addi X2 X31 0")
    linkable_lm_cache____cache_get.writeAction("evlb X31 linkable_lm_cache____cache_get_return")
    linkable_lm_cache____cache_get.writeAction("move 1552(X7) X23 0 8")
    linkable_lm_cache____cache_get.writeAction("lshift X8 X24 4")
    linkable_lm_cache____cache_get.writeAction("add X24 X23 X23")
    linkable_lm_cache____cache_get.writeAction("send_dmlm_ld X23 X31 2")
    linkable_lm_cache____cache_get.writeAction("addi X8 X21 0")
    linkable_lm_cache____cache_get.writeAction("addi X1 X20 0")
    linkable_lm_cache____cache_get.writeAction("yield")

    ## linkable_lm_cache____cache_get_return
    linkable_lm_cache____cache_get_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_get_return")
    linkable_lm_cache____cache_get_return.writeAction("print ' '")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Event word = %lu get key = %ld return ops = [%ld,  %ld, ]' X0 EQT X21 X8 X9")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Get pair success, return values = [%ld, %ld, ]' X0 X8 X9")
    linkable_lm_cache____cache_get_return.writeAction("movlr 0(X16) X17 0 8")
    linkable_lm_cache____cache_get_return.writeAction("beqi X17 -1 GenLinkableLMCache_rdxyv_skip_flush")
    linkable_lm_cache____cache_get_return.writeAction("sri X17 X23 63")
    linkable_lm_cache____cache_get_return.writeAction("beqi X23 0 GenLinkableLMCache_rdxyv_cache_occupied")
    linkable_lm_cache____cache_get_return.writeAction("movir X19 0")
    linkable_lm_cache____cache_get_return.writeAction("sli X17 X17 1")
    linkable_lm_cache____cache_get_return.writeAction("sri X17 X17 1")
    linkable_lm_cache____cache_get_return.writeAction("movlr 8(X16) X22 0 8")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Evict cached key = %ld, values = [%ld]' X0 X17 X22")
    linkable_lm_cache____cache_get_return.writeAction("addi X16 X16 8")
    linkable_lm_cache____cache_get_return.writeAction("addi X7 X18 1472")
    linkable_lm_cache____cache_get_return.writeAction("addi X2 X31 0")
    linkable_lm_cache____cache_get_return.writeAction("evlb X31 linkable_lm_cache____cache_get_flush_ack")
    linkable_lm_cache____cache_get_return.writeAction("movlr 1552(X7) X23 0 8")
    linkable_lm_cache____cache_get_return.writeAction("lshift X17 X24 4")
    linkable_lm_cache____cache_get_return.writeAction("add X24 X23 X23")
    linkable_lm_cache____cache_get_return.writeAction("send_dmlm X23 X31 X16 2")
    linkable_lm_cache____cache_get_return.writeAction("addi X16 X16 16")
    linkable_lm_cache____cache_get_return.writeAction("addi X19 X19 1")
    linkable_lm_cache____cache_get_return.writeAction("subi X16 X16 16")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Flush cached key = %ld values = [%ld, ]' X0 X17 X22")
    linkable_lm_cache____cache_get_return.writeAction("movrl X21 0(X16) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("movrl X8 8(X16) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Cache key = %lu loaded values = [%ld, %ld, ] at addr = 0x%lx' X0 X21 X8 X9 X16")
    linkable_lm_cache____cache_get_return.writeAction("yield")
    linkable_lm_cache____cache_get_return.writeAction("GenLinkableLMCache_rdxyv_skip_flush: movrl X21 0(X16) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("movrl X8 8(X16) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Cache key = %lu loaded values = [%ld, %ld, ] at addr = 0x%lx' X0 X21 X8 X9 X16")
    linkable_lm_cache____cache_get_return.writeAction("movir X31 -1")
    linkable_lm_cache____cache_get_return.writeAction("sri X31 X31 1")
    linkable_lm_cache____cache_get_return.writeAction("send_wcont X20 X31 X16 2")
    linkable_lm_cache____cache_get_return.writeAction("yieldt")
    linkable_lm_cache____cache_get_return.writeAction("GenLinkableLMCache_rdxyv_cache_occupied: addi X7 X18 1472")
    linkable_lm_cache____cache_get_return.writeAction("movrl X21 0(X18) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("move X8 8(X18) 0 8")
    linkable_lm_cache____cache_get_return.writeAction("movir X31 -1")
    linkable_lm_cache____cache_get_return.writeAction("sri X31 X31 1")
    linkable_lm_cache____cache_get_return.writeAction("send_wcont X20 X31 X18 2")
    linkable_lm_cache____cache_get_return.writeAction("yieldt")
    linkable_lm_cache____cache_get_return.writeAction("GenLinkableLMCache_rdxyv_get_fail: movir X23 -1")
    linkable_lm_cache____cache_get_return.writeAction("movir X31 -1")
    linkable_lm_cache____cache_get_return.writeAction("sri X31 X31 1")
    linkable_lm_cache____cache_get_return.writeAction("sendr_wcont X20 X31 X23 X17")
    linkable_lm_cache____cache_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_return] Key = %ld not exist, return failure.' X0 X17")
    linkable_lm_cache____cache_get_return.writeAction("yieldt")

    ## linkable_lm_cache____cache_get_flush_ack
    linkable_lm_cache____cache_get_flush_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_get_flush_ack")
    linkable_lm_cache____cache_get_flush_ack.writeAction("print ' '")
    linkable_lm_cache____cache_get_flush_ack.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_get_flush_ack] Flush pair return statuc = %lu addr = %lu(0x%lx)' X0 X8 X9 X9")
    linkable_lm_cache____cache_get_flush_ack.writeAction("subi X19 X19 1")
    linkable_lm_cache____cache_get_flush_ack.writeAction("bgti X19 0 GenLinkableLMCache_rdxyv_continue")
    linkable_lm_cache____cache_get_flush_ack.writeAction("movir X31 -1")
    linkable_lm_cache____cache_get_flush_ack.writeAction("sri X31 X31 1")
    linkable_lm_cache____cache_get_flush_ack.writeAction("send_wcont X20 X31 X16 2")
    linkable_lm_cache____cache_get_flush_ack.writeAction("movir X19 1")
    linkable_lm_cache____cache_get_flush_ack.writeAction("sli X19 X19 63")
    linkable_lm_cache____cache_get_flush_ack.writeAction("add X19 X21 X19")
    linkable_lm_cache____cache_get_flush_ack.writeAction("move X19 0(X16) 0 8")
    linkable_lm_cache____cache_get_flush_ack.writeAction("GenLinkableLMCache_rdxyv_continue: yieldt")

    ## linkable_lm_cache__cache_combine_value
    linkable_lm_cache__cache_combine_value = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__cache_combine_value")
    linkable_lm_cache__cache_combine_value.writeAction("print ' '")
    linkable_lm_cache__cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::cache_combine_value] Event <linkable_lm_cache::cache_combine_value> ev_word = %lu key = [%ld], cont = %lu' X0 EQT X8 X1")
    linkable_lm_cache__cache_combine_value.writeAction("addi X7 X16 1536")
    linkable_lm_cache__cache_combine_value.writeAction("movlr 0(X16) X17 0 8")
    linkable_lm_cache__cache_combine_value.writeAction("movlr 8(X16) X19 0 8")
    linkable_lm_cache__cache_combine_value.writeAction("movir X18 0")
    linkable_lm_cache__cache_combine_value.writeAction("hash X8 X18")
    linkable_lm_cache__cache_combine_value.writeAction("and X18 X17 X18")
    linkable_lm_cache__cache_combine_value.writeAction("add X18 X19 X18")
    linkable_lm_cache__cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::cache_combine_value] Send key = [%ld] values = [%ld] to lane %ld' X0 X8 X9 X18")
    linkable_lm_cache__cache_combine_value.writeAction("evi X2 X31 255 4")
    linkable_lm_cache__cache_combine_value.writeAction("evlb X31 linkable_lm_cache____cache_combine_value")
    linkable_lm_cache__cache_combine_value.writeAction("ev X31  X31  X18 X18 8")
    linkable_lm_cache__cache_combine_value.writeAction("sendops_wcont X31 X1 X8 2")
    linkable_lm_cache__cache_combine_value.writeAction("yieldt")

    ## linkable_lm_cache____cache_combine_value
    linkable_lm_cache____cache_combine_value = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_combine_value")
    linkable_lm_cache____cache_combine_value.writeAction("print ' '")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Event <linkable_lm_cache::__cache_combine_value> key = %ld, values = %ld' X0 X8 X9")
    linkable_lm_cache____cache_combine_value.writeAction("movir X22 32")
    linkable_lm_cache____cache_combine_value.writeAction("mod X8 X22 X22")
    linkable_lm_cache____cache_combine_value.writeAction("muli X22 X16 16")
    linkable_lm_cache____cache_combine_value.writeAction("add X7 X16 X16")
    linkable_lm_cache____cache_combine_value.writeAction("addi X16 X16 1600")
    linkable_lm_cache____cache_combine_value.writeAction("movlr 0(X16) X17 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Merge incoming key = %ld Cached key = %lu(0x%lx) at cache addr %lu(0x%lx) offset %ld' X0 X8 X17 X17 X16 X16 X22")
    linkable_lm_cache____cache_combine_value.writeAction("sri X17 X24 63")
    linkable_lm_cache____cache_combine_value.writeAction("beqi X24 0 GenLinkableLMCache_rdxyv_cache_occupied")
    linkable_lm_cache____cache_combine_value.writeAction("movir X22 1")
    linkable_lm_cache____cache_combine_value.writeAction("sli X22 X22 63")
    linkable_lm_cache____cache_combine_value.writeAction("or X22 X8 X25")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] key = %ld masked key = %lu(0x%lx) cached key = %lu(0x%lx)' X0 X8 X25 X25 X17 X17")
    linkable_lm_cache____cache_combine_value.writeAction("beq X25 X17 GenLinkableLMCache_rdxyv_cache_hit")
    linkable_lm_cache____cache_combine_value.writeAction("jmp GenLinkableLMCache_rdxyv_cache_evict")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_cache_occupied: evi X2 X21 255 4")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Cache entry occupied by key = %lu, push back to queue key = %ld values = [%ld, ]' X0 X17 X8 X9")
    linkable_lm_cache____cache_combine_value.writeAction("sendops_wcont X21 X1 X8 2")
    linkable_lm_cache____cache_combine_value.writeAction("yieldt")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_cache_hit: move 8(X16) X23 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Cache hit key = %ld, cached values = [%ld]' X0 X8 X23")
    linkable_lm_cache____cache_combine_value.writeAction("bge X9 X23 GenLinkableLMCache_rdxyv_combine_fail")
    linkable_lm_cache____cache_combine_value.writeAction("add X9 X23 X23")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Cache key = %ld combine result values = [%ld, ] at addr %lu(0x%lx)' X0 X8 X23 X16 X16")
    linkable_lm_cache____cache_combine_value.writeAction("movrl X23 8(X16) 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Combine key = %ld, result values = [%ld]' X0 X8 X23")
    linkable_lm_cache____cache_combine_value.writeAction("movrl X8 0(X16) 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("movir X21 -1")
    linkable_lm_cache____cache_combine_value.writeAction("sri X21 X21 1")
    linkable_lm_cache____cache_combine_value.writeAction("send_wcont X1 X21 X16 2 ")
    linkable_lm_cache____cache_combine_value.writeAction("movrl X17 0(X16) 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("yieldt")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_cache_evict: movrl X8 0(X16) 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Cache miss evict old key %lu. Get value for key = %ld from output key value set' X0 X17 X8")
    linkable_lm_cache____cache_combine_value.writeAction("movir X19 0")
    linkable_lm_cache____cache_combine_value.writeAction("beqi X17 -1 GenLinkableLMCache_rdxyv_skip_flush")
    linkable_lm_cache____cache_combine_value.writeAction("sub X17 X22 X17")
    linkable_lm_cache____cache_combine_value.writeAction("movlr 8(X16) X23 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Evict cached key = %ld, values = [%ld]' X0 X17 X23")
    linkable_lm_cache____cache_combine_value.writeAction("addi X16 X23 8")
    linkable_lm_cache____cache_combine_value.writeAction("addi X7 X18 1472")
    linkable_lm_cache____cache_combine_value.writeAction("addi X2 X21 0")
    linkable_lm_cache____cache_combine_value.writeAction("evlb X21 linkable_lm_cache____combine_value_put_pair_ack")
    linkable_lm_cache____cache_combine_value.writeAction("movlr 1552(X7) X24 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("lshift X17 X25 4")
    linkable_lm_cache____cache_combine_value.writeAction("add X25 X24 X24")
    linkable_lm_cache____cache_combine_value.writeAction("send_dmlm X24 X21 X23 2")
    linkable_lm_cache____cache_combine_value.writeAction("addi X23 X23 16")
    linkable_lm_cache____cache_combine_value.writeAction("addi X19 X19 1")
    linkable_lm_cache____cache_combine_value.writeAction("jmp GenLinkableLMCache_rdxyv_contiue")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_skip_flush: print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Invalid cached_key = %ld(0x%lx) skip put pair' X0 X17 X17")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_contiue: addi X2 X21 0")
    linkable_lm_cache____cache_combine_value.writeAction("evlb X21 linkable_lm_cache____combine_value_get_return")
    linkable_lm_cache____cache_combine_value.writeAction("move 1552(X7) X24 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("lshift X8 X25 4")
    linkable_lm_cache____cache_combine_value.writeAction("add X25 X24 X24")
    linkable_lm_cache____cache_combine_value.writeAction("send_dmlm_ld X24 X21 2")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Get pair key = %ld from output key value set' X0 X8")
    linkable_lm_cache____cache_combine_value.writeAction("move X9 8(X16) 0 8")
    linkable_lm_cache____cache_combine_value.writeAction("addi X8 X17 0")
    linkable_lm_cache____cache_combine_value.writeAction("addi X1 X20 0")
    linkable_lm_cache____cache_combine_value.writeAction("addi X19 X19 1")
    linkable_lm_cache____cache_combine_value.writeAction("yield")
    linkable_lm_cache____cache_combine_value.writeAction("GenLinkableLMCache_rdxyv_combine_fail: movir X24 -1")
    linkable_lm_cache____cache_combine_value.writeAction("sendr_reply X24 X8 X25")
    linkable_lm_cache____cache_combine_value.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_combine_value] Combine fail key = %ld, cached values [%ld] update value = [%ld] return failure.' X0 X8 X23 X9")
    linkable_lm_cache____cache_combine_value.writeAction("yieldt")

    ## linkable_lm_cache____combine_value_get_return
    linkable_lm_cache____combine_value_get_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____combine_value_get_return")
    linkable_lm_cache____combine_value_get_return.writeAction("print ' '")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_get_return] Event word = %lu Get key = %ld return ops = [%ld, %ld, ]' X0 EQT X17 X8 X9")
    linkable_lm_cache____combine_value_get_return.writeAction("movlr 8(X16) X23 0 8")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_get_return] Cached key = %ld values = [%ld, ]' X0 X17 X23 ")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_get_return] Get pair success, return values = [%ld, %ld, ]' X0 X8 X9")
    linkable_lm_cache____combine_value_get_return.writeAction("bge X23 X8 GenLinkableLMCache_rdxyv_combine_fail")
    linkable_lm_cache____combine_value_get_return.writeAction("add X23 X8 X23")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_get_return] Store key = %ld combine result values = [%ld, ] at addr %lu(0x%lx)' X0 X17 X23 X16 X16")
    linkable_lm_cache____combine_value_get_return.writeAction("movrl X23 8(X16) 0 8")
    linkable_lm_cache____combine_value_get_return.writeAction("GenLinkableLMCache_rdxyv_get_fail: subi X19 X19 1")
    linkable_lm_cache____combine_value_get_return.writeAction("beqi X19 0 GenLinkableLMCache_rdxyv_finish_write_back")
    linkable_lm_cache____combine_value_get_return.writeAction("yield")
    linkable_lm_cache____combine_value_get_return.writeAction("GenLinkableLMCache_rdxyv_finish_write_back: movir X22 1")
    linkable_lm_cache____combine_value_get_return.writeAction("sli X22 X22 63")
    linkable_lm_cache____combine_value_get_return.writeAction("or X22 X17 X17")
    linkable_lm_cache____combine_value_get_return.writeAction("sli X17 X24 1")
    linkable_lm_cache____combine_value_get_return.writeAction("sri X24 X24 1")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_get_return] Finish write back store key = %ld (masked = %lu) to lm addr = 0x%lx' X0 X17 X24 X16")
    linkable_lm_cache____combine_value_get_return.writeAction("movir X21 -1")
    linkable_lm_cache____combine_value_get_return.writeAction("sri X21 X21 1")
    linkable_lm_cache____combine_value_get_return.writeAction("send_wcont X20 X21 X16 2 ")
    linkable_lm_cache____combine_value_get_return.writeAction("movrl X17 0(X16) 0 8")
    linkable_lm_cache____combine_value_get_return.writeAction("yieldt")
    linkable_lm_cache____combine_value_get_return.writeAction("GenLinkableLMCache_rdxyv_combine_fail: movir X24 -1")
    linkable_lm_cache____combine_value_get_return.writeAction("sendr_wcont X1 X2 X24 X17")
    linkable_lm_cache____combine_value_get_return.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Combine fail key = %ld, loaded values [%ld] update values = [%ld] return failure.' X0 X8 X8 X9 X23")
    linkable_lm_cache____combine_value_get_return.writeAction("yieldt")

    ## linkable_lm_cache____combine_value_put_pair_ack
    linkable_lm_cache____combine_value_put_pair_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____combine_value_put_pair_ack")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("print ' '")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__combine_value_put_pair_ack] Event word = %lu put pair return operands = [%lu, ]' X0 EQT X8")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("subi X19 X19 1")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("beqi X19 0 GenLinkableLMCache_rdxyv_finish_write_back")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("yield")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("GenLinkableLMCache_rdxyv_finish_write_back: movir X22 1")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("sli X22 X22 63")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("movir X21 -1")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("sri X21 X21 1")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("send_wcont X20 X21 X16 2")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("or X22 X17 X17")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("movrl X17 0(X16) 0 8")
    linkable_lm_cache____combine_value_put_pair_ack.writeAction("yieldt")

    ## linkable_lm_cache__cache_flush
    linkable_lm_cache__cache_flush = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache__cache_flush")
    linkable_lm_cache__cache_flush.writeAction("print ' '")
    linkable_lm_cache__cache_flush.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache] Event <linkable_lm_cache::cache_flush> ev_word=%ld' X0 EQT")
    linkable_lm_cache__cache_flush.writeAction("addi X1 X16 0")
    linkable_lm_cache__cache_flush.writeAction("addi X2 X19 0")
    linkable_lm_cache__cache_flush.writeAction("movlr 1544(X7) X23 0 8")
    linkable_lm_cache__cache_flush.writeAction("movlr 1536(X7) X22 0 8")
    linkable_lm_cache__cache_flush.writeAction("addi X22 X22 1")
    linkable_lm_cache__cache_flush.writeAction("evlb X19 linkable_lm_cache____cache_flush_ack")
    linkable_lm_cache__cache_flush.writeAction("evi X2 X20 255 4")
    linkable_lm_cache__cache_flush.writeAction("evlb X20 linkable_lm_cache__broadcast_global")
    linkable_lm_cache__cache_flush.writeAction("addi X7 X17 1472")
    linkable_lm_cache__cache_flush.writeAction("movrl X22 0(X17) 0 8")
    linkable_lm_cache__cache_flush.writeAction("addi X2 X18 0")
    linkable_lm_cache__cache_flush.writeAction("evlb X18 linkable_lm_cache____cache_flush_lane")
    linkable_lm_cache__cache_flush.writeAction("movrl X18 8(X17) 0 8")
    linkable_lm_cache__cache_flush.writeAction("send_wcont X20 X19 X17 8")
    linkable_lm_cache__cache_flush.writeAction("yield")

    ## linkable_lm_cache____cache_flush_lane
    linkable_lm_cache____cache_flush_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_flush_lane")
    linkable_lm_cache____cache_flush_lane.writeAction("print ' '")
    linkable_lm_cache____cache_flush_lane.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane] Flush the cache at offset 1600 to DRAM' X0")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X1 X17 0")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X7 X20 1600")
    linkable_lm_cache____cache_flush_lane.writeAction("movir X16 32")
    linkable_lm_cache____cache_flush_lane.writeAction("muli X16 X16 16")
    linkable_lm_cache____cache_flush_lane.writeAction("add X16 X20 X16")
    linkable_lm_cache____cache_flush_lane.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane] Flush cache from offset = %lu(0x%lx) to offset = %lu(0x%lx) (X7 = %lu(0x%lx))' X0 X20 X20 X16 X16 X7")
    linkable_lm_cache____cache_flush_lane.writeAction("movir X19 0")
    linkable_lm_cache____cache_flush_lane.writeAction("movir X22 -1")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X2 X23 0")
    linkable_lm_cache____cache_flush_lane.writeAction("evlb X23 linkable_lm_cache____cache_flush_lane_ack")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X7 X18 1472")
    linkable_lm_cache____cache_flush_lane.writeAction("GenLinkableLMCache_rdxyv_flush_loop: bge X20 X16 GenLinkableLMCache_rdxyv_break_flush_loop")
    linkable_lm_cache____cache_flush_lane.writeAction("movlr 0(X20) X21 0 8")
    linkable_lm_cache____cache_flush_lane.writeAction("beq X21 X22 GenLinkableLMCache_rdxyv_continue_flush_loop")
    linkable_lm_cache____cache_flush_lane.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane] Flush key = %ld at lm_addr = %lu(0x%lx)' X0 X21 X20 X20")
    linkable_lm_cache____cache_flush_lane.writeAction("sli X21 X21 1")
    linkable_lm_cache____cache_flush_lane.writeAction("sri X21 X21 1")
    linkable_lm_cache____cache_flush_lane.writeAction("movlr 8(X20) X24 0 8")
    linkable_lm_cache____cache_flush_lane.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane] Flush key = %lu at lm_addr = %lu(0x%lx), values = [%ld]' X0 X21 X20 X20 X24 X25")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X20 X20 8")
    linkable_lm_cache____cache_flush_lane.writeAction("movlr 1552(X7) X24 0 8")
    linkable_lm_cache____cache_flush_lane.writeAction("lshift X21 X25 4")
    linkable_lm_cache____cache_flush_lane.writeAction("add X25 X24 X24")
    linkable_lm_cache____cache_flush_lane.writeAction("send_dmlm X24 X23 X20 2")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X20 X20 16")
    linkable_lm_cache____cache_flush_lane.writeAction("addi X19 X19 1")
    linkable_lm_cache____cache_flush_lane.writeAction("jmp GenLinkableLMCache_rdxyv_flush_loop")
    linkable_lm_cache____cache_flush_lane.writeAction("GenLinkableLMCache_rdxyv_continue_flush_loop: addi X20 X20 16")
    linkable_lm_cache____cache_flush_lane.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane] Invalid key %ld, skip flush' X0 X21")
    linkable_lm_cache____cache_flush_lane.writeAction("jmp GenLinkableLMCache_rdxyv_flush_loop")
    linkable_lm_cache____cache_flush_lane.writeAction("GenLinkableLMCache_rdxyv_break_flush_loop: beqi X19 0 GenLinkableLMCache_rdxyv_empty_cache")
    linkable_lm_cache____cache_flush_lane.writeAction("yield")
    linkable_lm_cache____cache_flush_lane.writeAction("GenLinkableLMCache_rdxyv_empty_cache: movir X21 -1")
    linkable_lm_cache____cache_flush_lane.writeAction("sri X21 X21 1")
    linkable_lm_cache____cache_flush_lane.writeAction("sendr_wcont X17 X21 X2 X16 ")
    linkable_lm_cache____cache_flush_lane.writeAction("yieldt")

    ## linkable_lm_cache____cache_flush_lane_ack
    linkable_lm_cache____cache_flush_lane_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_flush_lane_ack")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("subi X19 X19 1")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("bnei X19 0 GenLinkableLMCache_rdxyv_continue_flush_loop")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("movir X21 -1")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("sri X21 X21 1")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("sendr_wcont X17 X21 X2 X16 ")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_lane_ack] Flush complete, return to global master %lu' X0 X17")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("yieldt")
    linkable_lm_cache____cache_flush_lane_ack.writeAction("GenLinkableLMCache_rdxyv_continue_flush_loop: yield")

    ## linkable_lm_cache____cache_flush_ack
    linkable_lm_cache____cache_flush_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "linkable_lm_cache____cache_flush_ack")
    linkable_lm_cache____cache_flush_ack.writeAction("print ' '")
    linkable_lm_cache____cache_flush_ack.writeAction("print '[DEBUG][NWID %ld][linkable_lm_cache::__cache_flush_ack] Finish flushing the cache on %ld lanes. Return to user continuation %lu' X0 X22 X16")
    linkable_lm_cache____cache_flush_ack.writeAction("movir X20 -1")
    linkable_lm_cache____cache_flush_ack.writeAction("sri X20 X20 1")
    linkable_lm_cache____cache_flush_ack.writeAction("sendr_wcont X16 X20 X22 X22")
    linkable_lm_cache____cache_flush_ack.writeAction("yieldt")