from EFA_v2 import EFA, State, Transition

def efaProgram_spmvMSR_rh_nlbstrm_on(efa):

    ## init_null_state with ID 0
    init_null_state_0 = State()
    efa.add_state(init_null_state_0)
    efa.add_initId(init_null_state_0.state_id)

    ## Broadcast__broadcast_global with ID 0
    Broadcast__broadcast_global_0 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 0)
    Broadcast__broadcast_global_0.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global_0.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global_0.writeAction("movir X16 512")
    Broadcast__broadcast_global_0.writeAction("bgt X25 X16 GenLinkableBroadcast_cjcnm_max_child_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global_0.writeAction("beqi X16 0 GenLinkableBroadcast_cjcnm_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global_0.writeAction("jmp GenLinkableBroadcast_cjcnm_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_cjcnm_max_child_modular_eq_zero: mov_imm2reg X25 512")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_cjcnm_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global_0.writeAction("evlb X28 1")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_cjcnm_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global_0.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global_0.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global_0.writeAction("sendops_wret X28 5 X8 8 X16")
    Broadcast__broadcast_global_0.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global_0.writeAction("blt X17 X25 GenLinkableBroadcast_cjcnm_broadcast_loop")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global_0.writeAction("yield")

    ## Broadcast__broadcast_node with ID 1
    Broadcast__broadcast_node_1 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 1)
    Broadcast__broadcast_node_1.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node_1.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node_1.writeAction("movir X16 32")
    Broadcast__broadcast_node_1.writeAction("bgt X25 X16 GenLinkableBroadcast_cjcnm_max_child_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node_1.writeAction("beqi X16 0 GenLinkableBroadcast_cjcnm_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node_1.writeAction("jmp GenLinkableBroadcast_cjcnm_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_cjcnm_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_cjcnm_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node_1.writeAction("evlb X28 2")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_cjcnm_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node_1.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node_1.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node_1.writeAction("sendops_wret X28 4 X8 8 X16")
    Broadcast__broadcast_node_1.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node_1.writeAction("blt X17 X25 GenLinkableBroadcast_cjcnm_broadcast_loop")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node_1.writeAction("yield")

    ## Broadcast__broadcast_ud with ID 2
    Broadcast__broadcast_ud_2 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 2)
    Broadcast__broadcast_ud_2.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud_2.writeAction("movir X25 64")
    Broadcast__broadcast_ud_2.writeAction("bgt X8 X25 GenLinkableBroadcast_cjcnm_modular_eq_zero")
    Broadcast__broadcast_ud_2.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_cjcnm_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_cjcnm_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud_2.writeAction("sendops_wret X28 3 X10 6 X16")
    Broadcast__broadcast_ud_2.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud_2.writeAction("blt X17 X25 GenLinkableBroadcast_cjcnm_broadcast_loop")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud_2.writeAction("yield")

    ## Broadcast__broadcast_ud_fin with ID 3
    Broadcast__broadcast_ud_fin_3 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 3)
    Broadcast__broadcast_ud_fin_3.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin_3.writeAction("blt X26 X25 GenLinkableBroadcast_cjcnm_continue")
    Broadcast__broadcast_ud_fin_3.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_ud_fin_3.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin_3.writeAction("GenLinkableBroadcast_cjcnm_continue: yield")

    ## Broadcast__broadcast_node_fin with ID 4
    Broadcast__broadcast_node_fin_4 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 4)
    Broadcast__broadcast_node_fin_4.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin_4.writeAction("blt X26 X25 GenLinkableBroadcast_cjcnm_continue")
    Broadcast__broadcast_node_fin_4.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin_4.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin_4.writeAction("GenLinkableBroadcast_cjcnm_continue: yield")

    ## Broadcast__broadcast_global_fin with ID 5
    Broadcast__broadcast_global_fin_5 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 5)
    Broadcast__broadcast_global_fin_5.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin_5.writeAction("beq X26 X25 GenLinkableBroadcast_cjcnm_global_bcst_finish")
    Broadcast__broadcast_global_fin_5.writeAction("yield")
    Broadcast__broadcast_global_fin_5.writeAction("GenLinkableBroadcast_cjcnm_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin_5.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad with ID 6
    Broadcast__broadcast_value_to_scratchpad_6 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 6)
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("yieldt")

    ## spmv__map_shuffle_reduce with ID 7
    spmv__map_shuffle_reduce_7 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 7)
    spmv__map_shuffle_reduce_7.writeAction("addi X7 X20 688")
    spmv__map_shuffle_reduce_7.writeAction("addi X1 X31 0")
    spmv__map_shuffle_reduce_7.writeAction("move X31 0(X20) 0 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X8 X16 0")
    spmv__map_shuffle_reduce_7.writeAction("addi X10 X27 0")
    spmv__map_shuffle_reduce_7.writeAction("mul X9 X27 X19")
    spmv__map_shuffle_reduce_7.writeAction("addi X2 X21 0")
    spmv__map_shuffle_reduce_7.writeAction("evlb X21 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X7 X20 800")
    spmv__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    spmv__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    spmv__map_shuffle_reduce_7.writeAction("evi X2 X26 255 4")
    spmv__map_shuffle_reduce_7.writeAction("evlb X26 9")
    spmv__map_shuffle_reduce_7.writeAction("sendr_wcont X26 X21 X16 X19")
    spmv__map_shuffle_reduce_7.writeAction("evi X2 X30 255 4")
    spmv__map_shuffle_reduce_7.writeAction("evlb X30 11")
    spmv__map_shuffle_reduce_7.writeAction("movir X17 704")
    spmv__map_shuffle_reduce_7.writeAction("add X7 X17 X17")
    spmv__map_shuffle_reduce_7.writeAction("movrl X27 0(X17) 0 8")
    spmv__map_shuffle_reduce_7.writeAction("movir X18 0")
    spmv__map_shuffle_reduce_7.writeAction("evlb X18 20")
    spmv__map_shuffle_reduce_7.writeAction("movrl X18 8(X17) 0 8")
    spmv__map_shuffle_reduce_7.writeAction("movrl X27  16(X17) 0 8")
    spmv__map_shuffle_reduce_7.writeAction("movrl X0 24(X17) 0 8")
    spmv__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    spmv__map_shuffle_reduce_7.writeAction("movir X18 0")
    spmv__map_shuffle_reduce_7.writeAction("evlb X18 18")
    spmv__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    spmv__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    spmv__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    spmv__map_shuffle_reduce_7.writeAction("movir X18 0")
    spmv__map_shuffle_reduce_7.writeAction("evlb X18 19")
    spmv__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    spmv__map_shuffle_reduce_7.writeAction("addi X12 X29 0")
    spmv__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    spmv__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8 ")
    spmv__map_shuffle_reduce_7.writeAction("movir X26 0")
    spmv__map_shuffle_reduce_7.writeAction("addi X9 X19 0")
    spmv__map_shuffle_reduce_7.writeAction("perflog 1 0 'UDKVMSR Initialization setup finished.' ")
    spmv__map_shuffle_reduce_7.writeAction("yield")

    ## spmv__finish_init_udkvmsr with ID 8
    spmv__finish_init_udkvmsr_8 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 8)
    spmv__finish_init_udkvmsr_8.writeAction("addi X26 X26 1")
    spmv__finish_init_udkvmsr_8.writeAction("bgei X26 4 spmvMSREFA_okdhl_finish_initialize_udkvmsr")
    spmv__finish_init_udkvmsr_8.writeAction("yield")
    spmv__finish_init_udkvmsr_8.writeAction("spmvMSREFA_okdhl_finish_initialize_udkvmsr: addi X2 X30 0")
    spmv__finish_init_udkvmsr_8.writeAction("evlb X30 21")
    spmv__finish_init_udkvmsr_8.writeAction("perflog 1 0 'UDKVMSR Initialization Finished.' ")
    spmv__finish_init_udkvmsr_8.writeAction("sendr_wcont X30 X31 X16 X19")
    spmv__finish_init_udkvmsr_8.writeAction("yield")

    ## Test_input__generate_partition_array with ID 9
    Test_input__generate_partition_array_9 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 9)
    Test_input__generate_partition_array_9.writeAction("addi X9 X21 0")
    Test_input__generate_partition_array_9.writeAction("addi X1 X16 0")
    Test_input__generate_partition_array_9.writeAction("addi X2 X27 0")
    Test_input__generate_partition_array_9.writeAction("evlb X27 10")
    Test_input__generate_partition_array_9.writeAction("addi X7 X29 800")
    Test_input__generate_partition_array_9.writeAction("movlr 0(X29) X19 1 8")
    Test_input__generate_partition_array_9.writeAction("movlr 0(X29) X20 1 8")
    Test_input__generate_partition_array_9.writeAction("sli X20 X17 4")
    Test_input__generate_partition_array_9.writeAction("add X19 X17 X17")
    Test_input__generate_partition_array_9.writeAction("div X20 X21 X22")
    Test_input__generate_partition_array_9.writeAction("mul X22 X21 X30")
    Test_input__generate_partition_array_9.writeAction("beq X30 X20 spmvMSREFA_okdhl_modular_eq_zero")
    Test_input__generate_partition_array_9.writeAction("addi X22 X22 1")
    Test_input__generate_partition_array_9.writeAction("spmvMSREFA_okdhl_modular_eq_zero: sli X22 X23 4")
    Test_input__generate_partition_array_9.writeAction("addi X8 X18 0")
    Test_input__generate_partition_array_9.writeAction("sli X21 X24 4")
    Test_input__generate_partition_array_9.writeAction("add X8 X24 X24")
    Test_input__generate_partition_array_9.writeAction("spmvMSREFA_okdhl_write_partition_array_loop: bge X18 X24 spmvMSREFA_okdhl_loop_break")
    Test_input__generate_partition_array_9.writeAction("add X19 X23 X25")
    Test_input__generate_partition_array_9.writeAction("ble X25 X17 spmvMSREFA_okdhl_continue")
    Test_input__generate_partition_array_9.writeAction("addi X17 X25 0")
    Test_input__generate_partition_array_9.writeAction("spmvMSREFA_okdhl_continue: sendr2_dmlm X18 X27 X19 X25")
    Test_input__generate_partition_array_9.writeAction("addi X18 X18 16")
    Test_input__generate_partition_array_9.writeAction("addi X25 X19 0")
    Test_input__generate_partition_array_9.writeAction("jmp spmvMSREFA_okdhl_write_partition_array_loop")
    Test_input__generate_partition_array_9.writeAction("spmvMSREFA_okdhl_loop_break: movir X26 0")
    Test_input__generate_partition_array_9.writeAction("yield")

    ## Test_input__write_partition_array_return with ID 10
    Test_input__write_partition_array_return_10 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 10)
    Test_input__write_partition_array_return_10.writeAction("addi X26 X26 1")
    Test_input__write_partition_array_return_10.writeAction("blt X26 X21 spmvMSREFA_okdhl_continue")
    Test_input__write_partition_array_return_10.writeAction("sendr_wcont X16 X2 X18 X21")
    Test_input__write_partition_array_return_10.writeAction("yieldt")
    Test_input__write_partition_array_return_10.writeAction("spmvMSREFA_okdhl_continue: yield")

    ## spmv__broadcast_global with ID 11
    spmv__broadcast_global_11 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 11)
    spmv__broadcast_global_11.writeAction("addi X8 X27 0")
    spmv__broadcast_global_11.writeAction("sri X27 X25 11")
    spmv__broadcast_global_11.writeAction("movir X16 512")
    spmv__broadcast_global_11.writeAction("bgt X25 X16 spmvMSREFA_okdhl_max_child_modular_eq_zero")
    spmv__broadcast_global_11.writeAction("andi X27 X16 2047")
    spmv__broadcast_global_11.writeAction("beqi X16 0 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__broadcast_global_11.writeAction("addi X25 X25 1")
    spmv__broadcast_global_11.writeAction("jmp spmvMSREFA_okdhl_modular_eq_zero")
    spmv__broadcast_global_11.writeAction("spmvMSREFA_okdhl_max_child_modular_eq_zero: mov_imm2reg X25 512")
    spmv__broadcast_global_11.writeAction("spmvMSREFA_okdhl_modular_eq_zero: evi X2 X28 255 4")
    spmv__broadcast_global_11.writeAction("evlb X28 12")
    spmv__broadcast_global_11.writeAction("mov_imm2reg X17 0")
    spmv__broadcast_global_11.writeAction("spmvMSREFA_okdhl_broadcast_loop: lshift X17 X16 11")
    spmv__broadcast_global_11.writeAction("add X0 X16 X16")
    spmv__broadcast_global_11.writeAction("ev X28 X28 X16 X16 8")
    spmv__broadcast_global_11.writeAction("sendops_wret X28 16 X8 8 X16")
    spmv__broadcast_global_11.writeAction("addi X17 X17 1")
    spmv__broadcast_global_11.writeAction("blt X17 X25 spmvMSREFA_okdhl_broadcast_loop")
    spmv__broadcast_global_11.writeAction("mov_imm2reg X26 0")
    spmv__broadcast_global_11.writeAction("yield")

    ## spmv__broadcast_node with ID 12
    spmv__broadcast_node_12 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 12)
    spmv__broadcast_node_12.writeAction("addi X1 X29 0")
    spmv__broadcast_node_12.writeAction("sri X8 X25 6")
    spmv__broadcast_node_12.writeAction("movir X16 32")
    spmv__broadcast_node_12.writeAction("bgt X25 X16 spmvMSREFA_okdhl_max_child_modular_eq_zero")
    spmv__broadcast_node_12.writeAction("andi X8 X16 63")
    spmv__broadcast_node_12.writeAction("beqi X16 0 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__broadcast_node_12.writeAction("addi X25 X25 1")
    spmv__broadcast_node_12.writeAction("jmp spmvMSREFA_okdhl_modular_eq_zero")
    spmv__broadcast_node_12.writeAction("spmvMSREFA_okdhl_max_child_modular_eq_zero: mov_imm2reg X25 32")
    spmv__broadcast_node_12.writeAction("spmvMSREFA_okdhl_modular_eq_zero: evi X2 X28 255 4")
    spmv__broadcast_node_12.writeAction("evlb X28 13")
    spmv__broadcast_node_12.writeAction("mov_imm2reg X17 0")
    spmv__broadcast_node_12.writeAction("spmvMSREFA_okdhl_broadcast_loop: lshift X17 X16 6")
    spmv__broadcast_node_12.writeAction("add X0 X16 X16")
    spmv__broadcast_node_12.writeAction("ev X28 X28 X16 X16 8")
    spmv__broadcast_node_12.writeAction("sendops_wret X28 15 X8 8 X16")
    spmv__broadcast_node_12.writeAction("addi X17 X17 1")
    spmv__broadcast_node_12.writeAction("blt X17 X25 spmvMSREFA_okdhl_broadcast_loop")
    spmv__broadcast_node_12.writeAction("mov_imm2reg X26 0")
    spmv__broadcast_node_12.writeAction("yield")

    ## spmv__broadcast_ud with ID 13
    spmv__broadcast_ud_13 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 13)
    spmv__broadcast_ud_13.writeAction("addi X1 X29 0")
    spmv__broadcast_ud_13.writeAction("movir X25 64")
    spmv__broadcast_ud_13.writeAction("bgt X8 X25 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__broadcast_ud_13.writeAction("addi X8 X25 0")
    spmv__broadcast_ud_13.writeAction("spmvMSREFA_okdhl_modular_eq_zero: evi X2 X28 255 4")
    spmv__broadcast_ud_13.writeAction("ev X28 X28 X9 X9 1")
    spmv__broadcast_ud_13.writeAction("mov_imm2reg X17 0")
    spmv__broadcast_ud_13.writeAction("spmvMSREFA_okdhl_broadcast_loop: add X0 X17 X16")
    spmv__broadcast_ud_13.writeAction("ev X28 X28 X16 X16 8")
    spmv__broadcast_ud_13.writeAction("sendops_wret X28 14 X10 6 X16")
    spmv__broadcast_ud_13.writeAction("addi X17 X17 1")
    spmv__broadcast_ud_13.writeAction("blt X17 X25 spmvMSREFA_okdhl_broadcast_loop")
    spmv__broadcast_ud_13.writeAction("mov_imm2reg X26 0")
    spmv__broadcast_ud_13.writeAction("yield")

    ## spmv__broadcast_ud_fin with ID 14
    spmv__broadcast_ud_fin_14 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 14)
    spmv__broadcast_ud_fin_14.writeAction("addi X26 X26 1")
    spmv__broadcast_ud_fin_14.writeAction("blt X26 X25 spmvMSREFA_okdhl_continue")
    spmv__broadcast_ud_fin_14.writeAction("sendr_reply X0 X2 X16")
    spmv__broadcast_ud_fin_14.writeAction("yield_terminate")
    spmv__broadcast_ud_fin_14.writeAction("spmvMSREFA_okdhl_continue: yield")

    ## spmv__broadcast_node_fin with ID 15
    spmv__broadcast_node_fin_15 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 15)
    spmv__broadcast_node_fin_15.writeAction("addi X26 X26 1")
    spmv__broadcast_node_fin_15.writeAction("blt X26 X25 spmvMSREFA_okdhl_continue")
    spmv__broadcast_node_fin_15.writeAction("sendr_reply X0 X2 X16")
    spmv__broadcast_node_fin_15.writeAction("yield_terminate")
    spmv__broadcast_node_fin_15.writeAction("spmvMSREFA_okdhl_continue: yield")

    ## spmv__broadcast_global_fin with ID 16
    spmv__broadcast_global_fin_16 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 16)
    spmv__broadcast_global_fin_16.writeAction("addi X26 X26 1")
    spmv__broadcast_global_fin_16.writeAction("beq X26 X25 spmvMSREFA_okdhl_global_bcst_finish")
    spmv__broadcast_global_fin_16.writeAction("yield")
    spmv__broadcast_global_fin_16.writeAction("spmvMSREFA_okdhl_global_bcst_finish: sendr_reply X0 X2 X16")
    spmv__broadcast_global_fin_16.writeAction("yieldt")

    ## spmv__broadcast_value_to_scratchpad with ID 17
    spmv__broadcast_value_to_scratchpad_17 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 17)
    spmv__broadcast_value_to_scratchpad_17.writeAction("sri X8 X16 32")
    spmv__broadcast_value_to_scratchpad_17.writeAction("add X7 X16 X16")
    spmv__broadcast_value_to_scratchpad_17.writeAction("andi X8 X17 15")
    spmv__broadcast_value_to_scratchpad_17.writeAction("bcpyol X9 X16 X17")
    spmv__broadcast_value_to_scratchpad_17.writeAction("sendr_reply X1 X2 X16")
    spmv__broadcast_value_to_scratchpad_17.writeAction("yieldt")

    ## spmv__init_input_kvset_on_lane with ID 18
    spmv__init_input_kvset_on_lane_18 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 18)
    spmv__init_input_kvset_on_lane_18.writeAction("movir X16 800")
    spmv__init_input_kvset_on_lane_18.writeAction("add X7 X16 X16")
    spmv__init_input_kvset_on_lane_18.writeAction("bcpyoli X8 X16 2")
    spmv__init_input_kvset_on_lane_18.writeAction("sendr_reply X0 X16 X28")
    spmv__init_input_kvset_on_lane_18.writeAction("yield_terminate")

    ## spmv__init_output_kvset_on_lane with ID 19
    spmv__init_output_kvset_on_lane_19 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 19)
    spmv__init_output_kvset_on_lane_19.writeAction("movir X16 864")
    spmv__init_output_kvset_on_lane_19.writeAction("add X7 X16 X16")
    spmv__init_output_kvset_on_lane_19.writeAction("bcpyoli X8 X16  2")
    spmv__init_output_kvset_on_lane_19.writeAction("sendr_reply X0 X16 X28")
    spmv__init_output_kvset_on_lane_19.writeAction("yield_terminate")

    ## spmv__init_sp_lane with ID 20
    spmv__init_sp_lane_20 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 20)
    spmv__init_sp_lane_20.writeAction("mov_imm2reg UDPR_0 0")
    spmv__init_sp_lane_20.writeAction("addi X7 X20 640")
    spmv__init_sp_lane_20.writeAction("move UDPR_0 0(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("move UDPR_0 8(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("move UDPR_0 24(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("movir X28 32")
    spmv__init_sp_lane_20.writeAction("move X28 32(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("subi X8 X28 1")
    spmv__init_sp_lane_20.writeAction("move X28 40(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("move X9 56(X20) 0 8")
    spmv__init_sp_lane_20.writeAction("movir X16 -1")
    spmv__init_sp_lane_20.writeAction("movir X19 717")
    spmv__init_sp_lane_20.writeAction("movir X17 1928")
    spmv__init_sp_lane_20.writeAction("add X7 X17 X17")
    spmv__init_sp_lane_20.writeAction("mov_imm2reg X18 0")
    spmv__init_sp_lane_20.writeAction("spmvMSREFA_okdhl_init_cache_loop: movwrl X16 X17(X18,1,1)")
    spmv__init_sp_lane_20.writeAction("blt X18 X19 spmvMSREFA_okdhl_init_cache_loop")
    spmv__init_sp_lane_20.writeAction("sendr_reply X0 X16 X28")
    spmv__init_sp_lane_20.writeAction("yield_terminate")

    ## spmv__init_global_master with ID 21
    spmv__init_global_master_21 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 21)
    spmv__init_global_master_21.writeAction("mul X27 X9 X24")
    spmv__init_global_master_21.writeAction("sri X27 X25 11")
    spmv__init_global_master_21.writeAction("movir X28 512")
    spmv__init_global_master_21.writeAction("bgt X25 X28 spmvMSREFA_okdhl_max_child_modular_eq_zero")
    spmv__init_global_master_21.writeAction("andi X27 X28 2047")
    spmv__init_global_master_21.writeAction("beqi X28 0 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__init_global_master_21.writeAction("addi X25 X25 1")
    spmv__init_global_master_21.writeAction("jmp spmvMSREFA_okdhl_modular_eq_zero")
    spmv__init_global_master_21.writeAction("spmvMSREFA_okdhl_max_child_modular_eq_zero: mov_imm2reg X25 512")
    spmv__init_global_master_21.writeAction("spmvMSREFA_okdhl_modular_eq_zero: mov_imm2reg X22 2048")
    spmv__init_global_master_21.writeAction("bge X27 X22 spmvMSREFA_okdhl_global_master_full_child")
    spmv__init_global_master_21.writeAction("addi X27 X22 0")
    spmv__init_global_master_21.writeAction("spmvMSREFA_okdhl_global_master_full_child: mul X22 X9 X20")
    spmv__init_global_master_21.writeAction("lshift X20 X18 4")
    spmv__init_global_master_21.writeAction("mov_reg2reg X0 X23")
    spmv__init_global_master_21.writeAction("movir X21 0")
    spmv__init_global_master_21.writeAction("evi X2 X30 255 4")
    spmv__init_global_master_21.writeAction("evlb X30 25")
    spmv__init_global_master_21.writeAction("spmvMSREFA_okdhl_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    spmv__init_global_master_21.writeAction("sendr3_wret X30 22             X16 X18 X27 X28")
    spmv__init_global_master_21.writeAction("add X22 X23 X23")
    spmv__init_global_master_21.writeAction("add X18 X16 X16 ")
    spmv__init_global_master_21.writeAction("addi X21 X21 1")
    spmv__init_global_master_21.writeAction("blt X21 X25 spmvMSREFA_okdhl_glb_master_loop")
    spmv__init_global_master_21.writeAction("mul X21 X20 X17")
    spmv__init_global_master_21.writeAction("mov_imm2reg X19 0")
    spmv__init_global_master_21.writeAction("yield")

    ## spmv__global_master with ID 22
    spmv__global_master_22 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 22)
    spmv__global_master_22.writeAction("add X8 X19 X19")
    spmv__global_master_22.writeAction("bge X17 X24 spmvMSREFA_okdhl_global_master_fin_fetch")
    spmv__global_master_22.writeAction("sendr3_wret X1 22             X16 X18 X27 X28")
    spmv__global_master_22.writeAction("add X20 X17 X17")
    spmv__global_master_22.writeAction("add X18 X16 X16 ")
    spmv__global_master_22.writeAction("yield")
    spmv__global_master_22.writeAction("spmvMSREFA_okdhl_global_master_fin_fetch: subi X21 X21 1")
    spmv__global_master_22.writeAction("addi X1 X30 0")
    spmv__global_master_22.writeAction("evlb X30 27")
    spmv__global_master_22.writeAction("sendr_wcont X30 X2 X16 X16")
    spmv__global_master_22.writeAction("beqi X21 0 spmvMSREFA_okdhl_global_master_fin_map")
    spmv__global_master_22.writeAction("yield")
    spmv__global_master_22.writeAction("spmvMSREFA_okdhl_global_master_fin_map: evii X30, 11 255 5")
    spmv__global_master_22.writeAction("movir X29 704")
    spmv__global_master_22.writeAction("add X7 X29 X29")
    spmv__global_master_22.writeAction("movrl X27 0(X29) 0 8")
    spmv__global_master_22.writeAction("movir X28 0")
    spmv__global_master_22.writeAction("evlb X28 58")
    spmv__global_master_22.writeAction("movrl X28 8(X29) 0 8")
    spmv__global_master_22.writeAction("movir X28 1")
    spmv__global_master_22.writeAction("movrl X28  16(X29) 0 8")
    spmv__global_master_22.writeAction("evii X28 59 255 5")
    spmv__global_master_22.writeAction("send_wcont X30 X28 X29 8")
    spmv__global_master_22.writeAction("bnei X19 0 spmvMSREFA_okdhl_global_master_init_sync")
    spmv__global_master_22.writeAction("movir X28 -1")
    spmv__global_master_22.writeAction("sri X28 X28 1")
    spmv__global_master_22.writeAction("sendr_wcont X31 X28 X27 X19")
    spmv__global_master_22.writeAction("print 'returning to user cont %lx' X31")
    spmv__global_master_22.writeAction("yieldt")
    spmv__global_master_22.writeAction("spmvMSREFA_okdhl_global_master_init_sync: evi X2 X30 255 4")
    spmv__global_master_22.writeAction("evlb X30 37")
    spmv__global_master_22.writeAction("addi X2 X28 0")
    spmv__global_master_22.writeAction("evlb X28 23")
    spmv__global_master_22.writeAction("sendr_wcont X30 X28 X27 X19")
    spmv__global_master_22.writeAction("yield")

    ## spmv__cache_flush with ID 23
    spmv__cache_flush_23 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 23)
    spmv__cache_flush_23.writeAction("movir X20 704")
    spmv__cache_flush_23.writeAction("add X20 X7 X20")
    spmv__cache_flush_23.writeAction("movrl X27 0(X20) 0 8")
    spmv__cache_flush_23.writeAction("movir X28 0")
    spmv__cache_flush_23.writeAction("evlb X28 49")
    spmv__cache_flush_23.writeAction("movrl X28 8(X20) 0 8")
    spmv__cache_flush_23.writeAction("evi X2 X30 255 4")
    spmv__cache_flush_23.writeAction("evlb X30 11")
    spmv__cache_flush_23.writeAction("send_wret X30 24 X20 8 X28")
    spmv__cache_flush_23.writeAction("yield")

    ## spmv__cache_flush_return with ID 24
    spmv__cache_flush_return_24 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 24)
    spmv__cache_flush_return_24.writeAction("movir X28 -1")
    spmv__cache_flush_return_24.writeAction("sri X28 X28 1")
    spmv__cache_flush_return_24.writeAction("sendr_wcont X31 X28 X19 X19")
    spmv__cache_flush_return_24.writeAction("yieldt")

    ## spmv__init_node_master with ID 25
    spmv__init_node_master_25 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 25)
    spmv__init_node_master_25.writeAction("movir X26 0")
    spmv__init_node_master_25.writeAction("mov_reg2reg X1 X31")
    spmv__init_node_master_25.writeAction("mov_reg2reg X8 X16")
    spmv__init_node_master_25.writeAction("mov_reg2reg X10 X27")
    spmv__init_node_master_25.writeAction("sri X27 X25 6")
    spmv__init_node_master_25.writeAction("movir X28 32")
    spmv__init_node_master_25.writeAction("bgt X25 X28 spmvMSREFA_okdhl_max_child_modular_eq_zero")
    spmv__init_node_master_25.writeAction("andi X27 X28 63")
    spmv__init_node_master_25.writeAction("beqi X28 0 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__init_node_master_25.writeAction("addi X25 X25 1")
    spmv__init_node_master_25.writeAction("jmp spmvMSREFA_okdhl_modular_eq_zero")
    spmv__init_node_master_25.writeAction("spmvMSREFA_okdhl_max_child_modular_eq_zero: mov_imm2reg X25 32")
    spmv__init_node_master_25.writeAction("spmvMSREFA_okdhl_modular_eq_zero: add X9 X16 X24")
    spmv__init_node_master_25.writeAction("mov_imm2reg X21 0")
    spmv__init_node_master_25.writeAction("mov_imm2reg X22 64")
    spmv__init_node_master_25.writeAction("bge X27 X22 spmvMSREFA_okdhl_node_master_full_child")
    spmv__init_node_master_25.writeAction("addi X27 X22 0")
    spmv__init_node_master_25.writeAction("spmvMSREFA_okdhl_node_master_full_child: div X9 X25 X18")
    spmv__init_node_master_25.writeAction("addi X0 X23 0")
    spmv__init_node_master_25.writeAction("evi X2 X30 255 4")
    spmv__init_node_master_25.writeAction("evlb X30 28")
    spmv__init_node_master_25.writeAction("spmvMSREFA_okdhl_node_master_loop: ev X30 X30 X23 X23 8")
    spmv__init_node_master_25.writeAction("sendr3_wret X30 26             X16 X18 X27 X28")
    spmv__init_node_master_25.writeAction("add X22 X23 X23")
    spmv__init_node_master_25.writeAction("add X18 X16 X16 ")
    spmv__init_node_master_25.writeAction("addi X21 X21 1")
    spmv__init_node_master_25.writeAction("addi X26 X26 1")
    spmv__init_node_master_25.writeAction("blt X21 X25 spmvMSREFA_okdhl_node_master_loop")
    spmv__init_node_master_25.writeAction("mov_imm2reg X19 0")
    spmv__init_node_master_25.writeAction("yield")

    ## spmv__node_master with ID 26
    spmv__node_master_26 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 26)
    spmv__node_master_26.writeAction("add X8 X19 X19")
    spmv__node_master_26.writeAction("bge X16 X24 spmvMSREFA_okdhl_node_master_fin_fetch")
    spmv__node_master_26.writeAction("sendr3_wret X1 26             X16 X18 X27 X28")
    spmv__node_master_26.writeAction("add X18 X16 X16 ")
    spmv__node_master_26.writeAction("yield")
    spmv__node_master_26.writeAction("spmvMSREFA_okdhl_node_master_fin_fetch: subi X21 X21 1")
    spmv__node_master_26.writeAction("addi X1 X30 0")
    spmv__node_master_26.writeAction("evlb X30 30")
    spmv__node_master_26.writeAction("sendr_wcont X30 X2 X16 X22")
    spmv__node_master_26.writeAction("beqi X21 0 spmvMSREFA_okdhl_node_master_fin_partition")
    spmv__node_master_26.writeAction("yield")
    spmv__node_master_26.writeAction("spmvMSREFA_okdhl_node_master_fin_partition: sendr_wret X31 25             X19 X19 X28")
    spmv__node_master_26.writeAction("mov_imm2reg X19 0")
    spmv__node_master_26.writeAction("yield")

    ## spmv__termiante_node_master with ID 27
    spmv__termiante_node_master_27 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 27)
    spmv__termiante_node_master_27.writeAction("yield_terminate")

    ## spmv__init_updown_master with ID 28
    spmv__init_updown_master_28 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 28)
    spmv__init_updown_master_28.writeAction("movir X26 0")
    spmv__init_updown_master_28.writeAction("mov_reg2reg X1 X31")
    spmv__init_updown_master_28.writeAction("mov_reg2reg X8 X16")
    spmv__init_updown_master_28.writeAction("mov_reg2reg X10 X27")
    spmv__init_updown_master_28.writeAction("movir X25 64")
    spmv__init_updown_master_28.writeAction("bgt X27 X25 spmvMSREFA_okdhl_modular_eq_zero")
    spmv__init_updown_master_28.writeAction("addi X27 X25 0")
    spmv__init_updown_master_28.writeAction("spmvMSREFA_okdhl_modular_eq_zero: add X9 X16 X24")
    spmv__init_updown_master_28.writeAction("mov_imm2reg X21 0")
    spmv__init_updown_master_28.writeAction("mov_imm2reg X18 16")
    spmv__init_updown_master_28.writeAction("movir X29 784")
    spmv__init_updown_master_28.writeAction("add X7 X29 X29")
    spmv__init_updown_master_28.writeAction("mul X25 X18 X28")
    spmv__init_updown_master_28.writeAction("add X16 X28 X28")
    spmv__init_updown_master_28.writeAction("movrl X28 0(X29) 0 8")
    spmv__init_updown_master_28.writeAction("movir X29 792")
    spmv__init_updown_master_28.writeAction("add X7 X29 X29")
    spmv__init_updown_master_28.writeAction("movrl X24 0(X29) 0 8")
    spmv__init_updown_master_28.writeAction("mov_reg2reg X0 X23")
    spmv__init_updown_master_28.writeAction("evi X2 X30 255 4")
    spmv__init_updown_master_28.writeAction("evlb X30 31")
    spmv__init_updown_master_28.writeAction("spmvMSREFA_okdhl_updown_master_loop: ev X30 X30 X23 X23 8")
    spmv__init_updown_master_28.writeAction("sendr3_wret X30 29                 X16 X18 X21 X28")
    spmv__init_updown_master_28.writeAction("addi X23 X23 1")
    spmv__init_updown_master_28.writeAction("add X18 X16 X16 ")
    spmv__init_updown_master_28.writeAction("addi X21 X21 1")
    spmv__init_updown_master_28.writeAction("addi X26 X26 1")
    spmv__init_updown_master_28.writeAction("blt X21 X25 spmvMSREFA_okdhl_updown_master_loop")
    spmv__init_updown_master_28.writeAction("mov_imm2reg X19 0")
    spmv__init_updown_master_28.writeAction("addi X21 X22 0")
    spmv__init_updown_master_28.writeAction("yield")

    ## spmv__updown_master with ID 29
    spmv__updown_master_29 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 29)
    spmv__updown_master_29.writeAction("add X8 X19 X19")
    spmv__updown_master_29.writeAction("bge X16 X24 spmvMSREFA_okdhl_updown_master_fin_fetch")
    spmv__updown_master_29.writeAction("addi X22 X22 1")
    spmv__updown_master_29.writeAction("add X18 X16 X16 ")
    spmv__updown_master_29.writeAction("yield")
    spmv__updown_master_29.writeAction("spmvMSREFA_okdhl_updown_master_fin_fetch: subi X21 X21 1")
    spmv__updown_master_29.writeAction("blei X21 0 spmvMSREFA_okdhl_updown_master_fin_partition")
    spmv__updown_master_29.writeAction("yield")
    spmv__updown_master_29.writeAction("spmvMSREFA_okdhl_updown_master_fin_partition: sendr_wret X31             28 X19 X19 X28")
    spmv__updown_master_29.writeAction("mov_imm2reg X19 0")
    spmv__updown_master_29.writeAction("yield")

    ## spmv__terminate_updown_master with ID 30
    spmv__terminate_updown_master_30 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 30)
    spmv__terminate_updown_master_30.writeAction("yield_terminate")

    ## spmv__lane_master_init with ID 31
    spmv__lane_master_init_31 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 31)
    spmv__lane_master_init_31.writeAction("addi X1 X31 0")
    spmv__lane_master_init_31.writeAction("send_dmlm_ld_wret X8 33 2 X28")
    spmv__lane_master_init_31.writeAction("movir X16 0")
    spmv__lane_master_init_31.writeAction("movir X17 32")
    spmv__lane_master_init_31.writeAction("mov_imm2reg X19 0")
    spmv__lane_master_init_31.writeAction("addi X7 X22 640")
    spmv__lane_master_init_31.writeAction("move X19 0(X22) 0 8")
    spmv__lane_master_init_31.writeAction("addi X2 X28 0")
    spmv__lane_master_init_31.writeAction("evlb X28 32")
    spmv__lane_master_init_31.writeAction("addi X7 X29 656")
    spmv__lane_master_init_31.writeAction("move X28 0(X29) 0 8")
    spmv__lane_master_init_31.writeAction("addi X2 X20 0")
    spmv__lane_master_init_31.writeAction("evlb X20 34")
    spmv__lane_master_init_31.writeAction("evi X2 X21 255 4")
    spmv__lane_master_init_31.writeAction("evlb X21 68")
    spmv__lane_master_init_31.writeAction("movir X25 0")
    spmv__lane_master_init_31.writeAction("movir X28 776")
    spmv__lane_master_init_31.writeAction("add X7 X28 X28")
    spmv__lane_master_init_31.writeAction("movrl X1 0(X28) 0 8")
    spmv__lane_master_init_31.writeAction("yield")

    ## spmv__lane_master_loop with ID 32
    spmv__lane_master_loop_32 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 32)
    spmv__lane_master_loop_32.writeAction("subi X16 X16 1")
    spmv__lane_master_loop_32.writeAction("beqi X23 1 spmvMSREFA_okdhl_lane_master_loop_continue")
    spmv__lane_master_loop_32.writeAction("bge X23 X24 spmvMSREFA_okdhl_lane_master_reach_end")
    spmv__lane_master_loop_32.writeAction("addi X23 X28 16")
    spmv__lane_master_loop_32.writeAction("sendr_wcont X20 X20 X28 X24")
    spmv__lane_master_loop_32.writeAction("send_dmlm_ld X23 X21 2")
    spmv__lane_master_loop_32.writeAction("addi X16 X16 1")
    spmv__lane_master_loop_32.writeAction("movir X23 1")
    spmv__lane_master_loop_32.writeAction("yield")
    spmv__lane_master_loop_32.writeAction("spmvMSREFA_okdhl_lane_master_reach_end: bgti X16 0 spmvMSREFA_okdhl_lane_master_loop_continue")
    spmv__lane_master_loop_32.writeAction("movlr 0(X22) X19 0 8")
    spmv__lane_master_loop_32.writeAction("sendr_wret X31 31 X19 X19 X28")
    spmv__lane_master_loop_32.writeAction("mov_imm2reg X19 0")
    spmv__lane_master_loop_32.writeAction("movrl X19 0(X22) 0 8")
    spmv__lane_master_loop_32.writeAction("addi X2 X30 0")
    spmv__lane_master_loop_32.writeAction("evlb X30 36")
    spmv__lane_master_loop_32.writeAction("sendr_wcont X30 X2 X28 X28")
    spmv__lane_master_loop_32.writeAction("spmvMSREFA_okdhl_lane_master_loop_continue: yield")

    ## spmv__lane_master_read_partition with ID 33
    spmv__lane_master_read_partition_33 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 33)
    spmv__lane_master_read_partition_33.writeAction("bge X8 X9 spmvMSREFA_okdhl_lane_master_empty_partition")
    spmv__lane_master_read_partition_33.writeAction("addi X8 X28 16")
    spmv__lane_master_read_partition_33.writeAction("sendr_wcont X20 X20 X28 X9")
    spmv__lane_master_read_partition_33.writeAction("send_dmlm_ld X8 X21 2")
    spmv__lane_master_read_partition_33.writeAction("addi X16 X16 1")
    spmv__lane_master_read_partition_33.writeAction("movir X23 1")
    spmv__lane_master_read_partition_33.writeAction("yield")
    spmv__lane_master_read_partition_33.writeAction("spmvMSREFA_okdhl_lane_master_empty_partition: addi X2 X30 0")
    spmv__lane_master_read_partition_33.writeAction("evlb X30 36")
    spmv__lane_master_read_partition_33.writeAction("sendr_wcont X30 X2 X28 X28")
    spmv__lane_master_read_partition_33.writeAction("spmvMSREFA_okdhl_empty_part_ret_to_ud_mstr: sendr_wret X31 31 X19 X19 X28")
    spmv__lane_master_read_partition_33.writeAction("yield")

    ## spmv__lane_master_get_next_return with ID 34
    spmv__lane_master_get_next_return_34 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 34)
    spmv__lane_master_get_next_return_34.writeAction("bge X16 X17 spmvMSREFA_okdhl_lane_master_break_iterate_loop")
    spmv__lane_master_get_next_return_34.writeAction("bge X8 X9 spmvMSREFA_okdhl_lane_master_break_iterate_loop")
    spmv__lane_master_get_next_return_34.writeAction("addi X8 X28 16")
    spmv__lane_master_get_next_return_34.writeAction("sendr_wcont X20 X20 X28 X9")
    spmv__lane_master_get_next_return_34.writeAction("send_dmlm_ld X8 X21 2")
    spmv__lane_master_get_next_return_34.writeAction("addi X16 X16 1")
    spmv__lane_master_get_next_return_34.writeAction("yield")
    spmv__lane_master_get_next_return_34.writeAction("spmvMSREFA_okdhl_lane_master_break_iterate_loop: movir X23 0")
    spmv__lane_master_get_next_return_34.writeAction("addi X8 X23 0")
    spmv__lane_master_get_next_return_34.writeAction("addi X9 X24 0")
    spmv__lane_master_get_next_return_34.writeAction("yield")
    spmv__lane_master_get_next_return_34.writeAction("spmvMSREFA_okdhl_lane_master_iterator_pass_end: subi X16 X16 1")
    spmv__lane_master_get_next_return_34.writeAction("addi X8 X23 0")
    spmv__lane_master_get_next_return_34.writeAction("addi X9 X24 0")
    spmv__lane_master_get_next_return_34.writeAction("bgti X16 0 spmvMSREFA_okdhl_lane_master_loop_continue")
    spmv__lane_master_get_next_return_34.writeAction("movlr 0(X22) X19 0 8")
    spmv__lane_master_get_next_return_34.writeAction("sendr_wret X31 31 X19 X19 X28")
    spmv__lane_master_get_next_return_34.writeAction("addi X2 X30 0")
    spmv__lane_master_get_next_return_34.writeAction("evlb X30 36")
    spmv__lane_master_get_next_return_34.writeAction("sendr_wcont X30 X2 X28 X28")
    spmv__lane_master_get_next_return_34.writeAction("spmvMSREFA_okdhl_lane_master_loop_continue: yield")

    ## spmv__lane_master_terminate with ID 35
    spmv__lane_master_terminate_35 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 35)
    spmv__lane_master_terminate_35.writeAction("yield_terminate")

    ## spmv__lane_master_launch_worker with ID 36
    spmv__lane_master_launch_worker_36 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 36)
    spmv__lane_master_launch_worker_36.writeAction("spmvMSREFA_okdhl_prepare_launch_workers: evii X30 51 255 5")
    spmv__lane_master_launch_worker_36.writeAction("movir X28 -5")
    spmv__lane_master_launch_worker_36.writeAction("spmvMSREFA_okdhl_launch_workers: bgei X25 1 spmvMSREFA_okdhl_lane_master_loop_continue")
    spmv__lane_master_launch_worker_36.writeAction("sendr_wret X30 32 X28 X28 X29")
    spmv__lane_master_launch_worker_36.writeAction("addi X25 X25 1")
    spmv__lane_master_launch_worker_36.writeAction("jmp spmvMSREFA_okdhl_launch_workers")
    spmv__lane_master_launch_worker_36.writeAction("spmvMSREFA_okdhl_lane_master_loop_continue: yieldt")

    ## spmv__init_global_snyc with ID 37
    spmv__init_global_snyc_37 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 37)
    spmv__init_global_snyc_37.writeAction("sri X8 X16 11")
    spmv__init_global_snyc_37.writeAction("movir X28 512")
    spmv__init_global_snyc_37.writeAction("bgt X16 X28 spmvMSREFA_okdhl_max_child_max_node")
    spmv__init_global_snyc_37.writeAction("andi X8 X28 2047")
    spmv__init_global_snyc_37.writeAction("beqi X28 0 spmvMSREFA_okdhl_max_node")
    spmv__init_global_snyc_37.writeAction("addi X16 X16 1")
    spmv__init_global_snyc_37.writeAction("jmp spmvMSREFA_okdhl_max_node")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_max_child_max_node: mov_imm2reg X16 512")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_max_node: addi X16 X16 0")
    spmv__init_global_snyc_37.writeAction("sri X8 X17 6")
    spmv__init_global_snyc_37.writeAction("movir X28 32")
    spmv__init_global_snyc_37.writeAction("bgt X17 X28 spmvMSREFA_okdhl_max_child_max_ud_per_nd")
    spmv__init_global_snyc_37.writeAction("andi X8 X28 63")
    spmv__init_global_snyc_37.writeAction("beqi X28 0 spmvMSREFA_okdhl_max_ud_per_nd")
    spmv__init_global_snyc_37.writeAction("addi X17 X17 1")
    spmv__init_global_snyc_37.writeAction("jmp spmvMSREFA_okdhl_max_ud_per_nd")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_max_ud_per_nd: addi X17 X17 0")
    spmv__init_global_snyc_37.writeAction("movir X18 64")
    spmv__init_global_snyc_37.writeAction("bgt X8 X18 spmvMSREFA_okdhl_max_ln_per_ud")
    spmv__init_global_snyc_37.writeAction("addi X8 X18 0")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_max_ln_per_ud: addi X18 X18 0")
    spmv__init_global_snyc_37.writeAction("mov_reg2reg X1 X19")
    spmv__init_global_snyc_37.writeAction("mov_reg2reg X9 X21")
    spmv__init_global_snyc_37.writeAction("evi X2 X30 255 4")
    spmv__init_global_snyc_37.writeAction("evlb X30 38")
    spmv__init_global_snyc_37.writeAction("mov_imm2reg X29 0")
    spmv__init_global_snyc_37.writeAction("spmvMSREFA_okdhl_broadcast_loop: lshift X29 X28 11")
    spmv__init_global_snyc_37.writeAction("add X0 X28 X28")
    spmv__init_global_snyc_37.writeAction("ev X30 X30 X28 X28 8")
    spmv__init_global_snyc_37.writeAction("sendr_wret X30 40 X17 X18  X28")
    spmv__init_global_snyc_37.writeAction("addi X29 X29 1")
    spmv__init_global_snyc_37.writeAction("blt X29 X16 spmvMSREFA_okdhl_broadcast_loop")
    spmv__init_global_snyc_37.writeAction("mov_imm2reg X20 0")
    spmv__init_global_snyc_37.writeAction("mov_imm2reg X22 0")
    spmv__init_global_snyc_37.writeAction("yield")

    ## spmv__init_node_sync with ID 38
    spmv__init_node_sync_38 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 38)
    spmv__init_node_sync_38.writeAction("mov_reg2reg X8 X17")
    spmv__init_node_sync_38.writeAction("evi X2 X30 255 4")
    spmv__init_node_sync_38.writeAction("evlb X30 39")
    spmv__init_node_sync_38.writeAction("mov_imm2reg X29 0")
    spmv__init_node_sync_38.writeAction("spmvMSREFA_okdhl_broadcast_loop: lshift X29 X28 6")
    spmv__init_node_sync_38.writeAction("add X0 X28 X28")
    spmv__init_node_sync_38.writeAction("ev X30 X30 X28 X28 8")
    spmv__init_node_sync_38.writeAction("sendr_wret X30 41 X9 EQT  X28")
    spmv__init_node_sync_38.writeAction("addi X29 X29 1")
    spmv__init_node_sync_38.writeAction("blt X29 X17 spmvMSREFA_okdhl_broadcast_loop")
    spmv__init_node_sync_38.writeAction("mov_imm2reg X20 0")
    spmv__init_node_sync_38.writeAction("mov_imm2reg X22 0")
    spmv__init_node_sync_38.writeAction("mov_reg2reg X1 X19")
    spmv__init_node_sync_38.writeAction("yield")

    ## spmv__ud_accumulate with ID 39
    spmv__ud_accumulate_39 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 39)
    spmv__ud_accumulate_39.writeAction("mov_imm2reg X20 0")
    spmv__ud_accumulate_39.writeAction("mov_imm2reg X22 0")
    spmv__ud_accumulate_39.writeAction("spmvMSREFA_okdhl_accumulate_loop: lshift X20 X17 16")
    spmv__ud_accumulate_39.writeAction("add X7 X17 X17")
    spmv__ud_accumulate_39.writeAction("addi X17 X17 648")
    spmv__ud_accumulate_39.writeAction("move 0(X17) X28 0 8")
    spmv__ud_accumulate_39.writeAction("add X28 X22 X22")
    spmv__ud_accumulate_39.writeAction("addi X20 X20 1")
    spmv__ud_accumulate_39.writeAction("blt X20 X8 spmvMSREFA_okdhl_accumulate_loop")
    spmv__ud_accumulate_39.writeAction("sendr_reply X22 X22 X28")
    spmv__ud_accumulate_39.writeAction("yield_terminate")

    ## spmv__global_sync_return with ID 40
    spmv__global_sync_return_40 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 40)
    spmv__global_sync_return_40.writeAction("addi X20 X20 1")
    spmv__global_sync_return_40.writeAction("add X8 X22 X22")
    spmv__global_sync_return_40.writeAction("blt X20 X16 spmvMSREFA_okdhl_continue")
    spmv__global_sync_return_40.writeAction("bge X22 X21 spmvMSREFA_okdhl_sync_finish")
    spmv__global_sync_return_40.writeAction("mov_imm2reg X29 0")
    spmv__global_sync_return_40.writeAction("spmvMSREFA_okdhl_broadcast_loop: lshift X29 X28 11")
    spmv__global_sync_return_40.writeAction("add X0 X28 X28")
    spmv__global_sync_return_40.writeAction("ev X30 X30 X28 X28 8")
    spmv__global_sync_return_40.writeAction("sendr_wret X30 40 X17 X18  X28")
    spmv__global_sync_return_40.writeAction("addi X29 X29 1")
    spmv__global_sync_return_40.writeAction("blt X29 X16 spmvMSREFA_okdhl_broadcast_loop")
    spmv__global_sync_return_40.writeAction("mov_imm2reg X20 0")
    spmv__global_sync_return_40.writeAction("mov_imm2reg X22 0")
    spmv__global_sync_return_40.writeAction("spmvMSREFA_okdhl_continue: yield")
    spmv__global_sync_return_40.writeAction("spmvMSREFA_okdhl_sync_finish: movir X30 -1")
    spmv__global_sync_return_40.writeAction("sri X30 X30 1")
    spmv__global_sync_return_40.writeAction("sendr_wcont X19 X30 X22 X22")
    spmv__global_sync_return_40.writeAction("yield_terminate")

    ## spmv__node_sync_return with ID 41
    spmv__node_sync_return_41 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 41)
    spmv__node_sync_return_41.writeAction("addi X20 X20 1")
    spmv__node_sync_return_41.writeAction("add X8 X22 X22")
    spmv__node_sync_return_41.writeAction("blt X20 X17 spmvMSREFA_okdhl_continue")
    spmv__node_sync_return_41.writeAction("sendr_wcont X19 EQT X22 X22")
    spmv__node_sync_return_41.writeAction("yield_terminate")
    spmv__node_sync_return_41.writeAction("spmvMSREFA_okdhl_continue: yield")

    ## spmv__kv_map_emit with ID 42
    spmv__kv_map_emit_42 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 42)
    spmv__kv_map_emit_42.writeAction("addi X7 X25 640")
    spmv__kv_map_emit_42.writeAction("movlr 40(X25) X23 0 8")
    spmv__kv_map_emit_42.writeAction("movlr 56(X25) X26 0 8")
    spmv__kv_map_emit_42.writeAction("movir X24 0")
    spmv__kv_map_emit_42.writeAction("hash X8 X24")
    spmv__kv_map_emit_42.writeAction("and X24 X23 X24")
    spmv__kv_map_emit_42.writeAction("add X24 X26 X24")
    spmv__kv_map_emit_42.writeAction("evi X2 X30 255 4")
    spmv__kv_map_emit_42.writeAction("evlb X30 45")
    spmv__kv_map_emit_42.writeAction("evi X2 X27 255 4")
    spmv__kv_map_emit_42.writeAction("evlb X27 48")
    spmv__kv_map_emit_42.writeAction("ev X30  X30  X24 X24 8")
    spmv__kv_map_emit_42.writeAction("sendops_wcont X30 X27 X8 2")
    spmv__kv_map_emit_42.writeAction("move 0(X25) X29  0 8")
    spmv__kv_map_emit_42.writeAction("addi X29 X29 1")
    spmv__kv_map_emit_42.writeAction("move X29 0(X25) 0 8")
    spmv__kv_map_emit_42.writeAction("yield_terminate")

    ## spmv__kv_reduce_emit with ID 43
    spmv__kv_reduce_emit_43 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 43)
    spmv__kv_reduce_emit_43.writeAction("movir X16 704")
    spmv__kv_reduce_emit_43.writeAction("add X16 X7 X16")
    spmv__kv_reduce_emit_43.writeAction("movir X29 864")
    spmv__kv_reduce_emit_43.writeAction("add X7 X29 X29")
    spmv__kv_reduce_emit_43.writeAction("movlr 0(X29) X28 0 8")
    spmv__kv_reduce_emit_43.writeAction("lshift X8 X29 3")
    spmv__kv_reduce_emit_43.writeAction("add X29 X28 X28")
    spmv__kv_reduce_emit_43.writeAction("subi X16 X16 8")
    spmv__kv_reduce_emit_43.writeAction("send_dmlm X28 X1 X16 1")
    spmv__kv_reduce_emit_43.writeAction("yieldt")

    ## spmv__kv_map_return with ID 44
    spmv__kv_map_return_44 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 44)
    spmv__kv_map_return_44.writeAction("addi X7 X16 656")
    spmv__kv_map_return_44.writeAction("move 0(X16) X29 0 8")
    spmv__kv_map_return_44.writeAction("sendops_wcont X29 X2 X8 2")
    spmv__kv_map_return_44.writeAction("yieldt")

    ## spmv__init_reduce_thread with ID 45
    spmv__init_reduce_thread_45 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 45)
    spmv__init_reduce_thread_45.writeAction("movir X21 717")
    spmv__init_reduce_thread_45.writeAction("mod X8 X21 X21")
    spmv__init_reduce_thread_45.writeAction("sli X21 X16 4")
    spmv__init_reduce_thread_45.writeAction("add X7 X16 X16")
    spmv__init_reduce_thread_45.writeAction("addi X16 X16 1928")
    spmv__init_reduce_thread_45.writeAction("movlr 0(X16) X17 0 8")
    spmv__init_reduce_thread_45.writeAction("beq X17 X8 spmvMSREFA_okdhl_cache_hit")
    spmv__init_reduce_thread_45.writeAction("movir X21 1")
    spmv__init_reduce_thread_45.writeAction("sli X21 X21 63")
    spmv__init_reduce_thread_45.writeAction("or X21 X8 X25")
    spmv__init_reduce_thread_45.writeAction("beq X25 X17 spmvMSREFA_okdhl_cache_hit")
    spmv__init_reduce_thread_45.writeAction("rshift X17 X24 63")
    spmv__init_reduce_thread_45.writeAction("beqi X24 1 spmvMSREFA_okdhl_cache_evict")
    spmv__init_reduce_thread_45.writeAction("beqi X17 -1 spmvMSREFA_okdhl_cache_evict")
    spmv__init_reduce_thread_45.writeAction("evi X2 X24 255 4")
    spmv__init_reduce_thread_45.writeAction("sendops_wcont X24 X1 X8 2")
    spmv__init_reduce_thread_45.writeAction("yieldt")
    spmv__init_reduce_thread_45.writeAction("spmvMSREFA_okdhl_cache_hit: move 8(X16) X22 0 8")
    spmv__init_reduce_thread_45.writeAction("fadd.64 X9 X22 X22")
    spmv__init_reduce_thread_45.writeAction("movrl X22 8(X16) 0 8")
    spmv__init_reduce_thread_45.writeAction("sendr_wcont X1 X2 X8 X17 ")
    spmv__init_reduce_thread_45.writeAction("addi X7 X18 640")
    spmv__init_reduce_thread_45.writeAction("move 8(X18) X24 0 8")
    spmv__init_reduce_thread_45.writeAction("addi X24 X24 1")
    spmv__init_reduce_thread_45.writeAction("move X24 8(X18) 0 8")
    spmv__init_reduce_thread_45.writeAction("yieldt")
    spmv__init_reduce_thread_45.writeAction("spmvMSREFA_okdhl_cache_evict: addi X7 X18 640")
    spmv__init_reduce_thread_45.writeAction("move 24(X18) X24 0 8")
    spmv__init_reduce_thread_45.writeAction("move 32(X18) X25 0 8")
    spmv__init_reduce_thread_45.writeAction("bgt X25 X24 spmvMSREFA_okdhl_thread_available")
    spmv__init_reduce_thread_45.writeAction("evi X2 X24 255 4")
    spmv__init_reduce_thread_45.writeAction("sendops_wcont X24 X1 X8 2")
    spmv__init_reduce_thread_45.writeAction("yieldt")
    spmv__init_reduce_thread_45.writeAction("spmvMSREFA_okdhl_thread_available: addi X24 X24 1")
    spmv__init_reduce_thread_45.writeAction("move X24  24(X18) 0 8")
    spmv__init_reduce_thread_45.writeAction("movrl X8 0(X16) 1 8")
    spmv__init_reduce_thread_45.writeAction("movir X19 0")
    spmv__init_reduce_thread_45.writeAction("beqi X17 -1 spmvMSREFA_okdhl_skip_flush")
    spmv__init_reduce_thread_45.writeAction("sub X17 X21 X17")
    spmv__init_reduce_thread_45.writeAction("addi X16 X22 0")
    spmv__init_reduce_thread_45.writeAction("addi X7 X18 704")
    spmv__init_reduce_thread_45.writeAction("addi X2 X21 0")
    spmv__init_reduce_thread_45.writeAction("evlb X21 47")
    spmv__init_reduce_thread_45.writeAction("movir X25 864")
    spmv__init_reduce_thread_45.writeAction("add X7 X25 X25")
    spmv__init_reduce_thread_45.writeAction("movlr 0(X25) X24 0 8")
    spmv__init_reduce_thread_45.writeAction("lshift X17 X25 3")
    spmv__init_reduce_thread_45.writeAction("add X25 X24 X24")
    spmv__init_reduce_thread_45.writeAction("send_dmlm X24 X21 X22 1")
    spmv__init_reduce_thread_45.writeAction("addi X22 X22 8")
    spmv__init_reduce_thread_45.writeAction("addi X19 X19 1")
    spmv__init_reduce_thread_45.writeAction("spmvMSREFA_okdhl_skip_flush: addi X2 X21 0")
    spmv__init_reduce_thread_45.writeAction("evlb X21 46")
    spmv__init_reduce_thread_45.writeAction("movir X25 864")
    spmv__init_reduce_thread_45.writeAction("add X7 X25 X25")
    spmv__init_reduce_thread_45.writeAction("movlr 0(X25) X24 0 8")
    spmv__init_reduce_thread_45.writeAction("lshift X8 X25 3")
    spmv__init_reduce_thread_45.writeAction("add X25 X24 X24")
    spmv__init_reduce_thread_45.writeAction("send_dmlm_ld X24 X21 1")
    spmv__init_reduce_thread_45.writeAction("move X9 0(X16) 0 8")
    spmv__init_reduce_thread_45.writeAction("addi X8 X17 0")
    spmv__init_reduce_thread_45.writeAction("addi X1 X20 0")
    spmv__init_reduce_thread_45.writeAction("addi X19 X19 1")
    spmv__init_reduce_thread_45.writeAction("yield")

    ## spmv__combine_get_pair with ID 46
    spmv__combine_get_pair_46 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 46)
    spmv__combine_get_pair_46.writeAction("move 0(X16) X22 0 8")
    spmv__combine_get_pair_46.writeAction("fadd.64 X22 X8 X22")
    spmv__combine_get_pair_46.writeAction("move X22 0(X16) 0 8")
    spmv__combine_get_pair_46.writeAction("spmvMSREFA_okdhl_get_fail: subi X19 X19 1")
    spmv__combine_get_pair_46.writeAction("bnei X19 0 spmvMSREFA_okdhl_contiue")
    spmv__combine_get_pair_46.writeAction("movir X21 1")
    spmv__combine_get_pair_46.writeAction("sli X21 X21 63")
    spmv__combine_get_pair_46.writeAction("or X21 X17 X17")
    spmv__combine_get_pair_46.writeAction("movrl X17 -8(X16) 0 8")
    spmv__combine_get_pair_46.writeAction("sendr_wcont X20 X2 X2 X17 ")
    spmv__combine_get_pair_46.writeAction("addi X7 X18 640")
    spmv__combine_get_pair_46.writeAction("move 24(X18) X24  0 8")
    spmv__combine_get_pair_46.writeAction("subi X24 X24 1")
    spmv__combine_get_pair_46.writeAction("move X24  24(X18) 0 8")
    spmv__combine_get_pair_46.writeAction("move 8(X18) X24 0 8")
    spmv__combine_get_pair_46.writeAction("addi X24 X24 1")
    spmv__combine_get_pair_46.writeAction("move X24 8(X18) 0 8")
    spmv__combine_get_pair_46.writeAction("yieldt")
    spmv__combine_get_pair_46.writeAction("spmvMSREFA_okdhl_contiue: yield")

    ## spmv__combine_put_pair_ack with ID 47
    spmv__combine_put_pair_ack_47 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 47)
    spmv__combine_put_pair_ack_47.writeAction("subi X19 X19 1")
    spmv__combine_put_pair_ack_47.writeAction("bnei X19 0 spmvMSREFA_okdhl_contiue")
    spmv__combine_put_pair_ack_47.writeAction("movir X21 1")
    spmv__combine_put_pair_ack_47.writeAction("sli X21 X21 63")
    spmv__combine_put_pair_ack_47.writeAction("or X21 X17 X17")
    spmv__combine_put_pair_ack_47.writeAction("movrl X17 -8(X16) 0 8")
    spmv__combine_put_pair_ack_47.writeAction("sendr_wcont X20 X2 X2 X17 ")
    spmv__combine_put_pair_ack_47.writeAction("addi X7 X18 640")
    spmv__combine_put_pair_ack_47.writeAction("move 24(X18) X24  0 8")
    spmv__combine_put_pair_ack_47.writeAction("subi X24 X24 1")
    spmv__combine_put_pair_ack_47.writeAction("move X24  24(X18) 0 8")
    spmv__combine_put_pair_ack_47.writeAction("move 8(X18) X24 0 8")
    spmv__combine_put_pair_ack_47.writeAction("addi X24 X24 1")
    spmv__combine_put_pair_ack_47.writeAction("move X24 8(X18) 0 8")
    spmv__combine_put_pair_ack_47.writeAction("yieldt")
    spmv__combine_put_pair_ack_47.writeAction("spmvMSREFA_okdhl_contiue: yield")

    ## spmv__kv_reduce_return with ID 48
    spmv__kv_reduce_return_48 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 48)
    spmv__kv_reduce_return_48.writeAction("yieldt")

    ## spmv__combine_flush_lane with ID 49
    spmv__combine_flush_lane_49 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 49)
    spmv__combine_flush_lane_49.writeAction("addi X1 X17 0")
    spmv__combine_flush_lane_49.writeAction("addi X7 X20 1928")
    spmv__combine_flush_lane_49.writeAction("movir X16 717")
    spmv__combine_flush_lane_49.writeAction("sli X16 X16 4")
    spmv__combine_flush_lane_49.writeAction("add X16 X20 X16")
    spmv__combine_flush_lane_49.writeAction("movir X19 0")
    spmv__combine_flush_lane_49.writeAction("movir X22 -1")
    spmv__combine_flush_lane_49.writeAction("addi X2 X23 0")
    spmv__combine_flush_lane_49.writeAction("evlb X23 50")
    spmv__combine_flush_lane_49.writeAction("addi X7 X18 704")
    spmv__combine_flush_lane_49.writeAction("spmvMSREFA_okdhl_flush_loop: bge X20 X16 spmvMSREFA_okdhl_break_flush_loop")
    spmv__combine_flush_lane_49.writeAction("movlr 0(X20) X21 0 8")
    spmv__combine_flush_lane_49.writeAction("beq X21 X22 spmvMSREFA_okdhl_continue_flush_loop")
    spmv__combine_flush_lane_49.writeAction("sli X21 X21 1")
    spmv__combine_flush_lane_49.writeAction("sri X21 X21 1")
    spmv__combine_flush_lane_49.writeAction("addi X20 X20 8")
    spmv__combine_flush_lane_49.writeAction("movir X25 864")
    spmv__combine_flush_lane_49.writeAction("add X7 X25 X25")
    spmv__combine_flush_lane_49.writeAction("movlr 0(X25) X24 0 8")
    spmv__combine_flush_lane_49.writeAction("lshift X21 X25 3")
    spmv__combine_flush_lane_49.writeAction("add X25 X24 X24")
    spmv__combine_flush_lane_49.writeAction("send_dmlm X24 X23 X20 1")
    spmv__combine_flush_lane_49.writeAction("addi X20 X20 8")
    spmv__combine_flush_lane_49.writeAction("addi X19 X19 1")
    spmv__combine_flush_lane_49.writeAction("jmp spmvMSREFA_okdhl_flush_loop")
    spmv__combine_flush_lane_49.writeAction("spmvMSREFA_okdhl_continue_flush_loop: addi X20 X20 16")
    spmv__combine_flush_lane_49.writeAction("jmp spmvMSREFA_okdhl_flush_loop")
    spmv__combine_flush_lane_49.writeAction("spmvMSREFA_okdhl_break_flush_loop: beqi X19 0 spmvMSREFA_okdhl_empty_cache")
    spmv__combine_flush_lane_49.writeAction("yield")
    spmv__combine_flush_lane_49.writeAction("spmvMSREFA_okdhl_empty_cache: movir X21 -1")
    spmv__combine_flush_lane_49.writeAction("sri X21 X21 1")
    spmv__combine_flush_lane_49.writeAction("sendr_wcont X17 X21 X2 X16 ")
    spmv__combine_flush_lane_49.writeAction("yieldt")

    ## spmv__combine_flush_ack with ID 50
    spmv__combine_flush_ack_50 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 50)
    spmv__combine_flush_ack_50.writeAction("subi X19 X19 1")
    spmv__combine_flush_ack_50.writeAction("bnei X19 0 spmvMSREFA_okdhl_continue_flush_loop")
    spmv__combine_flush_ack_50.writeAction("movir X21 -1")
    spmv__combine_flush_ack_50.writeAction("sri X21 X21 1")
    spmv__combine_flush_ack_50.writeAction("sendr_wcont X17 X21 X2 X16 ")
    spmv__combine_flush_ack_50.writeAction("yieldt")
    spmv__combine_flush_ack_50.writeAction("spmvMSREFA_okdhl_continue_flush_loop: yield")

    ## spmv__worker_init with ID 51
    spmv__worker_init_51 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 51)
    spmv__worker_init_51.writeAction("addi X1 X31 0")
    spmv__worker_init_51.writeAction("movir UDPR_5 -1")
    spmv__worker_init_51.writeAction("movir UDPR_0 0")
    spmv__worker_init_51.writeAction("addi X0 UDPR_6 0")
    spmv__worker_init_51.writeAction("andi X0 X28 63")
    spmv__worker_init_51.writeAction("sli X28 X28 16")
    spmv__worker_init_51.writeAction("sub X7 X28 UDPR_3")
    spmv__worker_init_51.writeAction("movir UDPR_7 792")
    spmv__worker_init_51.writeAction("add UDPR_7 UDPR_3 UDPR_7")
    spmv__worker_init_51.writeAction("movlr 0(UDPR_7) UDPR_2 0 8")
    spmv__worker_init_51.writeAction("addi X2 X30 0")
    spmv__worker_init_51.writeAction("evlb X30 52")
    spmv__worker_init_51.writeAction("movir X28 -6")
    spmv__worker_init_51.writeAction("sendr_wcont X30 X2 X28 X28")
    spmv__worker_init_51.writeAction("yield")

    ## spmv__worker_work with ID 52
    spmv__worker_work_52 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 52)
    spmv__worker_work_52.writeAction("spmvMSREFA_okdhl_claim_work: bgei UDPR_5 0 spmvMSREFA_okdhl_claim_remote_work")
    spmv__worker_work_52.writeAction("addi X2 X30 0")
    spmv__worker_work_52.writeAction("evlb X30 53")
    spmv__worker_work_52.writeAction("sendr_wcont X30 X2 X8 X9")
    spmv__worker_work_52.writeAction("yield")
    spmv__worker_work_52.writeAction("spmvMSREFA_okdhl_claim_remote_work: addi X2 X30 0")
    spmv__worker_work_52.writeAction("evlb X30 54")
    spmv__worker_work_52.writeAction("sendr_wcont X30 X2 X8 X9")
    spmv__worker_work_52.writeAction("yield")

    ## spmv__worker_claim_local with ID 53
    spmv__worker_claim_local_53 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 53)
    spmv__worker_claim_local_53.writeAction("movir UDPR_7 784")
    spmv__worker_claim_local_53.writeAction("add UDPR_3 UDPR_7 UDPR_7")
    spmv__worker_claim_local_53.writeAction("spmvMSREFA_okdhl_claiming_local_maps: movlr 0(UDPR_7) X28 0 8")
    spmv__worker_claim_local_53.writeAction("beq X28 UDPR_2 spmvMSREFA_okdhl_local_maps_finished")
    spmv__worker_claim_local_53.writeAction("addi X28 X29 16")
    spmv__worker_claim_local_53.writeAction("cswp UDPR_7 UDPR_8 X28 X29")
    spmv__worker_claim_local_53.writeAction("beq X28 UDPR_8 spmvMSREFA_okdhl_claimed_local_maps")
    spmv__worker_claim_local_53.writeAction("jmp spmvMSREFA_okdhl_claiming_local_maps")
    spmv__worker_claim_local_53.writeAction("spmvMSREFA_okdhl_claimed_local_maps: evii X30 60 255 5")
    spmv__worker_claim_local_53.writeAction("movir UDPR_7 776")
    spmv__worker_claim_local_53.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__worker_claim_local_53.writeAction("movlr 0(UDPR_7) X29 0 8")
    spmv__worker_claim_local_53.writeAction("sendr_wcont X30 X2 X28 X29")
    spmv__worker_claim_local_53.writeAction("yield")
    spmv__worker_claim_local_53.writeAction("spmvMSREFA_okdhl_local_maps_finished: movir UDPR_5 0")
    spmv__worker_claim_local_53.writeAction("spmvMSREFA_okdhl_claim_remote_work: addi X2 X30 0")
    spmv__worker_claim_local_53.writeAction("evlb X30 54")
    spmv__worker_claim_local_53.writeAction("sendr_wcont X30 X2 X28 X28")
    spmv__worker_claim_local_53.writeAction("spmvMSREFA_okdhl_claiming_finished: yield")

    ## spmv__worker_claim_remote with ID 54
    spmv__worker_claim_remote_54 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 54)
    spmv__worker_claim_remote_54.writeAction("spmvMSREFA_okdhl_claim_work: movir UDPR_7 768")
    spmv__worker_claim_remote_54.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__worker_claim_remote_54.writeAction("movlr 0(UDPR_7) X28 0 8")
    spmv__worker_claim_remote_54.writeAction("beqi X28 1 spmvMSREFA_okdhl_worker_finished")
    spmv__worker_claim_remote_54.writeAction("beqi UDPR_0 1 spmvMSREFA_okdhl_send_claim_msg")
    spmv__worker_claim_remote_54.writeAction("movir UDPR_7 640")
    spmv__worker_claim_remote_54.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__worker_claim_remote_54.writeAction("movlr 56(UDPR_7) UDPR_11 0 8")
    spmv__worker_claim_remote_54.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("addi UDPR_6 UDPR_6 64")
    spmv__worker_claim_remote_54.writeAction("movlr 40(UDPR_7) X29 0 8")
    spmv__worker_claim_remote_54.writeAction("addi X29 X29 1")
    spmv__worker_claim_remote_54.writeAction("mod UDPR_6 X29 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("bne X0 UDPR_6 spmvMSREFA_okdhl_send_claim_msg")
    spmv__worker_claim_remote_54.writeAction("bgei UDPR_5 3 spmvMSREFA_okdhl_worker_finished")
    spmv__worker_claim_remote_54.writeAction("bgei UDPR_5 2 spmvMSREFA_okdhl_early_finished")
    spmv__worker_claim_remote_54.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("addi UDPR_6 UDPR_6 64")
    spmv__worker_claim_remote_54.writeAction("mod UDPR_6 X29 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    spmv__worker_claim_remote_54.writeAction("spmvMSREFA_okdhl_send_claim_msg: movir UDPR_0 0")
    spmv__worker_claim_remote_54.writeAction("evii X30 57 255 5")
    spmv__worker_claim_remote_54.writeAction("ev X30 X30 UDPR_6 UDPR_6 8")
    spmv__worker_claim_remote_54.writeAction("movir X28 1")
    spmv__worker_claim_remote_54.writeAction("sli X28 X28 59")
    spmv__worker_claim_remote_54.writeAction("or X28 X30 X30")
    spmv__worker_claim_remote_54.writeAction("movir X29 1")
    spmv__worker_claim_remote_54.writeAction("movir UDPR_4 1")
    spmv__worker_claim_remote_54.writeAction("sendr_wret X30 52 X29 X29 X28")
    spmv__worker_claim_remote_54.writeAction("yield")
    spmv__worker_claim_remote_54.writeAction("spmvMSREFA_okdhl_early_finished: yieldt")
    spmv__worker_claim_remote_54.writeAction("spmvMSREFA_okdhl_worker_finished: yieldt")

    ## spmv__worker_helper with ID 55
    spmv__worker_helper_55 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 55)
    spmv__worker_helper_55.writeAction("yield")

    ## spmv__worker_claimed_map with ID 56
    spmv__worker_claimed_map_56 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 56)
    spmv__worker_claimed_map_56.writeAction("addi X1 UDPR_9 0")
    spmv__worker_claimed_map_56.writeAction("movir UDPR_0 1")
    spmv__worker_claimed_map_56.writeAction("spmvMSREFA_okdhl_launch_mappers: evii X30 60 255 5")
    spmv__worker_claimed_map_56.writeAction("sendr_wret X30 52 X9 X10 X28")
    spmv__worker_claimed_map_56.writeAction("yield")

    ## spmv__receiver_claim_work with ID 57
    spmv__receiver_claim_work_57 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 57)
    spmv__receiver_claim_work_57.writeAction("andi X0 X28 63")
    spmv__receiver_claim_work_57.writeAction("sli X28 X28 16")
    spmv__receiver_claim_work_57.writeAction("sub X7 X28 UDPR_4")
    spmv__receiver_claim_work_57.writeAction("movir UDPR_7 784")
    spmv__receiver_claim_work_57.writeAction("add UDPR_4 UDPR_7 UDPR_7")
    spmv__receiver_claim_work_57.writeAction("movlr 0(UDPR_7) X28 0 8")
    spmv__receiver_claim_work_57.writeAction("movlr 8(UDPR_7) UDPR_9 0 8")
    spmv__receiver_claim_work_57.writeAction("spmvMSREFA_okdhl_claim_maps: beq X28 UDPR_9 spmvMSREFA_okdhl_local_work_resolved")
    spmv__receiver_claim_work_57.writeAction("addi X28 X29 16")
    spmv__receiver_claim_work_57.writeAction("cswp UDPR_7 UDPR_5 X28 X29")
    spmv__receiver_claim_work_57.writeAction("beq X28 UDPR_5 spmvMSREFA_okdhl_claimed_maps")
    spmv__receiver_claim_work_57.writeAction("movlr 0(UDPR_7) X28 0 8")
    spmv__receiver_claim_work_57.writeAction("jmp spmvMSREFA_okdhl_claim_maps")
    spmv__receiver_claim_work_57.writeAction("spmvMSREFA_okdhl_claimed_maps: evii UDPR_15 59 255 5")
    spmv__receiver_claim_work_57.writeAction("addi X1 X30 0")
    spmv__receiver_claim_work_57.writeAction("evlb X30 56")
    spmv__receiver_claim_work_57.writeAction("movir UDPR_7 776")
    spmv__receiver_claim_work_57.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__receiver_claim_work_57.writeAction("movlr 0(UDPR_7) X29 0 8")
    spmv__receiver_claim_work_57.writeAction("movir X28 -3")
    spmv__receiver_claim_work_57.writeAction("sendr3_wcont X30 UDPR_15 X28 UDPR_5 X29")
    spmv__receiver_claim_work_57.writeAction("yieldt")
    spmv__receiver_claim_work_57.writeAction("spmvMSREFA_okdhl_check_terminate_bit: movir UDPR_7 768")
    spmv__receiver_claim_work_57.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__receiver_claim_work_57.writeAction("movlr 0(UDPR_7) X28 0 8")
    spmv__receiver_claim_work_57.writeAction("blti X28 0 spmvMSREFA_okdhl_local_work_resolved")
    spmv__receiver_claim_work_57.writeAction("spmvMSREFA_okdhl_local_work_resolved: movir X28 -2")
    spmv__receiver_claim_work_57.writeAction("sendr_wcont X1 X2 X28 X29")
    spmv__receiver_claim_work_57.writeAction("spmvMSREFA_okdhl_receiver_claim_work_end: yieldt")

    ## spmv__receiver_set_terminate_bit with ID 58
    spmv__receiver_set_terminate_bit_58 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 58)
    spmv__receiver_set_terminate_bit_58.writeAction("movir UDPR_7 768")
    spmv__receiver_set_terminate_bit_58.writeAction("add X7 UDPR_7 UDPR_7")
    spmv__receiver_set_terminate_bit_58.writeAction("movrl X8 0(UDPR_7) 0 8")
    spmv__receiver_set_terminate_bit_58.writeAction("bnei X8 1 spmvMSREFA_okdhl_terminate")
    spmv__receiver_set_terminate_bit_58.writeAction("sendr_reply X28 X28 X28")
    spmv__receiver_set_terminate_bit_58.writeAction("spmvMSREFA_okdhl_terminate: yieldt")

    ## spmv__receiver_set_terminate_bit_ret with ID 59
    spmv__receiver_set_terminate_bit_ret_59 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 59)
    spmv__receiver_set_terminate_bit_ret_59.writeAction("yieldt")

    ## spmv__mapper_control_init with ID 60
    spmv__mapper_control_init_60 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 60)
    spmv__mapper_control_init_60.writeAction("addi X1 X31 0")
    spmv__mapper_control_init_60.writeAction("addi X9 X18 0")
    spmv__mapper_control_init_60.writeAction("send_dmlm_ld_wret X8 61 2 X28")
    spmv__mapper_control_init_60.writeAction("movir X16 0")
    spmv__mapper_control_init_60.writeAction("movir X17 32")
    spmv__mapper_control_init_60.writeAction("movir X19 0")
    spmv__mapper_control_init_60.writeAction("movir X22 640")
    spmv__mapper_control_init_60.writeAction("add X7 X22 X22")
    spmv__mapper_control_init_60.writeAction("addi X2 X28 0")
    spmv__mapper_control_init_60.writeAction("evlb X28 63")
    spmv__mapper_control_init_60.writeAction("movir X29 656")
    spmv__mapper_control_init_60.writeAction("add X7 X29 X29")
    spmv__mapper_control_init_60.writeAction("move X28 0(X29) 0 8")
    spmv__mapper_control_init_60.writeAction("addi X2 X20 0")
    spmv__mapper_control_init_60.writeAction("evlb X20 62")
    spmv__mapper_control_init_60.writeAction("evi X2 X21 255 4")
    spmv__mapper_control_init_60.writeAction("evlb X21 68")
    spmv__mapper_control_init_60.writeAction("yield")

    ## spmv__mapper_control_read_partition with ID 61
    spmv__mapper_control_read_partition_61 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 61)
    spmv__mapper_control_read_partition_61.writeAction("bge X8 X9 spmvMSREFA_okdhl_lane_master_empty_partition")
    spmv__mapper_control_read_partition_61.writeAction("addi X8 X28 16")
    spmv__mapper_control_read_partition_61.writeAction("sendr_wcont X20 X20 X28 X9")
    spmv__mapper_control_read_partition_61.writeAction("send_dmlm_ld X8 X21 2")
    spmv__mapper_control_read_partition_61.writeAction("addi X16 X16 1")
    spmv__mapper_control_read_partition_61.writeAction("movir X23 1")
    spmv__mapper_control_read_partition_61.writeAction("yield")
    spmv__mapper_control_read_partition_61.writeAction("spmvMSREFA_okdhl_lane_master_empty_partition: movir X29 -6")
    spmv__mapper_control_read_partition_61.writeAction("sendr_wcont X18 X2 X19 X19")
    spmv__mapper_control_read_partition_61.writeAction("sendr_wcont X31 X2 X29 X19")
    spmv__mapper_control_read_partition_61.writeAction("yieldt")

    ## spmv__mapper_control_get_next_return with ID 62
    spmv__mapper_control_get_next_return_62 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 62)
    spmv__mapper_control_get_next_return_62.writeAction("bge X16 X17 spmvMSREFA_okdhl_mapper_control_break_iterate_loop")
    spmv__mapper_control_get_next_return_62.writeAction("bge X8 X9 spmvMSREFA_okdhl_mapper_control_break_iterate_loop")
    spmv__mapper_control_get_next_return_62.writeAction("addi X8 X28 16")
    spmv__mapper_control_get_next_return_62.writeAction("sendr_wcont X20 X20 X28 X9")
    spmv__mapper_control_get_next_return_62.writeAction("send_dmlm_ld X8 X21 2")
    spmv__mapper_control_get_next_return_62.writeAction("addi X16 X16 1")
    spmv__mapper_control_get_next_return_62.writeAction("yield")
    spmv__mapper_control_get_next_return_62.writeAction("spmvMSREFA_okdhl_mapper_control_break_iterate_loop: movir X23 0")
    spmv__mapper_control_get_next_return_62.writeAction("addi X8 X23 0")
    spmv__mapper_control_get_next_return_62.writeAction("addi X9 X24 0")
    spmv__mapper_control_get_next_return_62.writeAction("yield")
    spmv__mapper_control_get_next_return_62.writeAction("spmvMSREFA_okdhl_mapper_control_iterator_pass_end: subi X16 X16 1")
    spmv__mapper_control_get_next_return_62.writeAction("addi X8 X23 0")
    spmv__mapper_control_get_next_return_62.writeAction("addi X9 X24 0")
    spmv__mapper_control_get_next_return_62.writeAction("bgti X16 0 spmvMSREFA_okdhl_lane_master_loop_continue")
    spmv__mapper_control_get_next_return_62.writeAction("movlr 0(X22) X19 0 8")
    spmv__mapper_control_get_next_return_62.writeAction("movir X29 -6")
    spmv__mapper_control_get_next_return_62.writeAction("sendr_wcont X31 X2 X29 X19")
    spmv__mapper_control_get_next_return_62.writeAction("sendr_wcont X18 X2 X29 X19")
    spmv__mapper_control_get_next_return_62.writeAction("yieldt")
    spmv__mapper_control_get_next_return_62.writeAction("spmvMSREFA_okdhl_lane_master_loop_continue: yield")

    ## spmv__mapper_control_loop with ID 63
    spmv__mapper_control_loop_63 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 63)
    spmv__mapper_control_loop_63.writeAction("subi X16 X16 1")
    spmv__mapper_control_loop_63.writeAction("beqi X23 1 spmvMSREFA_okdhl_mapper_control_loop_continue")
    spmv__mapper_control_loop_63.writeAction("bge X23 X24 spmvMSREFA_okdhl_mapper_control_reach_end")
    spmv__mapper_control_loop_63.writeAction("addi X23 X28 16")
    spmv__mapper_control_loop_63.writeAction("sendr_wcont X20 X20 X28 X24")
    spmv__mapper_control_loop_63.writeAction("send_dmlm_ld X23 X21 2")
    spmv__mapper_control_loop_63.writeAction("addi X16 X16 1")
    spmv__mapper_control_loop_63.writeAction("movir X23 1")
    spmv__mapper_control_loop_63.writeAction("yield")
    spmv__mapper_control_loop_63.writeAction("spmvMSREFA_okdhl_mapper_control_reach_end: bgti X16 0 spmvMSREFA_okdhl_mapper_control_loop_continue")
    spmv__mapper_control_loop_63.writeAction("movlr 0(X22) X19 0 8")
    spmv__mapper_control_loop_63.writeAction("movir X29 -6")
    spmv__mapper_control_loop_63.writeAction("sendr_wcont X18 X2 X19 X19")
    spmv__mapper_control_loop_63.writeAction("sendr_wcont X31 X2 X29 X19")
    spmv__mapper_control_loop_63.writeAction("mov_imm2reg X19 0")
    spmv__mapper_control_loop_63.writeAction("movrl X19 0(X22) 0 8")
    spmv__mapper_control_loop_63.writeAction("yieldt")
    spmv__mapper_control_loop_63.writeAction("spmvMSREFA_okdhl_mapper_control_loop_continue: yield")

    ## spmv__lane_remote_mapper_finished with ID 64
    spmv__lane_remote_mapper_finished_64 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 64)
    spmv__lane_remote_mapper_finished_64.writeAction("yieldt")

    ## updown_init with ID 65
    updown_init_65 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 65)
    updown_init_65.writeAction("perflog 1 0 'Updown Init'")
    updown_init_65.writeAction("addi X8 UDPR_3 0")
    updown_init_65.writeAction("addi X9 UDPR_4 0")
    updown_init_65.writeAction("addi X10 UDPR_5 0")
    updown_init_65.writeAction("addi X7 UDPR_1 1928")
    updown_init_65.writeAction("add X7 X12 UDPR_10")
    updown_init_65.writeAction("movlr 0(UDPR_10) UDPR_0 1 8")
    updown_init_65.writeAction("movrl UDPR_0 0(UDPR_1) 1 8")
    updown_init_65.writeAction("movlr 0(UDPR_10) UDPR_0 1 8")
    updown_init_65.writeAction("movrl UDPR_0 0(UDPR_1) 1 8")
    updown_init_65.writeAction("add X7 X13 UDPR_10")
    updown_init_65.writeAction("movlr 0(UDPR_10) UDPR_0 1 8")
    updown_init_65.writeAction("movrl UDPR_0 0(UDPR_1) 1 8")
    updown_init_65.writeAction("movlr 0(UDPR_10) UDPR_0 1 8")
    updown_init_65.writeAction("movrl UDPR_0 0(UDPR_1) 1 8")
    updown_init_65.writeAction("add X7 X14 UDPR_10")
    updown_init_65.writeAction("movlr 0(UDPR_10) UDPR_0 1 8")
    updown_init_65.writeAction("movrl UDPR_0 0(UDPR_1) 1 8")
    updown_init_65.writeAction("evii UDPR_9 11 255 5")
    updown_init_65.writeAction("addi X2 UDPR_11 0")
    updown_init_65.writeAction("evlb UDPR_11 66")
    updown_init_65.writeAction("addi X7 UDPR_10 8")
    updown_init_65.writeAction("movrl UDPR_5 0(UDPR_10) 1 8")
    updown_init_65.writeAction("movrl UDPR_11 0(UDPR_10) 1 8")
    updown_init_65.writeAction("movrl X11 0(UDPR_10) 1 8")
    updown_init_65.writeAction("addi X7 UDPR_10 8")
    updown_init_65.writeAction("send_wret UDPR_9 67 UDPR_10 8 UDPR_0")
    updown_init_65.writeAction("yield")

    ## set_vector_ptr with ID 66
    set_vector_ptr_66 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 66)
    set_vector_ptr_66.writeAction("addi X7 UDPR_1 1920")
    set_vector_ptr_66.writeAction("movrl X8 0(UDPR_1) 0 8")
    set_vector_ptr_66.writeAction("sendr_reply X0 X16 X16")
    set_vector_ptr_66.writeAction("yieldt")

    ## msr_init with ID 67
    msr_init_67 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 67)
    msr_init_67.writeAction("perflog 1 0 'MSR init'")
    msr_init_67.writeAction("movir UDPR_2 8")
    msr_init_67.writeAction("add X7 UDPR_2 UDPR_2")
    msr_init_67.writeAction("addi X7 UDPR_1 1928")
    msr_init_67.writeAction("movrl UDPR_3 0(UDPR_2) 1 8")
    msr_init_67.writeAction("movrl UDPR_4 0(UDPR_2) 1 8")
    msr_init_67.writeAction("movrl UDPR_5 0(UDPR_2) 1 8")
    msr_init_67.writeAction("movrl UDPR_1 0(UDPR_2) 1 8")
    msr_init_67.writeAction("addi UDPR_1 UDPR_1 16")
    msr_init_67.writeAction("movrl UDPR_1 0(UDPR_2) 1 8")
    msr_init_67.writeAction("addi UDPR_1 UDPR_1 16")
    msr_init_67.writeAction("movrl UDPR_1 0(UDPR_2) 1 8")
    msr_init_67.writeAction("movir UDPR_2 8")
    msr_init_67.writeAction("add X7 UDPR_2 UDPR_2")
    msr_init_67.writeAction("ev_update_2 UDPR_9 7 255 5")
    msr_init_67.writeAction("send_wret UDPR_9 70 UDPR_2 8 UDPR_0")
    msr_init_67.writeAction("yield")

    ## spmv__kv_map with ID 68
    spmv__kv_map_68 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 68)
    spmv__kv_map_68.writeAction("sri X8 X16 32")
    spmv__kv_map_68.writeAction("addi X9 X17 0")
    spmv__kv_map_68.writeAction("movir X31 1")
    spmv__kv_map_68.writeAction("sli X31 X31 32")
    spmv__kv_map_68.writeAction("subi X31 X31 1")
    spmv__kv_map_68.writeAction("and X8 X31 X18")
    spmv__kv_map_68.writeAction("movir X19 1920")
    spmv__kv_map_68.writeAction("add X7 X19 X19")
    spmv__kv_map_68.writeAction("movlr 0(X19) X19 0 8")
    spmv__kv_map_68.writeAction("muli X18 X31 8")
    spmv__kv_map_68.writeAction("add X31 X19 X19")
    spmv__kv_map_68.writeAction("send_dmlm_ld_wret X19 69 1 X31")
    spmv__kv_map_68.writeAction("yield")

    ## kv_map_calc with ID 69
    kv_map_calc_69 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 69)
    kv_map_calc_69.writeAction("fmul.64 X8 X17 X20")
    kv_map_calc_69.writeAction("fmul.64 X8 X17 X17")
    kv_map_calc_69.writeAction("evii X30 42 255 5")
    kv_map_calc_69.writeAction("sendr_wcont X30 X2 X16 X17")
    kv_map_calc_69.writeAction("addi X2 X30 0")
    kv_map_calc_69.writeAction("evlb X30 44")
    kv_map_calc_69.writeAction("sendr_wcont X30 X2 X16 X17")
    kv_map_calc_69.writeAction("yield")

    ## updown_terminate with ID 70
    updown_terminate_70 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 70)
    updown_terminate_70.writeAction("perflog 1 0 'MSR terminate'")
    updown_terminate_70.writeAction("mov_imm2reg UDPR_0 1")
    updown_terminate_70.writeAction("addi X7 UDPR_1 0")
    updown_terminate_70.writeAction("move UDPR_0 0(UDPR_1) 0 8")
    updown_terminate_70.writeAction("yield_terminate")



def main():
    efa = EFA([])
    efa.code_level = 'machine'
    efaProgram_spmvMSR_rh_nlbstrm_on(efa)
    return efa