/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include <cstdint>
#include <string>
#include "encodings.hh"
#include "debug.hh"

namespace basim {

struct ArchState; // forward declaration
class Cycles; // forward declaration

/* dummy Instruction */
Cycles exeInstDummy(ArchState& ast, EncInst inst);
std::string disasmInstDummy(EncInst inst);
EncInst constrInstDummy();

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
