/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include <cstdint>
#include <string>
#include "encodings.hh"

namespace basim {

struct ArchState; // forward declaration
class Cycles; // forward declaration

/* fmadd.64, fadd.64, fsub.64, fmul.64, fdiv.64, fsqrt.64, fexp.64, fmadd.32, fadd.32, fsub.32, fmul.32, fdiv.32, fsqrt.32, fexp.32, fmadd.b16, fadd.b16, fsub.b16, fmul.b16, fdiv.b16, fsqrt.b16, fexp.b16 Instruction */
Cycles exeInstFmaddFaddFsubFmulFdivFsqrtFexp(ArchState& ast, EncInst inst);
std::string disasmInstFmaddFaddFsubFmulFdivFsqrtFexp(EncInst inst);
EncInst constrInstFmaddFaddFsubFmulFdivFsqrtFexp(uint64_t func, uint64_t precision, RegId Xs, RegId Xt, RegId Xd);

/* fcnvt.64.i64, fcnvt.32.i32, fcnvt.i64.64, fcnvt.i32.32, fcnvt.64.32, fcnvt.64.b16, fcnvt.32.64, fcnvt.32.b16, fcnvt.b16.64, fcnvt.b16.32 Instruction */
Cycles exeInstFcnvt(ArchState& ast, EncInst inst);
std::string disasmInstFcnvt(EncInst inst);
EncInst constrInstFcnvt(uint64_t func, uint64_t precision, RegId Xs, RegId Xd);

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
