/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include "encodings.hh"
#include "int_arith_inst.hh"
#include "int_cmp_inst.hh"
#include "bitwise_inst.hh"
#include "ctrl_flow_inst.hh"
#include "msg_inst.hh"
#include "dat_mov_inst.hh"
#include "tran_ctrl_inst.hh"
#include "thread_ctrl_inst.hh"
#include "fp_arith_inst.hh"
#include "vec_inst.hh"
#include "hash_inst.hh"
#include "ev_inst.hh"
#include "atomic_inst.hh"
#include "debug_inst.hh"
#include "dummy_inst.hh"
#include "debug.hh"

namespace basim {

struct InstHandle {
  Cycles (*exe)(ArchState &, EncInst);
  std::string (*disasm)(EncInst);
};

inline constexpr InstHandle instHandleTable[128] = {
  { // 0x00, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x01
    exeInstYield,
    disasmInstYield,
  },
  { // 0x02
    exeInstYieldt,
    disasmInstYieldt,
  },
  { // 0x03
    exeInstClti,
    disasmInstClti,
  },
  { // 0x04
    exeInstCgti,
    disasmInstCgti,
  },
  { // 0x05
    exeInstCeqi,
    disasmInstCeqi,
  },
  { // 0x06
    exeInstAndi,
    disasmInstAndi,
  },
  { // 0x07
    exeInstOri,
    disasmInstOri,
  },
  { // 0x08
    exeInstMovir,
    disasmInstMovir,
  },
  { // 0x09
    exeInstAddi,
    disasmInstAddi,
  },
  { // 0x0a
    exeInstSubi,
    disasmInstSubi,
  },
  { // 0x0b
    exeInstMuli,
    disasmInstMuli,
  },
  { // 0x0c
    exeInstDivi,
    disasmInstDivi,
  },
  { // 0x0d, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x0e
    exeInstMovil2,
    disasmInstMovil2,
  },
  { // 0x0f
    exeInstMovil1,
    disasmInstMovil1,
  },
  { // 0x10
    exeInstSend,
    disasmInstSend,
  },
  { // 0x11
    exeInstSendm,
    disasmInstSendm,
  },
  { // 0x12
    exeInstSendmb,
    disasmInstSendmb,
  },
  { // 0x13
    exeInstSendr,
    disasmInstSendr,
  },
  { // 0x14
    exeInstSendmr,
    disasmInstSendmr,
  },
  { // 0x15
    exeInstSendb,
    disasmInstSendb,
  },
  { // 0x16
    exeInstSendops,
    disasmInstSendops,
  },
  { // 0x17
    exeInstSendr3,
    disasmInstSendr3,
  },
  { // 0x18
    exeInstSendmops,
    disasmInstSendmops,
  },
  { // 0x19
    exeInstSendmr2,
    disasmInstSendmr2,
  },
  { // 0x1a
    exeInstInstrans,
    disasmInstInstrans,
  },
  { // 0x1b, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x1c, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x1d, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x1e, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x1f, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x20
    exeInstMovlr,
    disasmInstMovlr,
  },
  { // 0x21
    exeInstMovrl,
    disasmInstMovrl,
  },
  { // 0x22
    exeInstSladdii,
    disasmInstSladdii,
  },
  { // 0x23
    exeInstSlsubii,
    disasmInstSlsubii,
  },
  { // 0x24
    exeInstBcpyoli,
    disasmInstBcpyoli,
  },
  { // 0x25
    exeInstSlorii,
    disasmInstSlorii,
  },
  { // 0x26
    exeInstSrorii,
    disasmInstSrorii,
  },
  { // 0x27
    exeInstSlandii,
    disasmInstSlandii,
  },
  { // 0x28
    exeInstSraddii,
    disasmInstSraddii,
  },
  { // 0x29
    exeInstSrandii,
    disasmInstSrandii,
  },
  { // 0x2a
    exeInstMovbil,
    disasmInstMovbil,
  },
  { // 0x2b
    exeInstMovblr,
    disasmInstMovblr,
  },
  { // 0x2c
    exeInstFstate,
    disasmInstFstate,
  },
  { // 0x2d
    exeInstCswpi,
    disasmInstCswpi,
  },
  { // 0x2e
    exeInstSwiz,
    disasmInstSwiz,
  },
  { // 0x2f
    exeInstSrsubii,
    disasmInstSrsubii,
  },
  { // 0x30
    exeInstBcpyol,
    disasmInstBcpyol,
  },
  { // 0x31
    exeInstMovwlr,
    disasmInstMovwlr,
  },
  { // 0x32
    exeInstMovwrl,
    disasmInstMovwrl,
  },
  { // 0x33
    exeInstAddSubMulDivMod,
    disasmInstAddSubMulDivMod,
  },
  { // 0x34
    exeInstAndOrXor,
    disasmInstAndOrXor,
  },
  { // 0x35
    exeInstCltCgtCeqCstr,
    disasmInstCltCgtCeqCstr,
  },
  { // 0x36
    exeInstSrSlSar,
    disasmInstSrSlSar,
  },
  { // 0x37
    exeInstBcpyll,
    disasmInstBcpyll,
  },
  { // 0x38
    exeInstMovrr,
    disasmInstMovrr,
  },
  { // 0x39, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3a, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3b, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3c, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3d, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3e, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x3f, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x40
    exeInstEvi,
    disasmInstEvi,
  },
  { // 0x41
    exeInstEvii,
    disasmInstEvii,
  },
  { // 0x42
    exeInstEvlb,
    disasmInstEvlb,
  },
  { // 0x43
    exeInstBneiBeqiBgtiBleiBltiBgei,
    disasmInstBneiBeqiBgtiBleiBltiBgei,
  },
  { // 0x44
    exeInstBneBeqBgtBle,
    disasmInstBneBeqBgtBle,
  },
  { // 0x45
    exeInstBneiuBeqiuBgtiuBleiuBltiuBgeiu,
    disasmInstBneiuBeqiuBgtiuBleiuBltiuBgeiu,
  },
  { // 0x46
    exeInstJmp,
    disasmInstJmp,
  },
  { // 0x47, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x48
    exeInstBneuBequBgtuBleu,
    disasmInstBneuBequBgtuBleu,
  },
  { // 0x49, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4a, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4b, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4c, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4d, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4e, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x4f, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x50
    exeInstSli,
    disasmInstSli,
  },
  { // 0x51
    exeInstSri,
    disasmInstSri,
  },
  { // 0x52
    exeInstSlori,
    disasmInstSlori,
  },
  { // 0x53
    exeInstSrori,
    disasmInstSrori,
  },
  { // 0x54
    exeInstSlandi,
    disasmInstSlandi,
  },
  { // 0x55
    exeInstSrandi,
    disasmInstSrandi,
  },
  { // 0x56
    exeInstSari,
    disasmInstSari,
  },
  { // 0x57
    exeInstHashsb32,
    disasmInstHashsb32,
  },
  { // 0x58
    exeInstHashsb64,
    disasmInstHashsb64,
  },
  { // 0x59
    exeInstHashl64,
    disasmInstHashl64,
  },
  { // 0x5a
    exeInstHash,
    disasmInstHash,
  },
  { // 0x5b
    exeInstHashl,
    disasmInstHashl,
  },
  { // 0x5c
    exeInstBcpylli,
    disasmInstBcpylli,
  },
  { // 0x5d
    exeInstMovsbr,
    disasmInstMovsbr,
  },
  { // 0x5e
    exeInstMovipr,
    disasmInstMovipr,
  },
  { // 0x5f
    exeInstMovlsb,
    disasmInstMovlsb,
  },
  { // 0x60
    exeInstFmaddFaddFsubFmulFdivFsqrtFexp,
    disasmInstFmaddFaddFsubFmulFdivFsqrtFexp,
  },
  { // 0x61
    exeInstFcnvt,
    disasmInstFcnvt,
  },
  { // 0x62
    exeInstVmaddVaddVsubVmulVdivVsqrtVexp,
    disasmInstVmaddVaddVsubVmulVdivVsqrtVexp,
  },
  { // 0x63
    exeInstVgt,
    disasmInstVgt,
  },
  { // 0x64
    exeInstVfill,
    disasmInstVfill,
  },
  { // 0x65, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x66, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x67, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x68, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x69, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6a, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6b, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6c, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6d, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6e, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x6f, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x70
    exeInstEv,
    disasmInstEv,
  },
  { // 0x71
    exeInstCswp,
    disasmInstCswp,
  },
  { // 0x72, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x73, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x74, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x75, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x76, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x77, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x78
    exeInstSsprop,
    disasmInstSsprop,
  },
  { // 0x79
    exeInstSiw,
    disasmInstSiw,
  },
  { // 0x7a
    exeInstRefill,
    disasmInstRefill,
  },
  { // 0x7b
    exeInstXori,
    disasmInstXori,
  },
  { // 0x7c
    exeInstModi,
    disasmInstModi,
  },
  { // 0x7d
    exeInstLastact,
    disasmInstLastact,
  },
  { // 0x7e, not encoded
    exeInstDummy,
    disasmInstDummy,
  },
  { // 0x7f
    exeInstPrintPerflog,
    disasmInstPrintPerflog,
  },
}; // instHandleTable

inline constexpr InstHandle decodeInst(EncInst inst) { return instHandleTable[static_cast<uint8_t>(extrInstOpcode(inst))]; }

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
