/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include <cstdint>
#include <string>
#include "encodings.hh"

namespace basim {

struct ArchState; // forward declaration
class Cycles; // forward declaration

/* addi Instruction */
Cycles exeInstAddi(ArchState& ast, EncInst inst);
std::string disasmInstAddi(EncInst inst);
EncInst constrInstAddi(RegId Xs, RegId Xd, int64_t imm);

/* subi Instruction */
Cycles exeInstSubi(ArchState& ast, EncInst inst);
std::string disasmInstSubi(EncInst inst);
EncInst constrInstSubi(RegId Xs, RegId Xd, int64_t imm);

/* muli Instruction */
Cycles exeInstMuli(ArchState& ast, EncInst inst);
std::string disasmInstMuli(EncInst inst);
EncInst constrInstMuli(RegId Xs, RegId Xd, int64_t imm);

/* divi Instruction */
Cycles exeInstDivi(ArchState& ast, EncInst inst);
std::string disasmInstDivi(EncInst inst);
EncInst constrInstDivi(RegId Xs, RegId Xd, int64_t imm);

/* modi Instruction */
Cycles exeInstModi(ArchState& ast, EncInst inst);
std::string disasmInstModi(EncInst inst);
EncInst constrInstModi(RegId Xs, RegId Xd, int64_t imm);

/* add, sub, mul, div, mod Instruction */
Cycles exeInstAddSubMulDivMod(ArchState& ast, EncInst inst);
std::string disasmInstAddSubMulDivMod(EncInst inst);
EncInst constrInstAddSubMulDivMod(uint64_t func, RegId Xs, RegId Xt, RegId Xd);

/* sladdii Instruction */
Cycles exeInstSladdii(ArchState& ast, EncInst inst);
std::string disasmInstSladdii(EncInst inst);
EncInst constrInstSladdii(RegId Xs, RegId Xd, uint64_t shift, uint64_t imm);

/* slsubii Instruction */
Cycles exeInstSlsubii(ArchState& ast, EncInst inst);
std::string disasmInstSlsubii(EncInst inst);
EncInst constrInstSlsubii(RegId Xs, RegId Xd, uint64_t shift, uint64_t imm);

/* sraddii Instruction */
Cycles exeInstSraddii(ArchState& ast, EncInst inst);
std::string disasmInstSraddii(EncInst inst);
EncInst constrInstSraddii(RegId Xs, RegId Xd, uint64_t shift, uint64_t imm);

/* srsubii Instruction */
Cycles exeInstSrsubii(ArchState& ast, EncInst inst);
std::string disasmInstSrsubii(EncInst inst);
EncInst constrInstSrsubii(RegId Xs, RegId Xd, uint64_t shift, uint64_t imm);

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
