/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include <cstdint>
#include <string>
#include "encodings.hh"

namespace basim {

struct ArchState; // forward declaration
class Cycles; // forward declaration

/* yield Instruction */
Cycles exeInstYield(ArchState& ast, EncInst inst);
std::string disasmInstYield(EncInst inst);
EncInst constrInstYield();

/* yieldt Instruction */
Cycles exeInstYieldt(ArchState& ast, EncInst inst);
std::string disasmInstYieldt(EncInst inst);
EncInst constrInstYieldt();

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
