/* AUTOGENERATED FILE - DO NOT MODIFY */
#pragma once
#include <cstdint>
#include <string>
#include "encodings.hh"

namespace basim {

struct ArchState; // forward declaration
class Cycles; // forward declaration

/* vmadd.32, vadd.32, vsub.32, vmul.32, vdiv.32, vsqrt.32, vexp.32, vmadd.b16, vadd.b16, vsub.b16, vmul.b16, vdiv.b16, vsqrt.b16, vexp.b16, vmadd.i32, vadd.i32, vsub.i32, vmul.i32, vdiv.i32, vsqrt.i32, vexp.i32 Instruction */
Cycles exeInstVmaddVaddVsubVmulVdivVsqrtVexp(ArchState& ast, EncInst inst);
std::string disasmInstVmaddVaddVsubVmulVdivVsqrtVexp(EncInst inst);
EncInst constrInstVmaddVaddVsubVmulVdivVsqrtVexp(uint64_t func, uint64_t precision, RegId Xs, RegId Xt, RegId Xd, uint64_t mask);

/* vgt.32, vgt.b16, vgt.i32 Instruction */
Cycles exeInstVgt(ArchState& ast, EncInst inst);
std::string disasmInstVgt(EncInst inst);
EncInst constrInstVgt(uint64_t precision, RegId Xs, RegId Xt, RegId Xd, uint64_t mask);

/* vfill.32, vfill.i32, vfill.b16 Instruction */
Cycles exeInstVfill(ArchState& ast, EncInst inst);
std::string disasmInstVfill(EncInst inst);
EncInst constrInstVfill(uint64_t precision, uint64_t imma, RegId Xd, uint64_t immb);

}; // namespace basim
/* AUTOGENERATED FILE - DO NOT MODIFY */
