from EFA_v2 import EFA, State, Transition

def efaProgram_gcn_udkvmsr_exe_rh_nlbstrm_on(efa):

    ## init_null_state with ID 0
    init_null_state_0 = State()
    efa.add_state(init_null_state_0)
    efa.add_initId(init_null_state_0.state_id)

    ## gnn_vanilla_kvmsr__map_shuffle_reduce with ID 0
    gnn_vanilla_kvmsr__map_shuffle_reduce_0 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 0)
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X7 X20 688")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X1 X31 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("move X31 0(X20) 0 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X8 X16 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X10 X27 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("mul X9 X27 X19")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X2 X21 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evlb X21 1")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X7 X20 800")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X11 X29 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("bcpylli X29 X20 16")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evi X2 X26 255 4")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evlb X26 2")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("sendr_wcont X26 X21 X16 X19")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evlb X30 4")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movir X17 704")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("add X7 X17 X17")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movrl X27 0(X17) 0 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evlb X18 12")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movrl X18 8(X17) 0 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movrl X27  16(X17) 0 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movrl X0 24(X17) 0 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("send_wcont X30 X21 X17 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X17 X20 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("evlb X18 11")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movrl X18 0(X20) 1 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X11 X29 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("bcpylli X29 X20 16")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("send_wcont X30 X21 X17 8")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("movir X26 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("addi X9 X19 0")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("perflog 1 0 'UDKVMSR Initialization setup finished.' ")
    gnn_vanilla_kvmsr__map_shuffle_reduce_0.writeAction("yield")

    ## gnn_vanilla_kvmsr__finish_init_udkvmsr with ID 1
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 1)
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("bgei X26 3 EFA_gcn_lrrjs_finish_initialize_udkvmsr")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("yield")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("EFA_gcn_lrrjs_finish_initialize_udkvmsr: addi X2 X30 0")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("evlb X30 13")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("perflog 1 0 'UDKVMSR Initialization Finished.' ")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("sendr_wcont X30 X31 X16 X19")
    gnn_vanilla_kvmsr__finish_init_udkvmsr_1.writeAction("yield")

    ## gnn_input__generate_partition_array with ID 2
    gnn_input__generate_partition_array_2 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 2)
    gnn_input__generate_partition_array_2.writeAction("addi X9 X21 0")
    gnn_input__generate_partition_array_2.writeAction("addi X1 X16 0")
    gnn_input__generate_partition_array_2.writeAction("addi X2 X27 0")
    gnn_input__generate_partition_array_2.writeAction("evlb X27 3")
    gnn_input__generate_partition_array_2.writeAction("addi X7 X29 800")
    gnn_input__generate_partition_array_2.writeAction("movlr 0(X29) X19 1 8")
    gnn_input__generate_partition_array_2.writeAction("movlr 0(X29) X20 1 8")
    gnn_input__generate_partition_array_2.writeAction("sli X20 X17 4")
    gnn_input__generate_partition_array_2.writeAction("add X19 X17 X17")
    gnn_input__generate_partition_array_2.writeAction("div X20 X21 X22")
    gnn_input__generate_partition_array_2.writeAction("mul X22 X21 X30")
    gnn_input__generate_partition_array_2.writeAction("beq X30 X20 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_input__generate_partition_array_2.writeAction("addi X22 X22 1")
    gnn_input__generate_partition_array_2.writeAction("EFA_gcn_lrrjs_modular_eq_zero: sli X22 X23 4")
    gnn_input__generate_partition_array_2.writeAction("addi X8 X18 0")
    gnn_input__generate_partition_array_2.writeAction("sli X21 X24 4")
    gnn_input__generate_partition_array_2.writeAction("add X8 X24 X24")
    gnn_input__generate_partition_array_2.writeAction("EFA_gcn_lrrjs_write_partition_array_loop: bge X18 X24 EFA_gcn_lrrjs_loop_break")
    gnn_input__generate_partition_array_2.writeAction("add X19 X23 X25")
    gnn_input__generate_partition_array_2.writeAction("ble X25 X17 EFA_gcn_lrrjs_continue")
    gnn_input__generate_partition_array_2.writeAction("addi X17 X25 0")
    gnn_input__generate_partition_array_2.writeAction("EFA_gcn_lrrjs_continue: sendr2_dmlm X18 X27 X19 X25")
    gnn_input__generate_partition_array_2.writeAction("addi X18 X18 16")
    gnn_input__generate_partition_array_2.writeAction("addi X25 X19 0")
    gnn_input__generate_partition_array_2.writeAction("jmp EFA_gcn_lrrjs_write_partition_array_loop")
    gnn_input__generate_partition_array_2.writeAction("EFA_gcn_lrrjs_loop_break: movir X26 0")
    gnn_input__generate_partition_array_2.writeAction("yield")

    ## gnn_input__write_partition_array_return with ID 3
    gnn_input__write_partition_array_return_3 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 3)
    gnn_input__write_partition_array_return_3.writeAction("addi X26 X26 1")
    gnn_input__write_partition_array_return_3.writeAction("blt X26 X21 EFA_gcn_lrrjs_continue")
    gnn_input__write_partition_array_return_3.writeAction("sendr_wcont X16 X2 X18 X21")
    gnn_input__write_partition_array_return_3.writeAction("yieldt")
    gnn_input__write_partition_array_return_3.writeAction("EFA_gcn_lrrjs_continue: yield")

    ## gnn_vanilla_kvmsr__broadcast_global with ID 4
    gnn_vanilla_kvmsr__broadcast_global_4 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 4)
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("addi X8 X27 0")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("sri X27 X25 11")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("movir X16 512")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("bgt X25 X16 EFA_gcn_lrrjs_max_child_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("andi X27 X16 2047")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("beqi X16 0 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("addi X25 X25 1")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("jmp EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("EFA_gcn_lrrjs_max_child_modular_eq_zero: mov_imm2reg X25 512")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("EFA_gcn_lrrjs_modular_eq_zero: evi X2 X28 255 4")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("evlb X28 5")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("mov_imm2reg X17 0")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("EFA_gcn_lrrjs_broadcast_loop: lshift X17 X16 11")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("add X0 X16 X16")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("ev X28 X28 X16 X16 8")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("sendops_wret X28 9 X8 8 X16")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("addi X17 X17 1")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("blt X17 X25 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("mov_imm2reg X26 0")
    gnn_vanilla_kvmsr__broadcast_global_4.writeAction("yield")

    ## gnn_vanilla_kvmsr__broadcast_node with ID 5
    gnn_vanilla_kvmsr__broadcast_node_5 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 5)
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("addi X1 X29 0")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("sri X8 X25 6")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("movir X16 32")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("bgt X25 X16 EFA_gcn_lrrjs_max_child_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("andi X8 X16 63")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("beqi X16 0 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("addi X25 X25 1")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("jmp EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("EFA_gcn_lrrjs_max_child_modular_eq_zero: mov_imm2reg X25 32")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("EFA_gcn_lrrjs_modular_eq_zero: evi X2 X28 255 4")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("evlb X28 6")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("mov_imm2reg X17 0")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("EFA_gcn_lrrjs_broadcast_loop: lshift X17 X16 6")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("add X0 X16 X16")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("ev X28 X28 X16 X16 8")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("sendops_wret X28 8 X8 8 X16")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("addi X17 X17 1")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("blt X17 X25 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("mov_imm2reg X26 0")
    gnn_vanilla_kvmsr__broadcast_node_5.writeAction("yield")

    ## gnn_vanilla_kvmsr__broadcast_ud with ID 6
    gnn_vanilla_kvmsr__broadcast_ud_6 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 6)
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("addi X1 X29 0")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("movir X25 64")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("bgt X8 X25 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("addi X8 X25 0")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("EFA_gcn_lrrjs_modular_eq_zero: evi X2 X28 255 4")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("ev X28 X28 X9 X9 1")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("mov_imm2reg X17 0")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("EFA_gcn_lrrjs_broadcast_loop: add X0 X17 X16")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("ev X28 X28 X16 X16 8")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("sendops_wret X28 7 X10 6 X16")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("addi X17 X17 1")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("blt X17 X25 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("mov_imm2reg X26 0")
    gnn_vanilla_kvmsr__broadcast_ud_6.writeAction("yield")

    ## gnn_vanilla_kvmsr__broadcast_ud_fin with ID 7
    gnn_vanilla_kvmsr__broadcast_ud_fin_7 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 7)
    gnn_vanilla_kvmsr__broadcast_ud_fin_7.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__broadcast_ud_fin_7.writeAction("blt X26 X25 EFA_gcn_lrrjs_continue")
    gnn_vanilla_kvmsr__broadcast_ud_fin_7.writeAction("sendr_reply X0 X2 X16")
    gnn_vanilla_kvmsr__broadcast_ud_fin_7.writeAction("yield_terminate")
    gnn_vanilla_kvmsr__broadcast_ud_fin_7.writeAction("EFA_gcn_lrrjs_continue: yield")

    ## gnn_vanilla_kvmsr__broadcast_node_fin with ID 8
    gnn_vanilla_kvmsr__broadcast_node_fin_8 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 8)
    gnn_vanilla_kvmsr__broadcast_node_fin_8.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__broadcast_node_fin_8.writeAction("blt X26 X25 EFA_gcn_lrrjs_continue")
    gnn_vanilla_kvmsr__broadcast_node_fin_8.writeAction("sendr_reply X0 X2 X16")
    gnn_vanilla_kvmsr__broadcast_node_fin_8.writeAction("yield_terminate")
    gnn_vanilla_kvmsr__broadcast_node_fin_8.writeAction("EFA_gcn_lrrjs_continue: yield")

    ## gnn_vanilla_kvmsr__broadcast_global_fin with ID 9
    gnn_vanilla_kvmsr__broadcast_global_fin_9 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 9)
    gnn_vanilla_kvmsr__broadcast_global_fin_9.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__broadcast_global_fin_9.writeAction("beq X26 X25 EFA_gcn_lrrjs_global_bcst_finish")
    gnn_vanilla_kvmsr__broadcast_global_fin_9.writeAction("yield")
    gnn_vanilla_kvmsr__broadcast_global_fin_9.writeAction("EFA_gcn_lrrjs_global_bcst_finish: sendr_reply X0 X2 X16")
    gnn_vanilla_kvmsr__broadcast_global_fin_9.writeAction("yieldt")

    ## gnn_vanilla_kvmsr__broadcast_value_to_scratchpad with ID 10
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 10)
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("sri X8 X16 32")
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("add X7 X16 X16")
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("andi X8 X17 15")
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("bcpyol X9 X16 X17")
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("sendr_reply X1 X2 X16")
    gnn_vanilla_kvmsr__broadcast_value_to_scratchpad_10.writeAction("yieldt")

    ## gnn_vanilla_kvmsr__init_input_kvset_on_lane with ID 11
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 11)
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11.writeAction("movir X16 800")
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11.writeAction("add X7 X16 X16")
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11.writeAction("bcpyoli X8 X16 2")
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11.writeAction("sendr_reply X0 X16 X28")
    gnn_vanilla_kvmsr__init_input_kvset_on_lane_11.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__init_sp_lane with ID 12
    gnn_vanilla_kvmsr__init_sp_lane_12 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 12)
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("mov_imm2reg UDPR_0 0")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("addi X7 X20 640")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move UDPR_0 0(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move UDPR_0 8(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move UDPR_0 24(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("movir X28 128")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move X28 32(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("subi X8 X28 1")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move X28 40(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("move X9 56(X20) 0 8")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("sendr_reply X0 X16 X28")
    gnn_vanilla_kvmsr__init_sp_lane_12.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__init_global_master with ID 13
    gnn_vanilla_kvmsr__init_global_master_13 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 13)
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("mul X27 X9 X24")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("sri X27 X25 11")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("movir X28 512")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("bgt X25 X28 EFA_gcn_lrrjs_max_child_modular_eq_zero")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("andi X27 X28 2047")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("beqi X28 0 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("addi X25 X25 1")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("jmp EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("EFA_gcn_lrrjs_max_child_modular_eq_zero: mov_imm2reg X25 512")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("EFA_gcn_lrrjs_modular_eq_zero: mov_imm2reg X22 2048")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("bge X27 X22 EFA_gcn_lrrjs_global_master_full_child")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("addi X27 X22 0")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("EFA_gcn_lrrjs_global_master_full_child: mul X22 X9 X20")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("lshift X20 X18 4")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("mov_reg2reg X0 X23")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("movir X21 0")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("evlb X30 15")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("EFA_gcn_lrrjs_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("sendr3_wret X30 14             X16 X18 X27 X28")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("add X22 X23 X23")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("addi X21 X21 1")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("blt X21 X25 EFA_gcn_lrrjs_glb_master_loop")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("mul X21 X20 X17")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__init_global_master_13.writeAction("yield")

    ## gnn_vanilla_kvmsr__global_master with ID 14
    gnn_vanilla_kvmsr__global_master_14 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 14)
    gnn_vanilla_kvmsr__global_master_14.writeAction("add X8 X19 X19")
    gnn_vanilla_kvmsr__global_master_14.writeAction("bge X17 X24 EFA_gcn_lrrjs_global_master_fin_fetch")
    gnn_vanilla_kvmsr__global_master_14.writeAction("sendr3_wret X1 14             X16 X18 X27 X28")
    gnn_vanilla_kvmsr__global_master_14.writeAction("add X20 X17 X17")
    gnn_vanilla_kvmsr__global_master_14.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__global_master_14.writeAction("yield")
    gnn_vanilla_kvmsr__global_master_14.writeAction("EFA_gcn_lrrjs_global_master_fin_fetch: subi X21 X21 1")
    gnn_vanilla_kvmsr__global_master_14.writeAction("addi X1 X30 0")
    gnn_vanilla_kvmsr__global_master_14.writeAction("evlb X30 17")
    gnn_vanilla_kvmsr__global_master_14.writeAction("sendr_wcont X30 X2 X16 X16")
    gnn_vanilla_kvmsr__global_master_14.writeAction("beqi X21 0 EFA_gcn_lrrjs_global_master_fin_map")
    gnn_vanilla_kvmsr__global_master_14.writeAction("yield")
    gnn_vanilla_kvmsr__global_master_14.writeAction("EFA_gcn_lrrjs_global_master_fin_map: evii X30, 4 255 5")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movir X29 704")
    gnn_vanilla_kvmsr__global_master_14.writeAction("add X7 X29 X29")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movrl X27 0(X29) 0 8")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movir X28 0")
    gnn_vanilla_kvmsr__global_master_14.writeAction("evlb X28 44")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movrl X28 8(X29) 0 8")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movir X28 1")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movrl X28  16(X29) 0 8")
    gnn_vanilla_kvmsr__global_master_14.writeAction("evii X28 45 255 5")
    gnn_vanilla_kvmsr__global_master_14.writeAction("send_wcont X30 X28 X29 8")
    gnn_vanilla_kvmsr__global_master_14.writeAction("print 'broadcasting terminate bit, num_map_gen %lu' X19")
    gnn_vanilla_kvmsr__global_master_14.writeAction("bnei X19 0 EFA_gcn_lrrjs_global_master_init_sync")
    gnn_vanilla_kvmsr__global_master_14.writeAction("movir X28 -1")
    gnn_vanilla_kvmsr__global_master_14.writeAction("sri X28 X28 1")
    gnn_vanilla_kvmsr__global_master_14.writeAction("sendr_wcont X31 X28 X27 X19")
    gnn_vanilla_kvmsr__global_master_14.writeAction("print 'returning to user cont %lx' X31")
    gnn_vanilla_kvmsr__global_master_14.writeAction("yieldt")
    gnn_vanilla_kvmsr__global_master_14.writeAction("EFA_gcn_lrrjs_global_master_init_sync: evi X2 X30 255 4")
    gnn_vanilla_kvmsr__global_master_14.writeAction("evlb X30 27")
    gnn_vanilla_kvmsr__global_master_14.writeAction("sendr_wcont X30 X31 X27 X19")
    gnn_vanilla_kvmsr__global_master_14.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__init_node_master with ID 15
    gnn_vanilla_kvmsr__init_node_master_15 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 15)
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("movir X26 0")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_reg2reg X1 X31")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_reg2reg X8 X16")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_reg2reg X10 X27")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("sri X27 X25 6")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("movir X28 32")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("bgt X25 X28 EFA_gcn_lrrjs_max_child_modular_eq_zero")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("andi X27 X28 63")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("beqi X28 0 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("addi X25 X25 1")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("jmp EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("EFA_gcn_lrrjs_max_child_modular_eq_zero: mov_imm2reg X25 32")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("EFA_gcn_lrrjs_modular_eq_zero: add X9 X16 X24")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_imm2reg X21 0")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_imm2reg X22 64")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("bge X27 X22 EFA_gcn_lrrjs_node_master_full_child")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("addi X27 X22 0")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("EFA_gcn_lrrjs_node_master_full_child: div X9 X25 X18")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("addi X0 X23 0")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("evlb X30 18")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("EFA_gcn_lrrjs_node_master_loop: ev X30 X30 X23 X23 8")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("sendr3_wret X30 16             X16 X18 X27 X28")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("add X22 X23 X23")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("addi X21 X21 1")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("blt X21 X25 EFA_gcn_lrrjs_node_master_loop")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__init_node_master_15.writeAction("yield")

    ## gnn_vanilla_kvmsr__node_master with ID 16
    gnn_vanilla_kvmsr__node_master_16 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 16)
    gnn_vanilla_kvmsr__node_master_16.writeAction("add X8 X19 X19")
    gnn_vanilla_kvmsr__node_master_16.writeAction("bge X16 X24 EFA_gcn_lrrjs_node_master_fin_fetch")
    gnn_vanilla_kvmsr__node_master_16.writeAction("sendr3_wret X1 16             X16 X18 X27 X28")
    gnn_vanilla_kvmsr__node_master_16.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__node_master_16.writeAction("yield")
    gnn_vanilla_kvmsr__node_master_16.writeAction("EFA_gcn_lrrjs_node_master_fin_fetch: subi X21 X21 1")
    gnn_vanilla_kvmsr__node_master_16.writeAction("addi X1 X30 0")
    gnn_vanilla_kvmsr__node_master_16.writeAction("evlb X30 20")
    gnn_vanilla_kvmsr__node_master_16.writeAction("sendr_wcont X30 X2 X16 X22")
    gnn_vanilla_kvmsr__node_master_16.writeAction("beqi X21 0 EFA_gcn_lrrjs_node_master_fin_partition")
    gnn_vanilla_kvmsr__node_master_16.writeAction("yield")
    gnn_vanilla_kvmsr__node_master_16.writeAction("EFA_gcn_lrrjs_node_master_fin_partition: sendr_wret X31 15             X19 X19 X28")
    gnn_vanilla_kvmsr__node_master_16.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__node_master_16.writeAction("yield")

    ## gnn_vanilla_kvmsr__termiante_node_master with ID 17
    gnn_vanilla_kvmsr__termiante_node_master_17 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 17)
    gnn_vanilla_kvmsr__termiante_node_master_17.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__init_updown_master with ID 18
    gnn_vanilla_kvmsr__init_updown_master_18 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 18)
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movir X26 0")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_reg2reg X1 X31")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_reg2reg X8 X16")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_reg2reg X10 X27")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movir X25 64")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("bgt X27 X25 EFA_gcn_lrrjs_modular_eq_zero")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("addi X27 X25 0")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("EFA_gcn_lrrjs_modular_eq_zero: add X9 X16 X24")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_imm2reg X21 0")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_imm2reg X18 16")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movir X29 784")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("add X7 X29 X29")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mul X25 X18 X28")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("add X16 X28 X28")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movrl X28 0(X29) 0 8")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movir X29 792")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("add X7 X29 X29")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("movrl X24 0(X29) 0 8")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_reg2reg X0 X23")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("evlb X30 21")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("EFA_gcn_lrrjs_updown_master_loop: ev X30 X30 X23 X23 8")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("sendr3_wret X30 19                 X16 X18 X21 X28")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("addi X23 X23 1")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("addi X21 X21 1")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("addi X26 X26 1")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("blt X21 X25 EFA_gcn_lrrjs_updown_master_loop")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("addi X21 X22 0")
    gnn_vanilla_kvmsr__init_updown_master_18.writeAction("yield")

    ## gnn_vanilla_kvmsr__updown_master with ID 19
    gnn_vanilla_kvmsr__updown_master_19 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 19)
    gnn_vanilla_kvmsr__updown_master_19.writeAction("add X8 X19 X19")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("bge X16 X24 EFA_gcn_lrrjs_updown_master_fin_fetch")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("addi X22 X22 1")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("add X18 X16 X16 ")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("yield")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("EFA_gcn_lrrjs_updown_master_fin_fetch: subi X21 X21 1")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("blei X21 0 EFA_gcn_lrrjs_updown_master_fin_partition")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("yield")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("EFA_gcn_lrrjs_updown_master_fin_partition: sendr_wret X31             18 X19 X19 X28")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__updown_master_19.writeAction("yield")

    ## gnn_vanilla_kvmsr__terminate_updown_master with ID 20
    gnn_vanilla_kvmsr__terminate_updown_master_20 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 20)
    gnn_vanilla_kvmsr__terminate_updown_master_20.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__lane_master_init with ID 21
    gnn_vanilla_kvmsr__lane_master_init_21 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 21)
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("addi X1 X31 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("send_dmlm_ld_wret X8 23 2 X28")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("movir X16 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("movir X17 64")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("addi X7 X22 640")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("move X19 0(X22) 0 8")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("addi X2 X28 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("evlb X28 22")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("addi X7 X29 656")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("move X28 0(X29) 0 8")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("addi X2 X20 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("evlb X20 24")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("evi X2 X21 255 4")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("evlb X21 53")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("movir X25 0")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("movir X28 776")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("add X7 X28 X28")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("movrl X1 0(X28) 0 8")
    gnn_vanilla_kvmsr__lane_master_init_21.writeAction("yield")

    ## gnn_vanilla_kvmsr__lane_master_loop with ID 22
    gnn_vanilla_kvmsr__lane_master_loop_22 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 22)
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("subi X16 X16 1")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("beqi X23 1 EFA_gcn_lrrjs_lane_master_loop_continue")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("bge X23 X24 EFA_gcn_lrrjs_lane_master_reach_end")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("addi X23 X28 16")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("sendr_wcont X20 X20 X28 X24")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("send_dmlm_ld X23 X21 2")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("movir X23 1")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("yield")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("EFA_gcn_lrrjs_lane_master_reach_end: bgti X16 0 EFA_gcn_lrrjs_lane_master_loop_continue")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("movlr 0(X22) X19 0 8")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("sendr_wret X31 21 X19 X19 X28")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("movrl X19 0(X22) 0 8")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("addi X2 X30 0")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("evlb X30 26")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("sendr_wcont X30 X2 X28 X28")
    gnn_vanilla_kvmsr__lane_master_loop_22.writeAction("EFA_gcn_lrrjs_lane_master_loop_continue: yield")

    ## gnn_vanilla_kvmsr__lane_master_read_partition with ID 23
    gnn_vanilla_kvmsr__lane_master_read_partition_23 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 23)
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("bge X8 X9 EFA_gcn_lrrjs_lane_master_empty_partition")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("addi X8 X28 16")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("sendr_wcont X20 X20 X28 X9")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("send_dmlm_ld X8 X21 2")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("movir X23 1")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("yield")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("EFA_gcn_lrrjs_lane_master_empty_partition: addi X2 X30 0")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("evlb X30 26")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("sendr_wcont X30 X2 X28 X28")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("EFA_gcn_lrrjs_empty_part_ret_to_ud_mstr: sendr_wret X31 21 X19 X19 X28")
    gnn_vanilla_kvmsr__lane_master_read_partition_23.writeAction("yield")

    ## gnn_vanilla_kvmsr__lane_master_get_next_return with ID 24
    gnn_vanilla_kvmsr__lane_master_get_next_return_24 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 24)
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("bge X16 X17 EFA_gcn_lrrjs_lane_master_break_iterate_loop")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("bge X8 X9 EFA_gcn_lrrjs_lane_master_break_iterate_loop")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X8 X28 16")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("sendr_wcont X20 X20 X28 X9")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("send_dmlm_ld X8 X21 2")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("yield")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("EFA_gcn_lrrjs_lane_master_break_iterate_loop: movir X23 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X8 X23 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X9 X24 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("yield")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("EFA_gcn_lrrjs_lane_master_iterator_pass_end: subi X16 X16 1")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X8 X23 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X9 X24 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("bgti X16 0 EFA_gcn_lrrjs_lane_master_loop_continue")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("movlr 0(X22) X19 0 8")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("sendr_wret X31 21 X19 X19 X28")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("addi X2 X30 0")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("evlb X30 26")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("sendr_wcont X30 X2 X28 X28")
    gnn_vanilla_kvmsr__lane_master_get_next_return_24.writeAction("EFA_gcn_lrrjs_lane_master_loop_continue: yield")

    ## gnn_vanilla_kvmsr__lane_master_terminate with ID 25
    gnn_vanilla_kvmsr__lane_master_terminate_25 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 25)
    gnn_vanilla_kvmsr__lane_master_terminate_25.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__lane_master_launch_worker with ID 26
    gnn_vanilla_kvmsr__lane_master_launch_worker_26 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 26)
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("EFA_gcn_lrrjs_prepare_launch_workers: evii X30 37 255 5")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("movir X28 -5")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("EFA_gcn_lrrjs_launch_workers: bgei X25 1 EFA_gcn_lrrjs_lane_master_loop_continue")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("sendr_wret X30 22 X28 X28 X29")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("addi X25 X25 1")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("jmp EFA_gcn_lrrjs_launch_workers")
    gnn_vanilla_kvmsr__lane_master_launch_worker_26.writeAction("EFA_gcn_lrrjs_lane_master_loop_continue: yieldt")

    ## gnn_vanilla_kvmsr__init_global_snyc with ID 27
    gnn_vanilla_kvmsr__init_global_snyc_27 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 27)
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("sri X8 X16 11")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("movir X28 512")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("bgt X16 X28 EFA_gcn_lrrjs_max_child_max_node")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("andi X8 X28 2047")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("beqi X28 0 EFA_gcn_lrrjs_max_node")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("jmp EFA_gcn_lrrjs_max_node")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_max_child_max_node: mov_imm2reg X16 512")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_max_node: addi X16 X16 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("sri X8 X17 6")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("movir X28 32")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("bgt X17 X28 EFA_gcn_lrrjs_max_child_max_ud_per_nd")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("andi X8 X28 63")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("beqi X28 0 EFA_gcn_lrrjs_max_ud_per_nd")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("addi X17 X17 1")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("jmp EFA_gcn_lrrjs_max_ud_per_nd")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_max_ud_per_nd: addi X17 X17 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("movir X18 64")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("bgt X8 X18 EFA_gcn_lrrjs_max_ln_per_ud")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("addi X8 X18 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_max_ln_per_ud: addi X18 X18 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("mov_reg2reg X1 X19")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("mov_reg2reg X9 X21")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("evlb X30 28")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("mov_imm2reg X29 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("EFA_gcn_lrrjs_broadcast_loop: lshift X29 X28 11")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("add X0 X28 X28")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("ev X30 X30 X28 X28 8")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("sendr_wret X30 30 X17 X18  X28")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("addi X29 X29 1")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("blt X29 X16 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("mov_imm2reg X20 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("mov_imm2reg X22 0")
    gnn_vanilla_kvmsr__init_global_snyc_27.writeAction("yield")

    ## gnn_vanilla_kvmsr__init_node_sync with ID 28
    gnn_vanilla_kvmsr__init_node_sync_28 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 28)
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("mov_reg2reg X8 X17")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("evlb X30 29")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("mov_imm2reg X29 0")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("EFA_gcn_lrrjs_broadcast_loop: lshift X29 X28 6")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("add X0 X28 X28")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("ev X30 X30 X28 X28 8")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("sendr_wret X30 31 X9 EQT  X28")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("addi X29 X29 1")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("blt X29 X17 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("mov_imm2reg X20 0")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("mov_imm2reg X22 0")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("mov_reg2reg X1 X19")
    gnn_vanilla_kvmsr__init_node_sync_28.writeAction("yield")

    ## gnn_vanilla_kvmsr__ud_accumulate with ID 29
    gnn_vanilla_kvmsr__ud_accumulate_29 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 29)
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("mov_imm2reg X20 0")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("mov_imm2reg X22 0")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("EFA_gcn_lrrjs_accumulate_loop: lshift X20 X17 16")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("add X7 X17 X17")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("addi X17 X17 648")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("move 0(X17) X28 0 8")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("add X28 X22 X22")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("addi X20 X20 1")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("blt X20 X8 EFA_gcn_lrrjs_accumulate_loop")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("sendr_reply X22 X22 X28")
    gnn_vanilla_kvmsr__ud_accumulate_29.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__global_sync_return with ID 30
    gnn_vanilla_kvmsr__global_sync_return_30 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 30)
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("addi X20 X20 1")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("add X8 X22 X22")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("blt X20 X16 EFA_gcn_lrrjs_continue")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("bge X22 X21 EFA_gcn_lrrjs_sync_finish")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("mov_imm2reg X29 0")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("EFA_gcn_lrrjs_broadcast_loop: lshift X29 X28 11")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("add X0 X28 X28")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("ev X30 X30 X28 X28 8")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("sendr_wret X30 30 X17 X18  X28")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("addi X29 X29 1")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("blt X29 X16 EFA_gcn_lrrjs_broadcast_loop")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("mov_imm2reg X20 0")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("mov_imm2reg X22 0")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("EFA_gcn_lrrjs_continue: yield")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("EFA_gcn_lrrjs_sync_finish: movir X30 -1")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("sri X30 X30 1")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("sendr_wcont X19 X30 X22 X22")
    gnn_vanilla_kvmsr__global_sync_return_30.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__node_sync_return with ID 31
    gnn_vanilla_kvmsr__node_sync_return_31 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 31)
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("addi X20 X20 1")
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("add X8 X22 X22")
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("blt X20 X17 EFA_gcn_lrrjs_continue")
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("sendr_wcont X19 EQT X22 X22")
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("yield_terminate")
    gnn_vanilla_kvmsr__node_sync_return_31.writeAction("EFA_gcn_lrrjs_continue: yield")

    ## gnn_vanilla_kvmsr__kv_map_emit with ID 32
    gnn_vanilla_kvmsr__kv_map_emit_32 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 32)
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("addi X7 X25 640")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("movlr 40(X25) X23 0 8")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("movlr 56(X25) X26 0 8")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("movir X24 0")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("hash X8 X24")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("and X24 X23 X24")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("add X24 X26 X24")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("evi X2 X30 255 4")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("evlb X30 35")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("evi X2 X27 255 4")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("evlb X27 36")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("ev X30  X30  X24 X24 8")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("sendops_wcont X30 X27 X8 3")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("move 0(X25) X29  0 8")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("addi X29 X29 1")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("move X29 0(X25) 0 8")
    gnn_vanilla_kvmsr__kv_map_emit_32.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__kv_reduce_emit with ID 33
    gnn_vanilla_kvmsr__kv_reduce_emit_33 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 33)

    ## gnn_vanilla_kvmsr__kv_map_return with ID 34
    gnn_vanilla_kvmsr__kv_map_return_34 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 34)
    gnn_vanilla_kvmsr__kv_map_return_34.writeAction("addi X7 X16 656")
    gnn_vanilla_kvmsr__kv_map_return_34.writeAction("move 0(X16) X29 0 8")
    gnn_vanilla_kvmsr__kv_map_return_34.writeAction("sendops_wcont X29 X2 X8 2")
    gnn_vanilla_kvmsr__kv_map_return_34.writeAction("yieldt")

    ## gnn_vanilla_kvmsr__init_reduce_thread with ID 35
    gnn_vanilla_kvmsr__init_reduce_thread_35 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 35)
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("addi X7 X20 640")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("movlr 24(X20) X28 0 8")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("move 32(X20) X29 0 8")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("bge X28 X29 EFA_gcn_lrrjs_push_back_to_queue")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("addi X28 X28 1")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("move X28  24(X20) 0 8")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("addi X2 X30 0")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("evlb X30 54")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("sendops_wret X30 36 X8 3 X28")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("yield")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("EFA_gcn_lrrjs_push_back_to_queue: ev_update_1 EQT X30 255 4")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("sendops_wcont X30 X1 X8 3")
    gnn_vanilla_kvmsr__init_reduce_thread_35.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__kv_reduce_return with ID 36
    gnn_vanilla_kvmsr__kv_reduce_return_36 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 36)
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("addi X7 X20 640")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("move 8(X20) X28 0 8")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("addi X28 X28 1")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("move X28 8(X20) 0 8")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("move 24(X20) X28 0 8")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("subi X28 X28 1")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("move X28  24(X20) 0 8")
    gnn_vanilla_kvmsr__kv_reduce_return_36.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__worker_init with ID 37
    gnn_vanilla_kvmsr__worker_init_37 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 37)
    gnn_vanilla_kvmsr__worker_init_37.writeAction("addi X1 X31 0")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("movir UDPR_5 -1")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("movir UDPR_0 0")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("addi X0 UDPR_6 0")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("andi X0 X28 63")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("sli X28 X28 16")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("sub X7 X28 UDPR_3")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("movir UDPR_7 792")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("add UDPR_7 UDPR_3 UDPR_7")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("movlr 0(UDPR_7) UDPR_2 0 8")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("addi X2 X30 0")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("evlb X30 38")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("movir X28 -6")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("sendr_wcont X30 X2 X28 X28")
    gnn_vanilla_kvmsr__worker_init_37.writeAction("yield")

    ## gnn_vanilla_kvmsr__worker_work with ID 38
    gnn_vanilla_kvmsr__worker_work_38 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 38)
    gnn_vanilla_kvmsr__worker_work_38.writeAction("EFA_gcn_lrrjs_claim_work: bgei UDPR_5 0 EFA_gcn_lrrjs_claim_remote_work")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("addi X2 X30 0")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("evlb X30 39")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("sendr_wcont X30 X2 X8 X9")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("yield")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("EFA_gcn_lrrjs_claim_remote_work: addi X2 X30 0")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("evlb X30 40")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("sendr_wcont X30 X2 X8 X9")
    gnn_vanilla_kvmsr__worker_work_38.writeAction("yield")

    ## gnn_vanilla_kvmsr__worker_claim_local with ID 39
    gnn_vanilla_kvmsr__worker_claim_local_39 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 39)
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("movir UDPR_7 784")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("add UDPR_3 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("EFA_gcn_lrrjs_claiming_local_maps: movlr 0(UDPR_7) X28 0 8")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("beq X28 UDPR_2 EFA_gcn_lrrjs_local_maps_finished")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("addi X28 X29 16")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("cswp UDPR_7 UDPR_8 X28 X29")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("beq X28 UDPR_8 EFA_gcn_lrrjs_claimed_local_maps")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("jmp EFA_gcn_lrrjs_claiming_local_maps")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("EFA_gcn_lrrjs_claimed_local_maps: evii X30 46 255 5")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("movir UDPR_7 776")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("movlr 0(UDPR_7) X29 0 8")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("sendr_wcont X30 X2 X28 X29")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("yield")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("EFA_gcn_lrrjs_local_maps_finished: movir UDPR_5 0")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("EFA_gcn_lrrjs_claim_remote_work: addi X2 X30 0")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("evlb X30 40")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("sendr_wcont X30 X2 X28 X28")
    gnn_vanilla_kvmsr__worker_claim_local_39.writeAction("EFA_gcn_lrrjs_claiming_finished: yield")

    ## gnn_vanilla_kvmsr__worker_claim_remote with ID 40
    gnn_vanilla_kvmsr__worker_claim_remote_40 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 40)
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("EFA_gcn_lrrjs_claim_work: movir UDPR_7 768")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movlr 0(UDPR_7) X28 0 8")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("beqi X28 1 EFA_gcn_lrrjs_worker_finished")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("beqi UDPR_0 1 EFA_gcn_lrrjs_send_claim_msg")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movir UDPR_7 640")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movlr 56(UDPR_7) UDPR_11 0 8")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("addi UDPR_6 UDPR_6 64")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movlr 40(UDPR_7) X29 0 8")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("addi X29 X29 1")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("mod UDPR_6 X29 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("bne X0 UDPR_6 EFA_gcn_lrrjs_send_claim_msg")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("bgei UDPR_5 3 EFA_gcn_lrrjs_worker_finished")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("bgei UDPR_5 2 EFA_gcn_lrrjs_early_finished")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("addi UDPR_6 UDPR_6 64")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("mod UDPR_6 X29 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("EFA_gcn_lrrjs_send_claim_msg: movir UDPR_0 0")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("evii X30 43 255 5")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("ev X30 X30 UDPR_6 UDPR_6 8")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movir X28 1")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("sli X28 X28 59")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("or X28 X30 X30")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movir X29 1")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("movir UDPR_4 1")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("sendr_wret X30 38 X29 X29 X28")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("yield")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("EFA_gcn_lrrjs_early_finished: yieldt")
    gnn_vanilla_kvmsr__worker_claim_remote_40.writeAction("EFA_gcn_lrrjs_worker_finished: yieldt")

    ## gnn_vanilla_kvmsr__worker_helper with ID 41
    gnn_vanilla_kvmsr__worker_helper_41 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 41)
    gnn_vanilla_kvmsr__worker_helper_41.writeAction("yield")

    ## gnn_vanilla_kvmsr__worker_claimed_map with ID 42
    gnn_vanilla_kvmsr__worker_claimed_map_42 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 42)
    gnn_vanilla_kvmsr__worker_claimed_map_42.writeAction("addi X1 UDPR_9 0")
    gnn_vanilla_kvmsr__worker_claimed_map_42.writeAction("movir UDPR_0 1")
    gnn_vanilla_kvmsr__worker_claimed_map_42.writeAction("EFA_gcn_lrrjs_launch_mappers: evii X30 46 255 5")
    gnn_vanilla_kvmsr__worker_claimed_map_42.writeAction("sendr_wret X30 38 X9 X10 X28")
    gnn_vanilla_kvmsr__worker_claimed_map_42.writeAction("yield")

    ## gnn_vanilla_kvmsr__receiver_claim_work with ID 43
    gnn_vanilla_kvmsr__receiver_claim_work_43 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 43)
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("andi X0 X28 63")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("sli X28 X28 16")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("sub X7 X28 UDPR_4")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movir UDPR_7 784")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("add UDPR_4 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movlr 0(UDPR_7) X28 0 8")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movlr 8(UDPR_7) UDPR_9 0 8")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("EFA_gcn_lrrjs_claim_maps: beq X28 UDPR_9 EFA_gcn_lrrjs_local_work_resolved")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("addi X28 X29 16")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("cswp UDPR_7 UDPR_5 X28 X29")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("beq X28 UDPR_5 EFA_gcn_lrrjs_claimed_maps")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movlr 0(UDPR_7) X28 0 8")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("jmp EFA_gcn_lrrjs_claim_maps")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("EFA_gcn_lrrjs_claimed_maps: evii UDPR_15 45 255 5")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("addi X1 X30 0")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("evlb X30 42")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movir UDPR_7 776")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movlr 0(UDPR_7) X29 0 8")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movir X28 -3")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("sendr3_wcont X30 UDPR_15 X28 UDPR_5 X29")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("yieldt")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("EFA_gcn_lrrjs_check_terminate_bit: movir UDPR_7 768")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("movlr 0(UDPR_7) X28 0 8")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("blti X28 0 EFA_gcn_lrrjs_local_work_resolved")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("EFA_gcn_lrrjs_local_work_resolved: movir X28 -2")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("sendr_wcont X1 X2 X28 X29")
    gnn_vanilla_kvmsr__receiver_claim_work_43.writeAction("EFA_gcn_lrrjs_receiver_claim_work_end: yieldt")

    ## gnn_vanilla_kvmsr__receiver_set_terminate_bit with ID 44
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 44)
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("movir UDPR_7 768")
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("add X7 UDPR_7 UDPR_7")
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("movrl X8 0(UDPR_7) 0 8")
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("bnei X8 1 EFA_gcn_lrrjs_terminate")
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("sendr_reply X28 X28 X28")
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_44.writeAction("EFA_gcn_lrrjs_terminate: yieldt")

    ## gnn_vanilla_kvmsr__receiver_set_terminate_bit_ret with ID 45
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_ret_45 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 45)
    gnn_vanilla_kvmsr__receiver_set_terminate_bit_ret_45.writeAction("yieldt")

    ## gnn_vanilla_kvmsr__mapper_control_init with ID 46
    gnn_vanilla_kvmsr__mapper_control_init_46 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 46)
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("addi X1 X31 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("addi X9 X18 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("send_dmlm_ld_wret X8 47 2 X28")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("movir X16 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("movir X17 64")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("movir X19 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("movir X22 640")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("add X7 X22 X22")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("addi X2 X28 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("evlb X28 49")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("movir X29 656")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("add X7 X29 X29")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("move X28 0(X29) 0 8")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("addi X2 X20 0")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("evlb X20 48")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("evi X2 X21 255 4")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("evlb X21 53")
    gnn_vanilla_kvmsr__mapper_control_init_46.writeAction("yield")

    ## gnn_vanilla_kvmsr__mapper_control_read_partition with ID 47
    gnn_vanilla_kvmsr__mapper_control_read_partition_47 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 47)
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("bge X8 X9 EFA_gcn_lrrjs_lane_master_empty_partition")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("addi X8 X28 16")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("sendr_wcont X20 X20 X28 X9")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("send_dmlm_ld X8 X21 2")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("movir X23 1")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("yield")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("EFA_gcn_lrrjs_lane_master_empty_partition: movir X29 -6")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("sendr_wcont X18 X2 X19 X19")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("sendr_wcont X31 X2 X29 X19")
    gnn_vanilla_kvmsr__mapper_control_read_partition_47.writeAction("yieldt")

    ## gnn_vanilla_kvmsr__mapper_control_get_next_return with ID 48
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 48)
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("bge X16 X17 EFA_gcn_lrrjs_mapper_control_break_iterate_loop")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("bge X8 X9 EFA_gcn_lrrjs_mapper_control_break_iterate_loop")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X8 X28 16")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("sendr_wcont X20 X20 X28 X9")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("send_dmlm_ld X8 X21 2")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("yield")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("EFA_gcn_lrrjs_mapper_control_break_iterate_loop: movir X23 0")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X8 X23 0")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X9 X24 0")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("yield")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("EFA_gcn_lrrjs_mapper_control_iterator_pass_end: subi X16 X16 1")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X8 X23 0")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("addi X9 X24 0")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("bgti X16 0 EFA_gcn_lrrjs_lane_master_loop_continue")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("movlr 0(X22) X19 0 8")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("movir X29 -6")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("sendr_wcont X31 X2 X29 X19")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("sendr_wcont X18 X2 X29 X19")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("yieldt")
    gnn_vanilla_kvmsr__mapper_control_get_next_return_48.writeAction("EFA_gcn_lrrjs_lane_master_loop_continue: yield")

    ## gnn_vanilla_kvmsr__mapper_control_loop with ID 49
    gnn_vanilla_kvmsr__mapper_control_loop_49 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 49)
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("subi X16 X16 1")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("beqi X23 1 EFA_gcn_lrrjs_mapper_control_loop_continue")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("bge X23 X24 EFA_gcn_lrrjs_mapper_control_reach_end")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("addi X23 X28 16")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("sendr_wcont X20 X20 X28 X24")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("send_dmlm_ld X23 X21 2")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("addi X16 X16 1")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("movir X23 1")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("yield")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("EFA_gcn_lrrjs_mapper_control_reach_end: bgti X16 0 EFA_gcn_lrrjs_mapper_control_loop_continue")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("movlr 0(X22) X19 0 8")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("movir X29 -6")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("sendr_wcont X18 X2 X19 X19")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("sendr_wcont X31 X2 X29 X19")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("mov_imm2reg X19 0")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("movrl X19 0(X22) 0 8")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("yieldt")
    gnn_vanilla_kvmsr__mapper_control_loop_49.writeAction("EFA_gcn_lrrjs_mapper_control_loop_continue: yield")

    ## gnn_vanilla_kvmsr__lane_remote_mapper_finished with ID 50
    gnn_vanilla_kvmsr__lane_remote_mapper_finished_50 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 50)
    gnn_vanilla_kvmsr__lane_remote_mapper_finished_50.writeAction("yieldt")

    ## gnn_vanilla_master__gnn_start with ID 51
    gnn_vanilla_master__gnn_start_51 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 51)
    gnn_vanilla_master__gnn_start_51.writeAction("EFA_gcn_lrrjs_entry: perflog 1 1 'GNN started'")
    gnn_vanilla_master__gnn_start_51.writeAction("print 'GNN started'")
    gnn_vanilla_master__gnn_start_51.writeAction("addi X7 X16 8")
    gnn_vanilla_master__gnn_start_51.writeAction("addi X7 X17 256")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X8 0(X17) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X9 8(X17) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X13 16(X17) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X10 0(X16) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X11 8(X16) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X12 16(X16) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X17 24(X16) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("addi X17 X19 16")
    gnn_vanilla_master__gnn_start_51.writeAction("movrl X19 32(X16) 0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("movir X18 0")
    gnn_vanilla_master__gnn_start_51.writeAction("evlb X18 0")
    gnn_vanilla_master__gnn_start_51.writeAction("evi X18 X18 255 4")
    gnn_vanilla_master__gnn_start_51.writeAction("ev X18 X18 X0 X0 8")
    gnn_vanilla_master__gnn_start_51.writeAction("evi X2 X19 52 1")
    gnn_vanilla_master__gnn_start_51.writeAction("send_wcont X18 X19 X16 5")
    gnn_vanilla_master__gnn_start_51.writeAction("yield")

    ## gnn_vanilla_master__gnn_term with ID 52
    gnn_vanilla_master__gnn_term_52 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 52)
    gnn_vanilla_master__gnn_term_52.writeAction("EFA_gcn_lrrjs_entry: movir X17 65528")
    gnn_vanilla_master__gnn_term_52.writeAction("add X7 X17 X16")
    gnn_vanilla_master__gnn_term_52.writeAction("perflog 1 1 'GNN finished'")
    gnn_vanilla_master__gnn_term_52.writeAction("print 'GNN finished'")
    gnn_vanilla_master__gnn_term_52.writeAction("movir X18 1")
    gnn_vanilla_master__gnn_term_52.writeAction("movrl X18 0(X16) 0 8")
    gnn_vanilla_master__gnn_term_52.writeAction("yield_terminate")

    ## gnn_vanilla_kvmsr__kv_map with ID 53
    gnn_vanilla_kvmsr__kv_map_53 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 53)
    gnn_vanilla_kvmsr__kv_map_53.writeAction("EFA_gcn_lrrjs_entry: addi X7 X17 8")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("movrl X9 0(X17) 0 8")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("movrl X8 8(X17) 0 8")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("movir X19 0")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("movrl X19 16(X17) 0 8")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("evlb X18 32")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("evi X18 X18 255 4")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("ev X18 X18 X0 X0 8")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("send_wcont X18 X1 X17 3")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("evi X2 X18 34 1")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("sendr_wcont X18 X1 X8 X9")
    gnn_vanilla_kvmsr__kv_map_53.writeAction("yield")

    ## gnn_vanilla_kvmsr__kv_reduce with ID 54
    gnn_vanilla_kvmsr__kv_reduce_54 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 54)
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("EFA_gcn_lrrjs_entry: movir X16 2")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("evi X2 X17 55 1")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("sendr_wcont X17 X1 X18 X18")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("sendr_wcont X17 X1 X18 X18")
    gnn_vanilla_kvmsr__kv_reduce_54.writeAction("yield")

    ## gnn_vanilla_kvmsr__kv_reduce_compute with ID 55
    gnn_vanilla_kvmsr__kv_reduce_compute_55 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 55)
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs_entry: subi X16 X16 1")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("bleiu X16 0 EFA_gcn_lrrjs___if_kv_reduce_compute_2_post")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs___if_kv_reduce_compute_0_true: yield")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs___if_kv_reduce_compute_2_post: movir X17 0")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("movir X18 1024")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("movir X17 0")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs___for_kv_reduce_compute_3_condition: bleu X18 X17 EFA_gcn_lrrjs___for_kv_reduce_compute_5_post")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs___for_kv_reduce_compute_4_body: addi X17 X17 0")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("addi X17 X17 1")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("jmp EFA_gcn_lrrjs___for_kv_reduce_compute_3_condition")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("EFA_gcn_lrrjs___for_kv_reduce_compute_5_post: movir X16 2")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("evi X2 X19 56 1")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("movir X20 0")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("sendr_wcont X19 X1 X20 X20")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("movir X20 0")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("sendr_wcont X19 X1 X20 X20")
    gnn_vanilla_kvmsr__kv_reduce_compute_55.writeAction("yield")

    ## gnn_vanilla_kvmsr__kv_reduce_write_back with ID 56
    gnn_vanilla_kvmsr__kv_reduce_write_back_56 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 56)
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("EFA_gcn_lrrjs_entry: subi X16 X16 1")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("bleiu X16 0 EFA_gcn_lrrjs___if_kv_reduce_write_back_2_post")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("EFA_gcn_lrrjs___if_kv_reduce_write_back_0_true: yield")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("EFA_gcn_lrrjs___if_kv_reduce_write_back_2_post: evi X2 X17 36 1")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("movir X18 0")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("sendr_wcont X17 X1 X18 X18")
    gnn_vanilla_kvmsr__kv_reduce_write_back_56.writeAction("yield")

    ## Broadcast__broadcast_global with ID 57
    Broadcast__broadcast_global_57 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 57)
    Broadcast__broadcast_global_57.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global_57.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global_57.writeAction("movir X16 512")
    Broadcast__broadcast_global_57.writeAction("bgt X25 X16 GenLinkableBroadcast_rxtdg_max_child_modular_eq_zero")
    Broadcast__broadcast_global_57.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global_57.writeAction("beqi X16 0 GenLinkableBroadcast_rxtdg_modular_eq_zero")
    Broadcast__broadcast_global_57.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global_57.writeAction("jmp GenLinkableBroadcast_rxtdg_modular_eq_zero")
    Broadcast__broadcast_global_57.writeAction("GenLinkableBroadcast_rxtdg_max_child_modular_eq_zero: mov_imm2reg X25 512")
    Broadcast__broadcast_global_57.writeAction("GenLinkableBroadcast_rxtdg_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global_57.writeAction("evlb X28 58")
    Broadcast__broadcast_global_57.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global_57.writeAction("GenLinkableBroadcast_rxtdg_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global_57.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global_57.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global_57.writeAction("sendops_wret X28 62 X8 8 X16")
    Broadcast__broadcast_global_57.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global_57.writeAction("blt X17 X25 GenLinkableBroadcast_rxtdg_broadcast_loop")
    Broadcast__broadcast_global_57.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global_57.writeAction("yield")

    ## Broadcast__broadcast_node with ID 58
    Broadcast__broadcast_node_58 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 58)
    Broadcast__broadcast_node_58.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node_58.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node_58.writeAction("movir X16 32")
    Broadcast__broadcast_node_58.writeAction("bgt X25 X16 GenLinkableBroadcast_rxtdg_max_child_modular_eq_zero")
    Broadcast__broadcast_node_58.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node_58.writeAction("beqi X16 0 GenLinkableBroadcast_rxtdg_modular_eq_zero")
    Broadcast__broadcast_node_58.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node_58.writeAction("jmp GenLinkableBroadcast_rxtdg_modular_eq_zero")
    Broadcast__broadcast_node_58.writeAction("GenLinkableBroadcast_rxtdg_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node_58.writeAction("GenLinkableBroadcast_rxtdg_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node_58.writeAction("evlb X28 59")
    Broadcast__broadcast_node_58.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node_58.writeAction("GenLinkableBroadcast_rxtdg_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node_58.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node_58.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node_58.writeAction("sendops_wret X28 61 X8 8 X16")
    Broadcast__broadcast_node_58.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node_58.writeAction("blt X17 X25 GenLinkableBroadcast_rxtdg_broadcast_loop")
    Broadcast__broadcast_node_58.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node_58.writeAction("yield")

    ## Broadcast__broadcast_ud with ID 59
    Broadcast__broadcast_ud_59 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 59)
    Broadcast__broadcast_ud_59.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud_59.writeAction("movir X25 64")
    Broadcast__broadcast_ud_59.writeAction("bgt X8 X25 GenLinkableBroadcast_rxtdg_modular_eq_zero")
    Broadcast__broadcast_ud_59.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud_59.writeAction("GenLinkableBroadcast_rxtdg_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud_59.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud_59.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud_59.writeAction("GenLinkableBroadcast_rxtdg_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud_59.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud_59.writeAction("sendops_wret X28 60 X10 6 X16")
    Broadcast__broadcast_ud_59.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud_59.writeAction("blt X17 X25 GenLinkableBroadcast_rxtdg_broadcast_loop")
    Broadcast__broadcast_ud_59.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud_59.writeAction("yield")

    ## Broadcast__broadcast_ud_fin with ID 60
    Broadcast__broadcast_ud_fin_60 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 60)
    Broadcast__broadcast_ud_fin_60.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin_60.writeAction("blt X26 X25 GenLinkableBroadcast_rxtdg_continue")
    Broadcast__broadcast_ud_fin_60.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_ud_fin_60.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin_60.writeAction("GenLinkableBroadcast_rxtdg_continue: yield")

    ## Broadcast__broadcast_node_fin with ID 61
    Broadcast__broadcast_node_fin_61 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 61)
    Broadcast__broadcast_node_fin_61.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin_61.writeAction("blt X26 X25 GenLinkableBroadcast_rxtdg_continue")
    Broadcast__broadcast_node_fin_61.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin_61.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin_61.writeAction("GenLinkableBroadcast_rxtdg_continue: yield")

    ## Broadcast__broadcast_global_fin with ID 62
    Broadcast__broadcast_global_fin_62 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 62)
    Broadcast__broadcast_global_fin_62.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin_62.writeAction("beq X26 X25 GenLinkableBroadcast_rxtdg_global_bcst_finish")
    Broadcast__broadcast_global_fin_62.writeAction("yield")
    Broadcast__broadcast_global_fin_62.writeAction("GenLinkableBroadcast_rxtdg_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin_62.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad with ID 63
    Broadcast__broadcast_value_to_scratchpad_63 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 63)
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad_63.writeAction("yieldt")



def main():
    efa = EFA([])
    efa.code_level = 'machine'
    efaProgram_gcn_udkvmsr_exe_rh_nlbstrm_on(efa)
    return efa