from EFA_v2 import EFA, State, Transition

def efaProgram_js_udkvmsr_exe_nlb(efa):

    ## init_null_state with ID 0
    init_null_state_0 = State()
    efa.add_state(init_null_state_0)
    efa.add_initId(init_null_state_0.state_id)

    ## lm_allocator__spmalloc with ID 0
    lm_allocator__spmalloc_0 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 0)
    lm_allocator__spmalloc_0.writeAction("mov_reg2reg X1 UDPR_4")
    lm_allocator__spmalloc_0.writeAction("addi X7 UDPR_15 0")
    lm_allocator__spmalloc_0.writeAction("movir UDPR_13 65536")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_init: add X7 UDPR_13 UDPR_2")
    lm_allocator__spmalloc_0.writeAction("movir UDPR_1 21464")
    lm_allocator__spmalloc_0.writeAction("add UDPR_15 UDPR_1 UDPR_1")
    lm_allocator__spmalloc_0.writeAction("move 0(UDPR_1) UDPR_14 0 8")
    lm_allocator__spmalloc_0.writeAction("add UDPR_14 UDPR_15 UDPR_1")
    lm_allocator__spmalloc_0.writeAction("move 0(UDPR_1) UDPR_13 0 8")
    lm_allocator__spmalloc_0.writeAction("bnei UDPR_13 0 EFA_js_soxqv_allocate_block")
    lm_allocator__spmalloc_0.writeAction("sub UDPR_2 UDPR_1 UDPR_14")
    lm_allocator__spmalloc_0.writeAction("lshift UDPR_14 UDPR_14 1")
    lm_allocator__spmalloc_0.writeAction("move UDPR_14 0(UDPR_1) 0 8")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_allocate_block: addi X8 UDPR_0 0")
    lm_allocator__spmalloc_0.writeAction("beqi UDPR_0 0 EFA_js_soxqv_no_block_available")
    lm_allocator__spmalloc_0.writeAction("addi UDPR_0 UDPR_0 1")
    lm_allocator__spmalloc_0.writeAction("lshift UDPR_0 UDPR_0 3")
    lm_allocator__spmalloc_0.writeAction("mov_reg2reg UDPR_1 UDPR_3")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_find_free_block: move 0(UDPR_3) UDPR_13 0 8")
    lm_allocator__spmalloc_0.writeAction("rshift UDPR_13 UDPR_14 1")
    lm_allocator__spmalloc_0.writeAction("andi UDPR_13 UDPR_12 1")
    lm_allocator__spmalloc_0.writeAction("blt UDPR_14 UDPR_0 EFA_js_soxqv_continue_find_block_loop")
    lm_allocator__spmalloc_0.writeAction("beqi UDPR_12 0 EFA_js_soxqv_found_free_block")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_continue_find_block_loop: add UDPR_14 UDPR_3 UDPR_11")
    lm_allocator__spmalloc_0.writeAction("bge UDPR_11 UDPR_2 EFA_js_soxqv_no_block_available")
    lm_allocator__spmalloc_0.writeAction("beqi UDPR_12 1 EFA_js_soxqv_do_not_coalesce")
    lm_allocator__spmalloc_0.writeAction("move 0(UDPR_11) UDPR_10 0 8")
    lm_allocator__spmalloc_0.writeAction("andi UDPR_10 UDPR_12 1")
    lm_allocator__spmalloc_0.writeAction("beqi UDPR_12 1 EFA_js_soxqv_do_not_coalesce")
    lm_allocator__spmalloc_0.writeAction("rshift UDPR_10 UDPR_10 1")
    lm_allocator__spmalloc_0.writeAction("add UDPR_10 UDPR_14 UDPR_14")
    lm_allocator__spmalloc_0.writeAction("lshift UDPR_14 UDPR_14 1")
    lm_allocator__spmalloc_0.writeAction("move UDPR_14 0(UDPR_3) 0 8")
    lm_allocator__spmalloc_0.writeAction("jmp EFA_js_soxqv_find_free_block")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_do_not_coalesce: mov_reg2reg UDPR_11 UDPR_3")
    lm_allocator__spmalloc_0.writeAction("jmp EFA_js_soxqv_find_free_block")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_found_free_block: sub UDPR_14 UDPR_0 UDPR_11")
    lm_allocator__spmalloc_0.writeAction("bltiu UDPR_11 16 EFA_js_soxqv_post_allocation_header_assignment")
    lm_allocator__spmalloc_0.writeAction("mov_reg2reg UDPR_0 UDPR_14")
    lm_allocator__spmalloc_0.writeAction("lshift UDPR_11 UDPR_11 1")
    lm_allocator__spmalloc_0.writeAction("add UDPR_3 UDPR_14 UDPR_12")
    lm_allocator__spmalloc_0.writeAction("move UDPR_11 0(UDPR_12) 0 8")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_post_allocation_header_assignment: lshift_add_imm UDPR_14 UDPR_14 1 1")
    lm_allocator__spmalloc_0.writeAction("move UDPR_14 0(UDPR_3) 0 8")
    lm_allocator__spmalloc_0.writeAction("addi UDPR_3 UDPR_3 8")
    lm_allocator__spmalloc_0.writeAction("jmp EFA_js_soxqv_write_results")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_no_block_available: mov_imm2reg UDPR_3 0")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_write_results: mov_imm2reg UDPR_14 0")
    lm_allocator__spmalloc_0.writeAction("beqi UDPR_3 0 EFA_js_soxqv_reply")
    lm_allocator__spmalloc_0.writeAction("mov_imm2reg UDPR_14 1")
    lm_allocator__spmalloc_0.writeAction("EFA_js_soxqv_reply: sendr_wcont UDPR_4 UDPR_4 UDPR_3 UDPR_14 UDPR_14")
    lm_allocator__spmalloc_0.writeAction("yield_terminate")

    ## lm_allocator__spfree with ID 1
    lm_allocator__spfree_1 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 1)
    lm_allocator__spfree_1.writeAction("mov_reg2reg X1 UDPR_2")
    lm_allocator__spfree_1.writeAction("addi X8 UDPR_4 0")
    lm_allocator__spfree_1.writeAction("subi UDPR_4 UDPR_4 8")
    lm_allocator__spfree_1.writeAction("move 0(UDPR_4) UDPR_3 0 8")
    lm_allocator__spfree_1.writeAction("movir UDPR_1 65535")
    lm_allocator__spfree_1.writeAction("sli UDPR_1 UDPR_1 16")
    lm_allocator__spfree_1.writeAction("ori UDPR_1 UDPR_1 65534")
    lm_allocator__spfree_1.writeAction("and UDPR_3 UDPR_1 UDPR_3")
    lm_allocator__spfree_1.writeAction("move UDPR_3 0(UDPR_4) 0 8")
    lm_allocator__spfree_1.writeAction("mov_imm2reg UDPR_1 1")
    lm_allocator__spfree_1.writeAction("sendr_wcont UDPR_2 UDPR_2 UDPR_1 UDPR_1 UDPR_1")
    lm_allocator__spfree_1.writeAction("yield_terminate")

    ## js_broadcast__broadcast_global with ID 2
    js_broadcast__broadcast_global_2 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 2)
    js_broadcast__broadcast_global_2.writeAction("addi X8 X27 0")
    js_broadcast__broadcast_global_2.writeAction("sri X27 X25 11")
    js_broadcast__broadcast_global_2.writeAction("movir X16 512")
    js_broadcast__broadcast_global_2.writeAction("bgt X25 X16 EFA_js_soxqv_max_child_modular_eq_zero")
    js_broadcast__broadcast_global_2.writeAction("andi X27 X16 2047")
    js_broadcast__broadcast_global_2.writeAction("beqi X16 0 EFA_js_soxqv_modular_eq_zero")
    js_broadcast__broadcast_global_2.writeAction("addi X25 X25 1")
    js_broadcast__broadcast_global_2.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js_broadcast__broadcast_global_2.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 512")
    js_broadcast__broadcast_global_2.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js_broadcast__broadcast_global_2.writeAction("evlb X28 3")
    js_broadcast__broadcast_global_2.writeAction("mov_imm2reg X17 0")
    js_broadcast__broadcast_global_2.writeAction("EFA_js_soxqv_broadcast_loop: lshift X17 X16 11")
    js_broadcast__broadcast_global_2.writeAction("add X0 X16 X16")
    js_broadcast__broadcast_global_2.writeAction("ev X28 X28 X16 X16 8")
    js_broadcast__broadcast_global_2.writeAction("sendops_wret X28 7 X8 8 X16")
    js_broadcast__broadcast_global_2.writeAction("addi X17 X17 1")
    js_broadcast__broadcast_global_2.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js_broadcast__broadcast_global_2.writeAction("mov_imm2reg X26 0")
    js_broadcast__broadcast_global_2.writeAction("yield")

    ## js_broadcast__broadcast_node with ID 3
    js_broadcast__broadcast_node_3 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 3)
    js_broadcast__broadcast_node_3.writeAction("addi X1 X29 0")
    js_broadcast__broadcast_node_3.writeAction("sri X8 X25 6")
    js_broadcast__broadcast_node_3.writeAction("movir X16 32")
    js_broadcast__broadcast_node_3.writeAction("bgt X25 X16 EFA_js_soxqv_max_child_modular_eq_zero")
    js_broadcast__broadcast_node_3.writeAction("andi X8 X16 63")
    js_broadcast__broadcast_node_3.writeAction("beqi X16 0 EFA_js_soxqv_modular_eq_zero")
    js_broadcast__broadcast_node_3.writeAction("addi X25 X25 1")
    js_broadcast__broadcast_node_3.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js_broadcast__broadcast_node_3.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 32")
    js_broadcast__broadcast_node_3.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js_broadcast__broadcast_node_3.writeAction("evlb X28 4")
    js_broadcast__broadcast_node_3.writeAction("mov_imm2reg X17 0")
    js_broadcast__broadcast_node_3.writeAction("EFA_js_soxqv_broadcast_loop: lshift X17 X16 6")
    js_broadcast__broadcast_node_3.writeAction("add X0 X16 X16")
    js_broadcast__broadcast_node_3.writeAction("ev X28 X28 X16 X16 8")
    js_broadcast__broadcast_node_3.writeAction("sendops_wret X28 6 X8 8 X16")
    js_broadcast__broadcast_node_3.writeAction("addi X17 X17 1")
    js_broadcast__broadcast_node_3.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js_broadcast__broadcast_node_3.writeAction("mov_imm2reg X26 0")
    js_broadcast__broadcast_node_3.writeAction("yield")

    ## js_broadcast__broadcast_ud with ID 4
    js_broadcast__broadcast_ud_4 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 4)
    js_broadcast__broadcast_ud_4.writeAction("addi X1 X29 0")
    js_broadcast__broadcast_ud_4.writeAction("movir X25 64")
    js_broadcast__broadcast_ud_4.writeAction("bgt X8 X25 EFA_js_soxqv_modular_eq_zero")
    js_broadcast__broadcast_ud_4.writeAction("addi X8 X25 0")
    js_broadcast__broadcast_ud_4.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js_broadcast__broadcast_ud_4.writeAction("ev X28 X28 X9 X9 1")
    js_broadcast__broadcast_ud_4.writeAction("mov_imm2reg X17 0")
    js_broadcast__broadcast_ud_4.writeAction("EFA_js_soxqv_broadcast_loop: add X0 X17 X16")
    js_broadcast__broadcast_ud_4.writeAction("ev X28 X28 X16 X16 8")
    js_broadcast__broadcast_ud_4.writeAction("sendops_wret X28 5 X10 6 X16")
    js_broadcast__broadcast_ud_4.writeAction("addi X17 X17 1")
    js_broadcast__broadcast_ud_4.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js_broadcast__broadcast_ud_4.writeAction("mov_imm2reg X26 0")
    js_broadcast__broadcast_ud_4.writeAction("yield")

    ## js_broadcast__broadcast_ud_fin with ID 5
    js_broadcast__broadcast_ud_fin_5 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 5)
    js_broadcast__broadcast_ud_fin_5.writeAction("addi X26 X26 1")
    js_broadcast__broadcast_ud_fin_5.writeAction("blt X26 X25 EFA_js_soxqv_continue")
    js_broadcast__broadcast_ud_fin_5.writeAction("sendr_reply X0 X2 X16")
    js_broadcast__broadcast_ud_fin_5.writeAction("yield_terminate")
    js_broadcast__broadcast_ud_fin_5.writeAction("EFA_js_soxqv_continue: yield")

    ## js_broadcast__broadcast_node_fin with ID 6
    js_broadcast__broadcast_node_fin_6 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 6)
    js_broadcast__broadcast_node_fin_6.writeAction("addi X26 X26 1")
    js_broadcast__broadcast_node_fin_6.writeAction("blt X26 X25 EFA_js_soxqv_continue")
    js_broadcast__broadcast_node_fin_6.writeAction("sendr_reply X0 X2 X16")
    js_broadcast__broadcast_node_fin_6.writeAction("yield_terminate")
    js_broadcast__broadcast_node_fin_6.writeAction("EFA_js_soxqv_continue: yield")

    ## js_broadcast__broadcast_global_fin with ID 7
    js_broadcast__broadcast_global_fin_7 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 7)
    js_broadcast__broadcast_global_fin_7.writeAction("addi X26 X26 1")
    js_broadcast__broadcast_global_fin_7.writeAction("beq X26 X25 EFA_js_soxqv_global_bcst_finish")
    js_broadcast__broadcast_global_fin_7.writeAction("yield")
    js_broadcast__broadcast_global_fin_7.writeAction("EFA_js_soxqv_global_bcst_finish: sendr_reply X0 X2 X16")
    js_broadcast__broadcast_global_fin_7.writeAction("yieldt")

    ## js_broadcast__broadcast_value_to_scratchpad with ID 8
    js_broadcast__broadcast_value_to_scratchpad_8 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 8)
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("sri X8 X16 32")
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("add X7 X16 X16")
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("andi X8 X17 15")
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("bcpyol X9 X16 X17")
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("sendr_reply X1 X2 X16")
    js_broadcast__broadcast_value_to_scratchpad_8.writeAction("yieldt")

    ## js__map_shuffle_reduce with ID 9
    js__map_shuffle_reduce_9 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 9)
    js__map_shuffle_reduce_9.writeAction("addi X7 X20 688")
    js__map_shuffle_reduce_9.writeAction("addi X1 X31 0")
    js__map_shuffle_reduce_9.writeAction("move X31 0(X20) 0 8")
    js__map_shuffle_reduce_9.writeAction("addi X8 X16 0")
    js__map_shuffle_reduce_9.writeAction("addi X10 X27 0")
    js__map_shuffle_reduce_9.writeAction("mul X9 X27 X19")
    js__map_shuffle_reduce_9.writeAction("addi X2 X21 0")
    js__map_shuffle_reduce_9.writeAction("evlb X21 10")
    js__map_shuffle_reduce_9.writeAction("addi X7 X20 768")
    js__map_shuffle_reduce_9.writeAction("addi X11 X29 0")
    js__map_shuffle_reduce_9.writeAction("bcpylli X29 X20 16")
    js__map_shuffle_reduce_9.writeAction("sendr_wcont X21 X21 X16 X19")
    js__map_shuffle_reduce_9.writeAction("evi X2 X30 255 4")
    js__map_shuffle_reduce_9.writeAction("evlb X30 11")
    js__map_shuffle_reduce_9.writeAction("movir X17 704")
    js__map_shuffle_reduce_9.writeAction("add X7 X17 X17")
    js__map_shuffle_reduce_9.writeAction("movrl X27 0(X17) 0 8")
    js__map_shuffle_reduce_9.writeAction("movir X18 0")
    js__map_shuffle_reduce_9.writeAction("evlb X18 19")
    js__map_shuffle_reduce_9.writeAction("movrl X18 8(X17) 0 8")
    js__map_shuffle_reduce_9.writeAction("movrl X27  16(X17) 0 8")
    js__map_shuffle_reduce_9.writeAction("movrl X0 24(X17) 0 8")
    js__map_shuffle_reduce_9.writeAction("send_wcont X30 X21 X17 8")
    js__map_shuffle_reduce_9.writeAction("addi X17 X20 8")
    js__map_shuffle_reduce_9.writeAction("movir X18 0")
    js__map_shuffle_reduce_9.writeAction("evlb X18 18")
    js__map_shuffle_reduce_9.writeAction("movrl X18 0(X20) 1 8")
    js__map_shuffle_reduce_9.writeAction("addi X11 X29 0")
    js__map_shuffle_reduce_9.writeAction("bcpylli X29 X20 16")
    js__map_shuffle_reduce_9.writeAction("send_wcont X30 X21 X17 8")
    js__map_shuffle_reduce_9.writeAction("movir X26 0")
    js__map_shuffle_reduce_9.writeAction("addi X9 X19 0")
    js__map_shuffle_reduce_9.writeAction("perflog 1 0 'UDKVMSR Initialization setup finished.' ")
    js__map_shuffle_reduce_9.writeAction("yield")

    ## js__finish_init_udkvmsr with ID 10
    js__finish_init_udkvmsr_10 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 10)
    js__finish_init_udkvmsr_10.writeAction("addi X26 X26 1")
    js__finish_init_udkvmsr_10.writeAction("bgei X26 3 EFA_js_soxqv_finish_initialize_udkvmsr")
    js__finish_init_udkvmsr_10.writeAction("yield")
    js__finish_init_udkvmsr_10.writeAction("EFA_js_soxqv_finish_initialize_udkvmsr: addi X2 X30 0")
    js__finish_init_udkvmsr_10.writeAction("evlb X30 20")
    js__finish_init_udkvmsr_10.writeAction("perflog 1 0 'UDKVMSR Initialization Finished.' ")
    js__finish_init_udkvmsr_10.writeAction("sendr_wcont X30 X31 X16 X19")
    js__finish_init_udkvmsr_10.writeAction("yield")

    ## js__broadcast_global with ID 11
    js__broadcast_global_11 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 11)
    js__broadcast_global_11.writeAction("addi X8 X27 0")
    js__broadcast_global_11.writeAction("sri X27 X25 11")
    js__broadcast_global_11.writeAction("movir X16 512")
    js__broadcast_global_11.writeAction("bgt X25 X16 EFA_js_soxqv_max_child_modular_eq_zero")
    js__broadcast_global_11.writeAction("andi X27 X16 2047")
    js__broadcast_global_11.writeAction("beqi X16 0 EFA_js_soxqv_modular_eq_zero")
    js__broadcast_global_11.writeAction("addi X25 X25 1")
    js__broadcast_global_11.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js__broadcast_global_11.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 512")
    js__broadcast_global_11.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js__broadcast_global_11.writeAction("evlb X28 12")
    js__broadcast_global_11.writeAction("mov_imm2reg X17 0")
    js__broadcast_global_11.writeAction("EFA_js_soxqv_broadcast_loop: lshift X17 X16 11")
    js__broadcast_global_11.writeAction("add X0 X16 X16")
    js__broadcast_global_11.writeAction("ev X28 X28 X16 X16 8")
    js__broadcast_global_11.writeAction("sendops_wret X28 16 X8 8 X16")
    js__broadcast_global_11.writeAction("addi X17 X17 1")
    js__broadcast_global_11.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js__broadcast_global_11.writeAction("mov_imm2reg X26 0")
    js__broadcast_global_11.writeAction("yield")

    ## js__broadcast_node with ID 12
    js__broadcast_node_12 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 12)
    js__broadcast_node_12.writeAction("addi X1 X29 0")
    js__broadcast_node_12.writeAction("sri X8 X25 6")
    js__broadcast_node_12.writeAction("movir X16 32")
    js__broadcast_node_12.writeAction("bgt X25 X16 EFA_js_soxqv_max_child_modular_eq_zero")
    js__broadcast_node_12.writeAction("andi X8 X16 63")
    js__broadcast_node_12.writeAction("beqi X16 0 EFA_js_soxqv_modular_eq_zero")
    js__broadcast_node_12.writeAction("addi X25 X25 1")
    js__broadcast_node_12.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js__broadcast_node_12.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 32")
    js__broadcast_node_12.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js__broadcast_node_12.writeAction("evlb X28 13")
    js__broadcast_node_12.writeAction("mov_imm2reg X17 0")
    js__broadcast_node_12.writeAction("EFA_js_soxqv_broadcast_loop: lshift X17 X16 6")
    js__broadcast_node_12.writeAction("add X0 X16 X16")
    js__broadcast_node_12.writeAction("ev X28 X28 X16 X16 8")
    js__broadcast_node_12.writeAction("sendops_wret X28 15 X8 8 X16")
    js__broadcast_node_12.writeAction("addi X17 X17 1")
    js__broadcast_node_12.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js__broadcast_node_12.writeAction("mov_imm2reg X26 0")
    js__broadcast_node_12.writeAction("yield")

    ## js__broadcast_ud with ID 13
    js__broadcast_ud_13 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 13)
    js__broadcast_ud_13.writeAction("addi X1 X29 0")
    js__broadcast_ud_13.writeAction("movir X25 64")
    js__broadcast_ud_13.writeAction("bgt X8 X25 EFA_js_soxqv_modular_eq_zero")
    js__broadcast_ud_13.writeAction("addi X8 X25 0")
    js__broadcast_ud_13.writeAction("EFA_js_soxqv_modular_eq_zero: evi X2 X28 255 4")
    js__broadcast_ud_13.writeAction("ev X28 X28 X9 X9 1")
    js__broadcast_ud_13.writeAction("mov_imm2reg X17 0")
    js__broadcast_ud_13.writeAction("EFA_js_soxqv_broadcast_loop: add X0 X17 X16")
    js__broadcast_ud_13.writeAction("ev X28 X28 X16 X16 8")
    js__broadcast_ud_13.writeAction("sendops_wret X28 14 X10 6 X16")
    js__broadcast_ud_13.writeAction("addi X17 X17 1")
    js__broadcast_ud_13.writeAction("blt X17 X25 EFA_js_soxqv_broadcast_loop")
    js__broadcast_ud_13.writeAction("mov_imm2reg X26 0")
    js__broadcast_ud_13.writeAction("yield")

    ## js__broadcast_ud_fin with ID 14
    js__broadcast_ud_fin_14 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 14)
    js__broadcast_ud_fin_14.writeAction("addi X26 X26 1")
    js__broadcast_ud_fin_14.writeAction("blt X26 X25 EFA_js_soxqv_continue")
    js__broadcast_ud_fin_14.writeAction("sendr_reply X0 X2 X16")
    js__broadcast_ud_fin_14.writeAction("yield_terminate")
    js__broadcast_ud_fin_14.writeAction("EFA_js_soxqv_continue: yield")

    ## js__broadcast_node_fin with ID 15
    js__broadcast_node_fin_15 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 15)
    js__broadcast_node_fin_15.writeAction("addi X26 X26 1")
    js__broadcast_node_fin_15.writeAction("blt X26 X25 EFA_js_soxqv_continue")
    js__broadcast_node_fin_15.writeAction("sendr_reply X0 X2 X16")
    js__broadcast_node_fin_15.writeAction("yield_terminate")
    js__broadcast_node_fin_15.writeAction("EFA_js_soxqv_continue: yield")

    ## js__broadcast_global_fin with ID 16
    js__broadcast_global_fin_16 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 16)
    js__broadcast_global_fin_16.writeAction("addi X26 X26 1")
    js__broadcast_global_fin_16.writeAction("beq X26 X25 EFA_js_soxqv_global_bcst_finish")
    js__broadcast_global_fin_16.writeAction("yield")
    js__broadcast_global_fin_16.writeAction("EFA_js_soxqv_global_bcst_finish: sendr_reply X0 X2 X16")
    js__broadcast_global_fin_16.writeAction("yieldt")

    ## js__broadcast_value_to_scratchpad with ID 17
    js__broadcast_value_to_scratchpad_17 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 17)
    js__broadcast_value_to_scratchpad_17.writeAction("sri X8 X16 32")
    js__broadcast_value_to_scratchpad_17.writeAction("add X7 X16 X16")
    js__broadcast_value_to_scratchpad_17.writeAction("andi X8 X17 15")
    js__broadcast_value_to_scratchpad_17.writeAction("bcpyol X9 X16 X17")
    js__broadcast_value_to_scratchpad_17.writeAction("sendr_reply X1 X2 X16")
    js__broadcast_value_to_scratchpad_17.writeAction("yieldt")

    ## js__init_input_kvset_on_lane with ID 18
    js__init_input_kvset_on_lane_18 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 18)
    js__init_input_kvset_on_lane_18.writeAction("movir X16 768")
    js__init_input_kvset_on_lane_18.writeAction("add X7 X16 X16")
    js__init_input_kvset_on_lane_18.writeAction("bcpyoli X8 X16 2")
    js__init_input_kvset_on_lane_18.writeAction("sendr_reply X0 X16 X28")
    js__init_input_kvset_on_lane_18.writeAction("yield_terminate")

    ## js__init_sp_lane with ID 19
    js__init_sp_lane_19 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 19)
    js__init_sp_lane_19.writeAction("mov_imm2reg UDPR_0 0")
    js__init_sp_lane_19.writeAction("addi X7 X20 640")
    js__init_sp_lane_19.writeAction("move UDPR_0 0(X20) 0 8")
    js__init_sp_lane_19.writeAction("move UDPR_0 8(X20) 0 8")
    js__init_sp_lane_19.writeAction("move UDPR_0 24(X20) 0 8")
    js__init_sp_lane_19.writeAction("movir X28 128")
    js__init_sp_lane_19.writeAction("move X28 32(X20) 0 8")
    js__init_sp_lane_19.writeAction("subi X8 X28 1")
    js__init_sp_lane_19.writeAction("move X28 40(X20) 0 8")
    js__init_sp_lane_19.writeAction("move X9 56(X20) 0 8")
    js__init_sp_lane_19.writeAction("sendr_reply X0 X16 X28")
    js__init_sp_lane_19.writeAction("yield_terminate")

    ## js__init_global_master with ID 20
    js__init_global_master_20 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 20)
    js__init_global_master_20.writeAction("mul X27 X9 X24")
    js__init_global_master_20.writeAction("sri X27 X25 11")
    js__init_global_master_20.writeAction("movir X28 512")
    js__init_global_master_20.writeAction("bgt X25 X28 EFA_js_soxqv_max_child_modular_eq_zero")
    js__init_global_master_20.writeAction("andi X27 X28 2047")
    js__init_global_master_20.writeAction("beqi X28 0 EFA_js_soxqv_modular_eq_zero")
    js__init_global_master_20.writeAction("addi X25 X25 1")
    js__init_global_master_20.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js__init_global_master_20.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 512")
    js__init_global_master_20.writeAction("EFA_js_soxqv_modular_eq_zero: mov_imm2reg X22 2048")
    js__init_global_master_20.writeAction("bge X27 X22 EFA_js_soxqv_global_master_full_child")
    js__init_global_master_20.writeAction("addi X27 X22 0")
    js__init_global_master_20.writeAction("EFA_js_soxqv_global_master_full_child: mul X22 X9 X20")
    js__init_global_master_20.writeAction("lshift X20 X18 4")
    js__init_global_master_20.writeAction("mov_reg2reg X0 X23")
    js__init_global_master_20.writeAction("movir X21 0")
    js__init_global_master_20.writeAction("evi X2 X30 255 4")
    js__init_global_master_20.writeAction("evlb X30 22")
    js__init_global_master_20.writeAction("EFA_js_soxqv_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    js__init_global_master_20.writeAction("sendr3_wret X30 21             X16 X18 X27 X28")
    js__init_global_master_20.writeAction("add X22 X23 X23")
    js__init_global_master_20.writeAction("add X18 X16 X16 ")
    js__init_global_master_20.writeAction("addi X21 X21 1")
    js__init_global_master_20.writeAction("blt X21 X25 EFA_js_soxqv_glb_master_loop")
    js__init_global_master_20.writeAction("mul X21 X20 X17")
    js__init_global_master_20.writeAction("mov_imm2reg X19 0")
    js__init_global_master_20.writeAction("yield")

    ## js__global_master with ID 21
    js__global_master_21 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 21)
    js__global_master_21.writeAction("add X8 X19 X19")
    js__global_master_21.writeAction("bge X17 X24 EFA_js_soxqv_global_master_fin_fetch")
    js__global_master_21.writeAction("sendr3_wret X1 21             X16 X18 X27 X28")
    js__global_master_21.writeAction("add X20 X17 X17")
    js__global_master_21.writeAction("add X18 X16 X16 ")
    js__global_master_21.writeAction("yield")
    js__global_master_21.writeAction("EFA_js_soxqv_global_master_fin_fetch: subi X21 X21 1")
    js__global_master_21.writeAction("addi X1 X30 0")
    js__global_master_21.writeAction("evlb X30 24")
    js__global_master_21.writeAction("sendr_wcont X30 X2 X16 X16")
    js__global_master_21.writeAction("beqi X21 0 EFA_js_soxqv_global_master_fin_map")
    js__global_master_21.writeAction("yield")
    js__global_master_21.writeAction("EFA_js_soxqv_global_master_fin_map: bnei X19 0 EFA_js_soxqv_global_master_init_sync")
    js__global_master_21.writeAction("movir X28 -1")
    js__global_master_21.writeAction("sri X28 X28 1")
    js__global_master_21.writeAction("sendr_wcont X31 X28 X27 X19")
    js__global_master_21.writeAction("print 'returning to user cont %lx' X31")
    js__global_master_21.writeAction("yieldt")
    js__global_master_21.writeAction("EFA_js_soxqv_global_master_init_sync: evi X2 X30 255 4")
    js__global_master_21.writeAction("evlb X30 33")
    js__global_master_21.writeAction("sendr_wcont X30 X31 X27 X19")
    js__global_master_21.writeAction("yield_terminate")

    ## js__init_node_master with ID 22
    js__init_node_master_22 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 22)
    js__init_node_master_22.writeAction("mov_reg2reg X1 X31")
    js__init_node_master_22.writeAction("mov_reg2reg X8 X16")
    js__init_node_master_22.writeAction("mov_reg2reg X10 X27")
    js__init_node_master_22.writeAction("sri X27 X25 6")
    js__init_node_master_22.writeAction("movir X28 32")
    js__init_node_master_22.writeAction("bgt X25 X28 EFA_js_soxqv_max_child_modular_eq_zero")
    js__init_node_master_22.writeAction("andi X27 X28 63")
    js__init_node_master_22.writeAction("beqi X28 0 EFA_js_soxqv_modular_eq_zero")
    js__init_node_master_22.writeAction("addi X25 X25 1")
    js__init_node_master_22.writeAction("jmp EFA_js_soxqv_modular_eq_zero")
    js__init_node_master_22.writeAction("EFA_js_soxqv_max_child_modular_eq_zero: mov_imm2reg X25 32")
    js__init_node_master_22.writeAction("EFA_js_soxqv_modular_eq_zero: add X9 X16 X24")
    js__init_node_master_22.writeAction("mov_imm2reg X21 0")
    js__init_node_master_22.writeAction("mov_imm2reg X22 64")
    js__init_node_master_22.writeAction("bge X27 X22 EFA_js_soxqv_node_master_full_child")
    js__init_node_master_22.writeAction("addi X27 X22 0")
    js__init_node_master_22.writeAction("EFA_js_soxqv_node_master_full_child: div X9 X25 X18")
    js__init_node_master_22.writeAction("addi X0 X23 0")
    js__init_node_master_22.writeAction("evi X2 X30 255 4")
    js__init_node_master_22.writeAction("evlb X30 25")
    js__init_node_master_22.writeAction("EFA_js_soxqv_node_master_loop: ev X30 X30 X23 X23 8")
    js__init_node_master_22.writeAction("sendr3_wret X30 23             X16 X18 X27 X28")
    js__init_node_master_22.writeAction("add X22 X23 X23")
    js__init_node_master_22.writeAction("add X18 X16 X16 ")
    js__init_node_master_22.writeAction("addi X21 X21 1")
    js__init_node_master_22.writeAction("blt X21 X25 EFA_js_soxqv_node_master_loop")
    js__init_node_master_22.writeAction("mov_imm2reg X19 0")
    js__init_node_master_22.writeAction("yield")

    ## js__node_master with ID 23
    js__node_master_23 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 23)
    js__node_master_23.writeAction("add X8 X19 X19")
    js__node_master_23.writeAction("bge X16 X24 EFA_js_soxqv_node_master_fin_fetch")
    js__node_master_23.writeAction("sendr3_wret X1 23             X16 X18 X27 X28")
    js__node_master_23.writeAction("add X18 X16 X16 ")
    js__node_master_23.writeAction("yield")
    js__node_master_23.writeAction("EFA_js_soxqv_node_master_fin_fetch: subi X21 X21 1")
    js__node_master_23.writeAction("addi X1 X30 0")
    js__node_master_23.writeAction("evlb X30 27")
    js__node_master_23.writeAction("sendr_wcont X30 X2 X16 X22")
    js__node_master_23.writeAction("beqi X21 0 EFA_js_soxqv_node_master_fin_partition")
    js__node_master_23.writeAction("yield")
    js__node_master_23.writeAction("EFA_js_soxqv_node_master_fin_partition: sendr_wret X31 22             X19 X19 X28")
    js__node_master_23.writeAction("mov_imm2reg X19 0")
    js__node_master_23.writeAction("yield")

    ## js__termiante_node_master with ID 24
    js__termiante_node_master_24 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 24)
    js__termiante_node_master_24.writeAction("yield_terminate")

    ## js__init_updown_master with ID 25
    js__init_updown_master_25 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 25)
    js__init_updown_master_25.writeAction("mov_reg2reg X1 X31")
    js__init_updown_master_25.writeAction("mov_reg2reg X8 X16")
    js__init_updown_master_25.writeAction("mov_reg2reg X10 X27")
    js__init_updown_master_25.writeAction("movir X25 64")
    js__init_updown_master_25.writeAction("bgt X27 X25 EFA_js_soxqv_modular_eq_zero")
    js__init_updown_master_25.writeAction("addi X27 X25 0")
    js__init_updown_master_25.writeAction("EFA_js_soxqv_modular_eq_zero: add X9 X16 X24")
    js__init_updown_master_25.writeAction("mov_imm2reg X21 0")
    js__init_updown_master_25.writeAction("div X9 X25 X18")
    js__init_updown_master_25.writeAction("mov_reg2reg X0 X23")
    js__init_updown_master_25.writeAction("evi X2 X30 255 4")
    js__init_updown_master_25.writeAction("evlb X30 28")
    js__init_updown_master_25.writeAction("EFA_js_soxqv_updown_master_loop: ev X30 X30 X23 X23 8")
    js__init_updown_master_25.writeAction("sendr3_wret X30 26                 X16 X18 X21 X28")
    js__init_updown_master_25.writeAction("addi X23 X23 1")
    js__init_updown_master_25.writeAction("add X18 X16 X16 ")
    js__init_updown_master_25.writeAction("addi X21 X21 1")
    js__init_updown_master_25.writeAction("blt X21 X25 EFA_js_soxqv_updown_master_loop")
    js__init_updown_master_25.writeAction("mov_imm2reg X19 0")
    js__init_updown_master_25.writeAction("addi X21 X22 0")
    js__init_updown_master_25.writeAction("yield")

    ## js__updown_master with ID 26
    js__updown_master_26 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 26)
    js__updown_master_26.writeAction("add X8 X19 X19")
    js__updown_master_26.writeAction("bge X16 X24 EFA_js_soxqv_updown_master_fin_fetch")
    js__updown_master_26.writeAction("sendr3_wret X1 26                 X16 X18 X22 X28")
    js__updown_master_26.writeAction("addi X22 X22 1")
    js__updown_master_26.writeAction("add X18 X16 X16 ")
    js__updown_master_26.writeAction("yield")
    js__updown_master_26.writeAction("EFA_js_soxqv_updown_master_fin_fetch: subi X21 X21 1")
    js__updown_master_26.writeAction("addi X1 X30 0")
    js__updown_master_26.writeAction("evlb X30 32")
    js__updown_master_26.writeAction("sendr_wcont X30 X2 X16 X22")
    js__updown_master_26.writeAction("blei X21 0 EFA_js_soxqv_updown_master_fin_partition")
    js__updown_master_26.writeAction("yield")
    js__updown_master_26.writeAction("EFA_js_soxqv_updown_master_fin_partition: sendr_wret X31             25 X19 X19 X28")
    js__updown_master_26.writeAction("mov_imm2reg X19 0")
    js__updown_master_26.writeAction("yield")

    ## js__terminate_updown_master with ID 27
    js__terminate_updown_master_27 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 27)
    js__terminate_updown_master_27.writeAction("yield_terminate")

    ## js__lane_master_init with ID 28
    js__lane_master_init_28 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 28)
    js__lane_master_init_28.writeAction("addi X1 X31 0")
    js__lane_master_init_28.writeAction("send_dmlm_ld_wret X8 30 2 X28")
    js__lane_master_init_28.writeAction("movir X16 0")
    js__lane_master_init_28.writeAction("movir X17 64")
    js__lane_master_init_28.writeAction("mov_imm2reg X19 0")
    js__lane_master_init_28.writeAction("addi X8 X25 16")
    js__lane_master_init_28.writeAction("add X8 X9 X26")
    js__lane_master_init_28.writeAction("addi X7 X22 640")
    js__lane_master_init_28.writeAction("move X19 0(X22) 0 8")
    js__lane_master_init_28.writeAction("addi X2 X28 0")
    js__lane_master_init_28.writeAction("evlb X28 29")
    js__lane_master_init_28.writeAction("addi X7 X29 656")
    js__lane_master_init_28.writeAction("move X28 0(X29) 0 8")
    js__lane_master_init_28.writeAction("addi X2 X20 0")
    js__lane_master_init_28.writeAction("evlb X20 31")
    js__lane_master_init_28.writeAction("evi X2 X21 255 4")
    js__lane_master_init_28.writeAction("evlb X21 43")
    js__lane_master_init_28.writeAction("yield")

    ## js__lane_master_loop with ID 29
    js__lane_master_loop_29 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 29)
    js__lane_master_loop_29.writeAction("subi X16 X16 1")
    js__lane_master_loop_29.writeAction("beqi X23 1 EFA_js_soxqv_lane_master_loop_continue")
    js__lane_master_loop_29.writeAction("bge X23 X24 EFA_js_soxqv_lane_master_reach_end")
    js__lane_master_loop_29.writeAction("addi X23 X28 24")
    js__lane_master_loop_29.writeAction("sendr_wcont X20 X20 X28 X24")
    js__lane_master_loop_29.writeAction("send_dmlm_ld X23 X21 3")
    js__lane_master_loop_29.writeAction("addi X16 X16 1")
    js__lane_master_loop_29.writeAction("movir X23 1")
    js__lane_master_loop_29.writeAction("yield")
    js__lane_master_loop_29.writeAction("EFA_js_soxqv_lane_master_reach_end: bgti X16 0 EFA_js_soxqv_lane_master_loop_continue")
    js__lane_master_loop_29.writeAction("bge X25 X26 EFA_js_soxqv_all_partitions_finished")
    js__lane_master_loop_29.writeAction("send_dmlm_ld_wret X25 30 2 X28")
    js__lane_master_loop_29.writeAction("addi X25 X25 16")
    js__lane_master_loop_29.writeAction("yield")
    js__lane_master_loop_29.writeAction("EFA_js_soxqv_all_partitions_finished: movlr 0(X22) X19 0 8")
    js__lane_master_loop_29.writeAction("sendr_wret X31 28 X19 X19 X28")
    js__lane_master_loop_29.writeAction("mov_imm2reg X19 0")
    js__lane_master_loop_29.writeAction("movrl X19 0(X22) 0 8")
    js__lane_master_loop_29.writeAction("EFA_js_soxqv_lane_master_loop_continue: yield")

    ## js__lane_master_read_partition with ID 30
    js__lane_master_read_partition_30 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 30)
    js__lane_master_read_partition_30.writeAction("bge X8 X9 EFA_js_soxqv_lane_master_empty_partition")
    js__lane_master_read_partition_30.writeAction("addi X8 X28 24")
    js__lane_master_read_partition_30.writeAction("sendr_wcont X20 X20 X28 X9")
    js__lane_master_read_partition_30.writeAction("send_dmlm_ld X8 X21 3")
    js__lane_master_read_partition_30.writeAction("addi X16 X16 1")
    js__lane_master_read_partition_30.writeAction("movir X23 1")
    js__lane_master_read_partition_30.writeAction("yield")
    js__lane_master_read_partition_30.writeAction("EFA_js_soxqv_lane_master_empty_partition: bge X25 X26 EFA_js_soxqv_all_partitions_finished")
    js__lane_master_read_partition_30.writeAction("send_dmlm_ld_wret X25 30 2 X28")
    js__lane_master_read_partition_30.writeAction("addi X25 X25 16")
    js__lane_master_read_partition_30.writeAction("yield")
    js__lane_master_read_partition_30.writeAction("EFA_js_soxqv_all_partitions_finished: movlr 0(X22) X19 0 8")
    js__lane_master_read_partition_30.writeAction("sendr_wret X31 28 X19 X19 X28")
    js__lane_master_read_partition_30.writeAction("yield")

    ## js__lane_master_get_next_return with ID 31
    js__lane_master_get_next_return_31 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 31)
    js__lane_master_get_next_return_31.writeAction("bge X16 X17 EFA_js_soxqv_lane_master_break_iterate_loop")
    js__lane_master_get_next_return_31.writeAction("bge X8 X9 EFA_js_soxqv_lane_master_break_iterate_loop")
    js__lane_master_get_next_return_31.writeAction("addi X8 X28 24")
    js__lane_master_get_next_return_31.writeAction("sendr_wcont X20 X20 X28 X9")
    js__lane_master_get_next_return_31.writeAction("send_dmlm_ld X8 X21 3")
    js__lane_master_get_next_return_31.writeAction("addi X16 X16 1")
    js__lane_master_get_next_return_31.writeAction("yield")
    js__lane_master_get_next_return_31.writeAction("EFA_js_soxqv_lane_master_break_iterate_loop: movir X23 0")
    js__lane_master_get_next_return_31.writeAction("addi X8 X23 0")
    js__lane_master_get_next_return_31.writeAction("addi X9 X24 0")
    js__lane_master_get_next_return_31.writeAction("yield")
    js__lane_master_get_next_return_31.writeAction("EFA_js_soxqv_lane_master_iterator_pass_end: subi X16 X16 1")
    js__lane_master_get_next_return_31.writeAction("addi X8 X23 0")
    js__lane_master_get_next_return_31.writeAction("addi X9 X24 0")
    js__lane_master_get_next_return_31.writeAction("bgti X16 0 EFA_js_soxqv_lane_master_loop_continue")
    js__lane_master_get_next_return_31.writeAction("bge X25 X26 EFA_js_soxqv_all_partitions_finished")
    js__lane_master_get_next_return_31.writeAction("send_dmlm_ld_wret X25 30 2 X28")
    js__lane_master_get_next_return_31.writeAction("addi X25 X25 16")
    js__lane_master_get_next_return_31.writeAction("yield")
    js__lane_master_get_next_return_31.writeAction("EFA_js_soxqv_all_partitions_finished: movlr 0(X22) X19 0 8")
    js__lane_master_get_next_return_31.writeAction("sendr_wret X31 28 X19 X19 X28")
    js__lane_master_get_next_return_31.writeAction("EFA_js_soxqv_lane_master_loop_continue: yield")

    ## js__lane_master_terminate with ID 32
    js__lane_master_terminate_32 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 32)
    js__lane_master_terminate_32.writeAction("yield_terminate")

    ## js__init_global_snyc with ID 33
    js__init_global_snyc_33 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 33)
    js__init_global_snyc_33.writeAction("sri X8 X16 11")
    js__init_global_snyc_33.writeAction("movir X28 512")
    js__init_global_snyc_33.writeAction("bgt X16 X28 EFA_js_soxqv_max_child_max_node")
    js__init_global_snyc_33.writeAction("andi X8 X28 2047")
    js__init_global_snyc_33.writeAction("beqi X28 0 EFA_js_soxqv_max_node")
    js__init_global_snyc_33.writeAction("addi X16 X16 1")
    js__init_global_snyc_33.writeAction("jmp EFA_js_soxqv_max_node")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_max_child_max_node: mov_imm2reg X16 512")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_max_node: addi X16 X16 0")
    js__init_global_snyc_33.writeAction("sri X8 X17 6")
    js__init_global_snyc_33.writeAction("movir X28 32")
    js__init_global_snyc_33.writeAction("bgt X17 X28 EFA_js_soxqv_max_child_max_ud_per_nd")
    js__init_global_snyc_33.writeAction("andi X8 X28 63")
    js__init_global_snyc_33.writeAction("beqi X28 0 EFA_js_soxqv_max_ud_per_nd")
    js__init_global_snyc_33.writeAction("addi X17 X17 1")
    js__init_global_snyc_33.writeAction("jmp EFA_js_soxqv_max_ud_per_nd")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_max_ud_per_nd: addi X17 X17 0")
    js__init_global_snyc_33.writeAction("movir X18 64")
    js__init_global_snyc_33.writeAction("bgt X8 X18 EFA_js_soxqv_max_ln_per_ud")
    js__init_global_snyc_33.writeAction("addi X8 X18 0")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_max_ln_per_ud: addi X18 X18 0")
    js__init_global_snyc_33.writeAction("mov_reg2reg X1 X19")
    js__init_global_snyc_33.writeAction("mov_reg2reg X9 X21")
    js__init_global_snyc_33.writeAction("evi X2 X30 255 4")
    js__init_global_snyc_33.writeAction("evlb X30 34")
    js__init_global_snyc_33.writeAction("mov_imm2reg X29 0")
    js__init_global_snyc_33.writeAction("EFA_js_soxqv_broadcast_loop: lshift X29 X28 11")
    js__init_global_snyc_33.writeAction("add X0 X28 X28")
    js__init_global_snyc_33.writeAction("ev X30 X30 X28 X28 8")
    js__init_global_snyc_33.writeAction("sendr_wret X30 36 X17 X18  X28")
    js__init_global_snyc_33.writeAction("addi X29 X29 1")
    js__init_global_snyc_33.writeAction("blt X29 X16 EFA_js_soxqv_broadcast_loop")
    js__init_global_snyc_33.writeAction("mov_imm2reg X20 0")
    js__init_global_snyc_33.writeAction("mov_imm2reg X22 0")
    js__init_global_snyc_33.writeAction("yield")

    ## js__init_node_sync with ID 34
    js__init_node_sync_34 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 34)
    js__init_node_sync_34.writeAction("mov_reg2reg X8 X17")
    js__init_node_sync_34.writeAction("evi X2 X30 255 4")
    js__init_node_sync_34.writeAction("evlb X30 35")
    js__init_node_sync_34.writeAction("mov_imm2reg X29 0")
    js__init_node_sync_34.writeAction("EFA_js_soxqv_broadcast_loop: lshift X29 X28 6")
    js__init_node_sync_34.writeAction("add X0 X28 X28")
    js__init_node_sync_34.writeAction("ev X30 X30 X28 X28 8")
    js__init_node_sync_34.writeAction("sendr_wret X30 37 X9 EQT  X28")
    js__init_node_sync_34.writeAction("addi X29 X29 1")
    js__init_node_sync_34.writeAction("blt X29 X17 EFA_js_soxqv_broadcast_loop")
    js__init_node_sync_34.writeAction("mov_imm2reg X20 0")
    js__init_node_sync_34.writeAction("mov_imm2reg X22 0")
    js__init_node_sync_34.writeAction("mov_reg2reg X1 X19")
    js__init_node_sync_34.writeAction("yield")

    ## js__ud_accumulate with ID 35
    js__ud_accumulate_35 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 35)
    js__ud_accumulate_35.writeAction("mov_imm2reg X20 0")
    js__ud_accumulate_35.writeAction("mov_imm2reg X22 0")
    js__ud_accumulate_35.writeAction("EFA_js_soxqv_accumulate_loop: lshift X20 X17 16")
    js__ud_accumulate_35.writeAction("add X7 X17 X17")
    js__ud_accumulate_35.writeAction("addi X17 X17 648")
    js__ud_accumulate_35.writeAction("move 0(X17) X28 0 8")
    js__ud_accumulate_35.writeAction("add X28 X22 X22")
    js__ud_accumulate_35.writeAction("addi X20 X20 1")
    js__ud_accumulate_35.writeAction("blt X20 X8 EFA_js_soxqv_accumulate_loop")
    js__ud_accumulate_35.writeAction("sendr_reply X22 X22 X28")
    js__ud_accumulate_35.writeAction("yield_terminate")

    ## js__global_sync_return with ID 36
    js__global_sync_return_36 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 36)
    js__global_sync_return_36.writeAction("addi X20 X20 1")
    js__global_sync_return_36.writeAction("add X8 X22 X22")
    js__global_sync_return_36.writeAction("blt X20 X16 EFA_js_soxqv_continue")
    js__global_sync_return_36.writeAction("bge X22 X21 EFA_js_soxqv_sync_finish")
    js__global_sync_return_36.writeAction("mov_imm2reg X29 0")
    js__global_sync_return_36.writeAction("EFA_js_soxqv_broadcast_loop: lshift X29 X28 11")
    js__global_sync_return_36.writeAction("add X0 X28 X28")
    js__global_sync_return_36.writeAction("ev X30 X30 X28 X28 8")
    js__global_sync_return_36.writeAction("sendr_wret X30 36 X17 X18  X28")
    js__global_sync_return_36.writeAction("addi X29 X29 1")
    js__global_sync_return_36.writeAction("blt X29 X16 EFA_js_soxqv_broadcast_loop")
    js__global_sync_return_36.writeAction("mov_imm2reg X20 0")
    js__global_sync_return_36.writeAction("mov_imm2reg X22 0")
    js__global_sync_return_36.writeAction("EFA_js_soxqv_continue: yield")
    js__global_sync_return_36.writeAction("EFA_js_soxqv_sync_finish: movir X30 -1")
    js__global_sync_return_36.writeAction("sri X30 X30 1")
    js__global_sync_return_36.writeAction("sendr_wcont X19 X30 X22 X22")
    js__global_sync_return_36.writeAction("yield_terminate")

    ## js__node_sync_return with ID 37
    js__node_sync_return_37 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 37)
    js__node_sync_return_37.writeAction("addi X20 X20 1")
    js__node_sync_return_37.writeAction("add X8 X22 X22")
    js__node_sync_return_37.writeAction("blt X20 X17 EFA_js_soxqv_continue")
    js__node_sync_return_37.writeAction("sendr_wcont X19 EQT X22 X22")
    js__node_sync_return_37.writeAction("yield_terminate")
    js__node_sync_return_37.writeAction("EFA_js_soxqv_continue: yield")

    ## js__kv_map_emit with ID 38
    js__kv_map_emit_38 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 38)
    js__kv_map_emit_38.writeAction("addi X7 X25 640")
    js__kv_map_emit_38.writeAction("movlr 40(X25) X23 0 8")
    js__kv_map_emit_38.writeAction("movlr 56(X25) X26 0 8")
    js__kv_map_emit_38.writeAction("movir X24 0")
    js__kv_map_emit_38.writeAction("hash X8 X24")
    js__kv_map_emit_38.writeAction("and X24 X23 X24")
    js__kv_map_emit_38.writeAction("add X24 X26 X24")
    js__kv_map_emit_38.writeAction("evi X2 X30 255 4")
    js__kv_map_emit_38.writeAction("evlb X30 41")
    js__kv_map_emit_38.writeAction("evi X2 X27 255 4")
    js__kv_map_emit_38.writeAction("evlb X27 42")
    js__kv_map_emit_38.writeAction("ev X30  X30  X24 X24 8")
    js__kv_map_emit_38.writeAction("sendops_wcont X30 X27 X8 5")
    js__kv_map_emit_38.writeAction("move 0(X25) X29  0 8")
    js__kv_map_emit_38.writeAction("addi X29 X29 1")
    js__kv_map_emit_38.writeAction("move X29 0(X25) 0 8")
    js__kv_map_emit_38.writeAction("yield_terminate")

    ## js__kv_reduce_emit with ID 39
    js__kv_reduce_emit_39 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 39)

    ## js__kv_map_return with ID 40
    js__kv_map_return_40 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 40)
    js__kv_map_return_40.writeAction("addi X7 X16 656")
    js__kv_map_return_40.writeAction("move 0(X16) X29 0 8")
    js__kv_map_return_40.writeAction("sendops_wcont X29 X2 X8 2")
    js__kv_map_return_40.writeAction("yieldt")

    ## js__init_reduce_thread with ID 41
    js__init_reduce_thread_41 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 41)
    js__init_reduce_thread_41.writeAction("addi X7 X20 640")
    js__init_reduce_thread_41.writeAction("movlr 24(X20) X28 0 8")
    js__init_reduce_thread_41.writeAction("move 32(X20) X29 0 8")
    js__init_reduce_thread_41.writeAction("bge X28 X29 EFA_js_soxqv_push_back_to_queue")
    js__init_reduce_thread_41.writeAction("addi X28 X28 1")
    js__init_reduce_thread_41.writeAction("move X28  24(X20) 0 8")
    js__init_reduce_thread_41.writeAction("addi X2 X30 0")
    js__init_reduce_thread_41.writeAction("evlb X30 46")
    js__init_reduce_thread_41.writeAction("sendops_wret X30 42 X8 5 X28")
    js__init_reduce_thread_41.writeAction("yield")
    js__init_reduce_thread_41.writeAction("EFA_js_soxqv_push_back_to_queue: ev_update_1 EQT X30 255 4")
    js__init_reduce_thread_41.writeAction("sendops_wcont X30 X1 X8 5")
    js__init_reduce_thread_41.writeAction("yield_terminate")

    ## js__kv_reduce_return with ID 42
    js__kv_reduce_return_42 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 42)
    js__kv_reduce_return_42.writeAction("addi X7 X20 640")
    js__kv_reduce_return_42.writeAction("move 8(X20) X28 0 8")
    js__kv_reduce_return_42.writeAction("addi X28 X28 1")
    js__kv_reduce_return_42.writeAction("move X28 8(X20) 0 8")
    js__kv_reduce_return_42.writeAction("move 24(X20) X28 0 8")
    js__kv_reduce_return_42.writeAction("subi X28 X28 1")
    js__kv_reduce_return_42.writeAction("move X28  24(X20) 0 8")
    js__kv_reduce_return_42.writeAction("yield_terminate")

    ## js__kv_map with ID 43
    js__kv_map_43 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 43)
    js__kv_map_43.writeAction("EFA_js_soxqv_entry: addi X8 X16 0")
    js__kv_map_43.writeAction("addi X9 X19 0")
    js__kv_map_43.writeAction("addi X10 X22 0")
    js__kv_map_43.writeAction("addi X7 X25 21440")
    js__kv_map_43.writeAction("movlr 0(X25) X26 0 8")
    js__kv_map_43.writeAction("movir X23 0")
    js__kv_map_43.writeAction("sli X8 X27 6")
    js__kv_map_43.writeAction("add X26 X27 X26")
    js__kv_map_43.writeAction("send_dmlm_ld_wret X26 44 3 X27")
    js__kv_map_43.writeAction("yield")

    ## js__map_v1_read_ret with ID 44
    js__map_v1_read_ret_44 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 44)
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv_entry: addi X7 X25 21440")
    js__map_v1_read_ret_44.writeAction("movlr 0(X25) X26 0 8")
    js__map_v1_read_ret_44.writeAction("addi X7 X25 21448")
    js__map_v1_read_ret_44.writeAction("movlr 0(X25) X27 0 8")
    js__map_v1_read_ret_44.writeAction("sub X27 X19 X28")
    js__map_v1_read_ret_44.writeAction("bgtu X22 X28 EFA_js_soxqv___if_map_v1_read_ret_2_post")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_0_true: addi X22 X28 0")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_2_post: bleiu X9 0 EFA_js_soxqv___if_map_v1_read_ret_5_post")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_3_true: addi X9 X17 0")
    js__map_v1_read_ret_44.writeAction("addi X10 X18 0")
    js__map_v1_read_ret_44.writeAction("sli X19 X29 6")
    js__map_v1_read_ret_44.writeAction("add X26 X29 X26")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___while_map_v1_read_ret_6_condition: bleu X28 X23 EFA_js_soxqv___if_map_v1_read_ret_5_post")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___while_map_v1_read_ret_7_body: send_dmlm_ld_wret X26 45 3 X29")
    js__map_v1_read_ret_44.writeAction("addi X26 X26 64")
    js__map_v1_read_ret_44.writeAction("addi X23 X23 1")
    js__map_v1_read_ret_44.writeAction("jmp EFA_js_soxqv___while_map_v1_read_ret_6_condition")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_5_post: sub X22 X28 X22")
    js__map_v1_read_ret_44.writeAction("bneiu X23 0 EFA_js_soxqv___if_map_v1_read_ret_11_post")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_9_true: bneiu X22 0 EFA_js_soxqv___if_map_v1_read_ret_13_false")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_12_true: evi X2 X29 40 1")
    js__map_v1_read_ret_44.writeAction("movir X30 -1")
    js__map_v1_read_ret_44.writeAction("sri X30 X30 1")
    js__map_v1_read_ret_44.writeAction("sendr_wcont X29 X30 X16 X19")
    js__map_v1_read_ret_44.writeAction("jmp EFA_js_soxqv___if_map_v1_read_ret_11_post")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_13_false: addi X16 X16 1")
    js__map_v1_read_ret_44.writeAction("addi X16 X19 1")
    js__map_v1_read_ret_44.writeAction("sli X16 X29 6")
    js__map_v1_read_ret_44.writeAction("add X26 X29 X26")
    js__map_v1_read_ret_44.writeAction("send_dmlm_ld_wret X26 44 3 X29")
    js__map_v1_read_ret_44.writeAction("EFA_js_soxqv___if_map_v1_read_ret_11_post: yield")

    ## js__map_v2_read_ret with ID 45
    js__map_v2_read_ret_45 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 45)
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv_entry: subi X23 X23 1")
    js__map_v2_read_ret_45.writeAction("bleiu X9 0 EFA_js_soxqv___if_map_v2_read_ret_2_post")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_0_true: movir X25 0")
    js__map_v2_read_ret_45.writeAction("evlb X25 38")
    js__map_v2_read_ret_45.writeAction("evi X25 X25 255 4")
    js__map_v2_read_ret_45.writeAction("ev X25 X25 X0 X0 8")
    js__map_v2_read_ret_45.writeAction("sli X8 X27 32")
    js__map_v2_read_ret_45.writeAction("or X27 X16 X26")
    js__map_v2_read_ret_45.writeAction("addi X7 X27 704")
    js__map_v2_read_ret_45.writeAction("movrl X26 0(X27) 0 8")
    js__map_v2_read_ret_45.writeAction("movrl X17 8(X27) 0 8")
    js__map_v2_read_ret_45.writeAction("movrl X18 16(X27) 0 8")
    js__map_v2_read_ret_45.writeAction("movrl X9 24(X27) 0 8")
    js__map_v2_read_ret_45.writeAction("movrl X10 32(X27) 0 8")
    js__map_v2_read_ret_45.writeAction("movir X28 -1")
    js__map_v2_read_ret_45.writeAction("sri X28 X28 1")
    js__map_v2_read_ret_45.writeAction("send_wcont X25 X28 X27 5")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_2_post: bneiu X23 0 EFA_js_soxqv___if_map_v2_read_ret_5_post")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_3_true: bneiu X22 0 EFA_js_soxqv___if_map_v2_read_ret_7_false")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_6_true: evi X2 X25 40 1")
    js__map_v2_read_ret_45.writeAction("movir X26 -1")
    js__map_v2_read_ret_45.writeAction("sri X26 X26 1")
    js__map_v2_read_ret_45.writeAction("sendr_wcont X25 X26 X16 X19")
    js__map_v2_read_ret_45.writeAction("jmp EFA_js_soxqv___if_map_v2_read_ret_5_post")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_7_false: addi X16 X16 1")
    js__map_v2_read_ret_45.writeAction("addi X16 X19 1")
    js__map_v2_read_ret_45.writeAction("addi X7 X25 21440")
    js__map_v2_read_ret_45.writeAction("movlr 0(X25) X26 0 8")
    js__map_v2_read_ret_45.writeAction("sli X16 X27 6")
    js__map_v2_read_ret_45.writeAction("add X26 X27 X26")
    js__map_v2_read_ret_45.writeAction("send_dmlm_ld_wret X26 44 3 X27")
    js__map_v2_read_ret_45.writeAction("EFA_js_soxqv___if_map_v2_read_ret_5_post: yield")

    ## js__kv_reduce with ID 46
    js__kv_reduce_46 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 46)
    js__kv_reduce_46.writeAction("EFA_js_soxqv_entry: addi X1 X25 0")
    js__kv_reduce_46.writeAction("sli X8 X26 32")
    js__kv_reduce_46.writeAction("sri X26 X16 32")
    js__kv_reduce_46.writeAction("addi X9 X17 0")
    js__kv_reduce_46.writeAction("addi X10 X18 0")
    js__kv_reduce_46.writeAction("sri X8 X19 32")
    js__kv_reduce_46.writeAction("addi X11 X20 0")
    js__kv_reduce_46.writeAction("addi X12 X21 0")
    js__kv_reduce_46.writeAction("movir X26 0")
    js__kv_reduce_46.writeAction("evlb X26 0")
    js__kv_reduce_46.writeAction("evi X26 X26 255 4")
    js__kv_reduce_46.writeAction("ev X26 X26 X0 X0 8")
    js__kv_reduce_46.writeAction("movir X29 24")
    js__kv_reduce_46.writeAction("sendr_wret X26 47 X29 X29 X30")
    js__kv_reduce_46.writeAction("addi X7 X27 21464")
    js__kv_reduce_46.writeAction("movlr 0(X27) X28 0 8")
    js__kv_reduce_46.writeAction("yield")

    ## js__sp_malloc_ret with ID 47
    js__sp_malloc_ret_47 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 47)
    js__sp_malloc_ret_47.writeAction("EFA_js_soxqv_entry: addi X8 X24 0")
    js__sp_malloc_ret_47.writeAction("movrl X17 0(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movrl X18 8(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movir X27 0")
    js__sp_malloc_ret_47.writeAction("movrl X27 16(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movir X27 0")
    js__sp_malloc_ret_47.writeAction("movrl X27 24(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movrl X20 32(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movrl X21 40(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movir X27 0")
    js__sp_malloc_ret_47.writeAction("movrl X27 48(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("movir X27 0")
    js__sp_malloc_ret_47.writeAction("movrl X27 56(X24) 0 8")
    js__sp_malloc_ret_47.writeAction("evi X2 X26 48 1")
    js__sp_malloc_ret_47.writeAction("sendr3_wcont X26 X25 X16 X19 X24")
    js__sp_malloc_ret_47.writeAction("yield")

    ## js_compute__setup_thread_reg with ID 48
    js_compute__setup_thread_reg_48 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 48)
    js_compute__setup_thread_reg_48.writeAction("EFA_js_soxqv_entry: addi X8 X16 0")
    js_compute__setup_thread_reg_48.writeAction("addi X9 X17 0")
    js_compute__setup_thread_reg_48.writeAction("movir X18 0")
    js_compute__setup_thread_reg_48.writeAction("movir X19 0")
    js_compute__setup_thread_reg_48.writeAction("addi X10 X20 0")
    js_compute__setup_thread_reg_48.writeAction("movlr 8(X20) X21 0 8")
    js_compute__setup_thread_reg_48.writeAction("movlr 40(X20) X22 0 8")
    js_compute__setup_thread_reg_48.writeAction("send_dmlm_ld_wret X21 49 8 X23")
    js_compute__setup_thread_reg_48.writeAction("send_dmlm_ld_wret X22 50 8 X23")
    js_compute__setup_thread_reg_48.writeAction("movir X19 2")
    js_compute__setup_thread_reg_48.writeAction("yield")

    ## js_compute__v1_nblist_read_ret with ID 49
    js_compute__v1_nblist_read_ret_49 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 49)
    js_compute__v1_nblist_read_ret_49.writeAction("EFA_js_soxqv_entry: subi X19 X19 1")
    js_compute__v1_nblist_read_ret_49.writeAction("addi X20 X21 64")
    js_compute__v1_nblist_read_ret_49.writeAction("bcpyoli X8 X21 8")
    js_compute__v1_nblist_read_ret_49.writeAction("bneiu X19 0 EFA_js_soxqv___if_v1_nblist_read_ret_2_post")
    js_compute__v1_nblist_read_ret_49.writeAction("EFA_js_soxqv___if_v1_nblist_read_ret_0_true: evi X2 X22 51 1")
    js_compute__v1_nblist_read_ret_49.writeAction("sendr_wcont X22 X1 X16 X17")
    js_compute__v1_nblist_read_ret_49.writeAction("EFA_js_soxqv___if_v1_nblist_read_ret_2_post: yield")

    ## js_compute__v2_nblist_read_ret with ID 50
    js_compute__v2_nblist_read_ret_50 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 50)
    js_compute__v2_nblist_read_ret_50.writeAction("EFA_js_soxqv_entry: subi X19 X19 1")
    js_compute__v2_nblist_read_ret_50.writeAction("addi X20 X21 128")
    js_compute__v2_nblist_read_ret_50.writeAction("bcpyoli X8 X21 8")
    js_compute__v2_nblist_read_ret_50.writeAction("bneiu X19 0 EFA_js_soxqv___if_v2_nblist_read_ret_2_post")
    js_compute__v2_nblist_read_ret_50.writeAction("EFA_js_soxqv___if_v2_nblist_read_ret_0_true: evi X2 X22 51 1")
    js_compute__v2_nblist_read_ret_50.writeAction("sendr_wcont X22 X1 X16 X17")
    js_compute__v2_nblist_read_ret_50.writeAction("EFA_js_soxqv___if_v2_nblist_read_ret_2_post: yield")

    ## js_compute__intersect_ab with ID 51
    js_compute__intersect_ab_51 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 51)
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv_entry: movlr 24(X20) X21 0 8")
    js_compute__intersect_ab_51.writeAction("movlr 56(X20) X22 0 8")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_0_true: movlr 0(X20) X26 0 8")
    js_compute__intersect_ab_51.writeAction("movlr 16(X20) X27 0 8")
    js_compute__intersect_ab_51.writeAction("sub X26 X27 X25")
    js_compute__intersect_ab_51.writeAction("bleiu X25 8 EFA_js_soxqv___if_intersect_ab_4_false")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_3_true: movir X23 8")
    js_compute__intersect_ab_51.writeAction("jmp EFA_js_soxqv___if_intersect_ab_5_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_4_false: addi X25 X23 0")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_5_post: movlr 32(X20) X26 0 8")
    js_compute__intersect_ab_51.writeAction("movlr 48(X20) X27 0 8")
    js_compute__intersect_ab_51.writeAction("sub X26 X27 X25")
    js_compute__intersect_ab_51.writeAction("bleiu X25 8 EFA_js_soxqv___if_intersect_ab_7_false")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_6_true: movir X24 8")
    js_compute__intersect_ab_51.writeAction("jmp EFA_js_soxqv___if_intersect_ab_9_true")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_7_false: addi X25 X24 0")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_9_true: addi X20 X25 64")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___while_intersect_ab_12_condition: clt X21 X23 X26")
    js_compute__intersect_ab_51.writeAction("clt X22 X24 X27")
    js_compute__intersect_ab_51.writeAction("and X26 X27 X28")
    js_compute__intersect_ab_51.writeAction("beqiu X28 0 EFA_js_soxqv___while_intersect_ab_14_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___while_intersect_ab_13_body: movwlr X25(X21,0,0) X26")
    js_compute__intersect_ab_51.writeAction("addi X22 X28 8")
    js_compute__intersect_ab_51.writeAction("movwlr X25(X28,0,0) X27")
    js_compute__intersect_ab_51.writeAction("ble X27 X26 EFA_js_soxqv___if_intersect_ab_16_false")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_15_true: addi X21 X21 1")
    js_compute__intersect_ab_51.writeAction("jmp EFA_js_soxqv___if_intersect_ab_17_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_16_false: ble X26 X27 EFA_js_soxqv___if_intersect_ab_19_false")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_18_true: addi X22 X22 1")
    js_compute__intersect_ab_51.writeAction("jmp EFA_js_soxqv___if_intersect_ab_17_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_19_false: addi X18 X18 1")
    js_compute__intersect_ab_51.writeAction("addi X21 X21 1")
    js_compute__intersect_ab_51.writeAction("addi X22 X22 1")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_17_post: jmp EFA_js_soxqv___while_intersect_ab_12_condition")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___while_intersect_ab_14_post: movlr 16(X20) X25 0 8")
    js_compute__intersect_ab_51.writeAction("bneu X21 X23 EFA_js_soxqv___if_intersect_ab_23_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_21_true: add X25 X23 X25")
    js_compute__intersect_ab_51.writeAction("movlr 0(X20) X26 0 8")
    js_compute__intersect_ab_51.writeAction("bgtu X26 X25 EFA_js_soxqv___if_intersect_ab_23_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_24_true: evi X2 X26 52 1")
    js_compute__intersect_ab_51.writeAction("sendr_wcont X26 X1 X16 X17")
    js_compute__intersect_ab_51.writeAction("yield")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_23_post: movlr 48(X20) X26 0 8")
    js_compute__intersect_ab_51.writeAction("bneu X22 X24 EFA_js_soxqv___if_intersect_ab_29_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_27_true: add X26 X24 X26")
    js_compute__intersect_ab_51.writeAction("movlr 32(X20) X27 0 8")
    js_compute__intersect_ab_51.writeAction("bgtu X27 X26 EFA_js_soxqv___if_intersect_ab_29_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_30_true: evi X2 X27 52 1")
    js_compute__intersect_ab_51.writeAction("sendr_wcont X27 X1 X16 X17")
    js_compute__intersect_ab_51.writeAction("yield")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_29_post: bneu X21 X23 EFA_js_soxqv___if_intersect_ab_35_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_33_true: movlr 8(X20) X28 0 8")
    js_compute__intersect_ab_51.writeAction("sli X25 X29 3")
    js_compute__intersect_ab_51.writeAction("add X28 X29 X27")
    js_compute__intersect_ab_51.writeAction("send_dmlm_ld_wret X27 49 8 X28")
    js_compute__intersect_ab_51.writeAction("movir X21 0")
    js_compute__intersect_ab_51.writeAction("addi X19 X19 1")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_35_post: bneu X22 X24 EFA_js_soxqv___if_intersect_ab_38_post")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_36_true: movlr 40(X20) X28 0 8")
    js_compute__intersect_ab_51.writeAction("sli X26 X29 3")
    js_compute__intersect_ab_51.writeAction("add X28 X29 X27")
    js_compute__intersect_ab_51.writeAction("send_dmlm_ld_wret X27 50 8 X28")
    js_compute__intersect_ab_51.writeAction("movir X22 0")
    js_compute__intersect_ab_51.writeAction("addi X19 X19 1")
    js_compute__intersect_ab_51.writeAction("EFA_js_soxqv___if_intersect_ab_38_post: movrl X25 16(X20) 0 8")
    js_compute__intersect_ab_51.writeAction("movrl X21 24(X20) 0 8")
    js_compute__intersect_ab_51.writeAction("movrl X26 48(X20) 0 8")
    js_compute__intersect_ab_51.writeAction("movrl X22 56(X20) 0 8")
    js_compute__intersect_ab_51.writeAction("yield")

    ## js_compute__intersect_term with ID 52
    js_compute__intersect_term_52 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 52)
    js_compute__intersect_term_52.writeAction("EFA_js_soxqv_entry: bleiu X18 0 EFA_js_soxqv___if_intersect_term_2_post")
    js_compute__intersect_term_52.writeAction("EFA_js_soxqv___if_intersect_term_0_true: movlr 0(X20) X21 0 8")
    js_compute__intersect_term_52.writeAction("movlr 32(X20) X22 0 8")
    js_compute__intersect_term_52.writeAction("fcnvt.i64.64 X18 X23")
    js_compute__intersect_term_52.writeAction("add X21 X22 X25")
    js_compute__intersect_term_52.writeAction("sub X25 X18 X26")
    js_compute__intersect_term_52.writeAction("fcnvt.i64.64 X26 X24")
    js_compute__intersect_term_52.writeAction("fdiv.64 X23 X24 X25")
    js_compute__intersect_term_52.writeAction("addi X7 X26 21456")
    js_compute__intersect_term_52.writeAction("movlr 0(X26) X28 0 8")
    js_compute__intersect_term_52.writeAction("addi X28 X29 1")
    js_compute__intersect_term_52.writeAction("movrl X29 0(X26) 0 8")
    js_compute__intersect_term_52.writeAction("EFA_js_soxqv___if_intersect_term_2_post: movir X21 0")
    js_compute__intersect_term_52.writeAction("evlb X21 1")
    js_compute__intersect_term_52.writeAction("evi X21 X21 255 4")
    js_compute__intersect_term_52.writeAction("ev X21 X21 X0 X0 8")
    js_compute__intersect_term_52.writeAction("movir X22 0")
    js_compute__intersect_term_52.writeAction("evlb X22 53")
    js_compute__intersect_term_52.writeAction("evi X22 X22 255 4")
    js_compute__intersect_term_52.writeAction("ev X22 X22 X0 X0 8")
    js_compute__intersect_term_52.writeAction("sendr_wcont X21 X22 X20 X20")
    js_compute__intersect_term_52.writeAction("evi X2 X21 42 1")
    js_compute__intersect_term_52.writeAction("sendr_wcont X21 X1 X16 X17")
    js_compute__intersect_term_52.writeAction("yield")

    ## js_compute__sp_free_ret with ID 53
    js_compute__sp_free_ret_53 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 53)
    js_compute__sp_free_ret_53.writeAction("EFA_js_soxqv_entry: yield_terminate")

    ## main__init with ID 54
    main__init_54 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 54)
    main__init_54.writeAction("EFA_js_soxqv_entry: addi X7 X17 704")
    main__init_54.writeAction("addi X7 X18 21472")
    main__init_54.writeAction("movir X19 0")
    main__init_54.writeAction("evlb X19 2")
    main__init_54.writeAction("evi X19 X19 255 4")
    main__init_54.writeAction("ev X19 X19 X0 X0 8")
    main__init_54.writeAction("movir X20 0")
    main__init_54.writeAction("evlb X20 57")
    main__init_54.writeAction("evi X20 X20 255 4")
    main__init_54.writeAction("ev X20 X20 X0 X0 8")
    main__init_54.writeAction("movrl X10 0(X17) 0 8")
    main__init_54.writeAction("movrl X20 8(X17) 0 8")
    main__init_54.writeAction("movrl X13 16(X17) 0 8")
    main__init_54.writeAction("movrl X14 24(X17) 0 8")
    main__init_54.writeAction("send_wcont X19 X2 X17 8")
    main__init_54.writeAction("movrl X8 0(X17) 0 8")
    main__init_54.writeAction("movrl X9 8(X17) 0 8")
    main__init_54.writeAction("movrl X10 16(X17) 0 8")
    main__init_54.writeAction("movrl X11 0(X18) 0 8")
    main__init_54.writeAction("movrl X12 8(X18) 0 8")
    main__init_54.writeAction("movrl X18 24(X17) 0 8")
    main__init_54.writeAction("addi X18 X18 16")
    main__init_54.writeAction("movrl X15 0(X18) 0 8")
    main__init_54.writeAction("movrl X18 32(X17) 0 8")
    main__init_54.writeAction("movir X19 0")
    main__init_54.writeAction("evlb X19 9")
    main__init_54.writeAction("evi X19 X19 255 4")
    main__init_54.writeAction("ev X19 X19 X0 X0 8")
    main__init_54.writeAction("send_wret X19 55 X17 8 X21")
    main__init_54.writeAction("addi X10 X16 0")
    main__init_54.writeAction("yield")

    ## main__combine_js with ID 55
    main__combine_js_55 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 55)
    main__combine_js_55.writeAction("EFA_js_soxqv_entry: print 'UDKVMSR finished, executed %lu reduce tasks.' X8")
    main__combine_js_55.writeAction("perflog 1 0 'UDKVMSR finished'")
    main__combine_js_55.writeAction("addi X7 X17 64")
    main__combine_js_55.writeAction("movir X19 273")
    main__combine_js_55.writeAction("movrl X19 0(X17) 0 8")
    main__combine_js_55.writeAction("yield_terminate")

    ## main__term with ID 56
    main__term_56 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 56)
    main__term_56.writeAction("EFA_js_soxqv_entry: print 'Total js nonzero count: %lu' X8")
    main__term_56.writeAction("perflog 1 0 'JS finished'")
    main__term_56.writeAction("addi X7 X17 64")
    main__term_56.writeAction("movir X19 273")
    main__term_56.writeAction("movrl X19 0(X17) 0 8")
    main__term_56.writeAction("print 'Set test flag TEST_TOP_FLAG at offset TEST_TOP_OFFSET.'")
    main__term_56.writeAction("yield_terminate")

    ## main_broadcast_init__setup_spd with ID 57
    main_broadcast_init__setup_spd_57 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 57)
    main_broadcast_init__setup_spd_57.writeAction("EFA_js_soxqv_entry: addi X7 X16 21464")
    main_broadcast_init__setup_spd_57.writeAction("movir X18 21472")
    main_broadcast_init__setup_spd_57.writeAction("movrl X18 0(X16) 0 8")
    main_broadcast_init__setup_spd_57.writeAction("addi X7 X16 21440")
    main_broadcast_init__setup_spd_57.writeAction("movrl X8 0(X16) 0 8")
    main_broadcast_init__setup_spd_57.writeAction("addi X7 X16 21448")
    main_broadcast_init__setup_spd_57.writeAction("movrl X9 0(X16) 0 8")
    main_broadcast_init__setup_spd_57.writeAction("yield_terminate")

    ## Broadcast__broadcast_global with ID 58
    Broadcast__broadcast_global_58 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 58)
    Broadcast__broadcast_global_58.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global_58.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global_58.writeAction("movir X16 512")
    Broadcast__broadcast_global_58.writeAction("bgt X25 X16 GenLinkableBroadcast_hbtna_max_child_modular_eq_zero")
    Broadcast__broadcast_global_58.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global_58.writeAction("beqi X16 0 GenLinkableBroadcast_hbtna_modular_eq_zero")
    Broadcast__broadcast_global_58.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global_58.writeAction("jmp GenLinkableBroadcast_hbtna_modular_eq_zero")
    Broadcast__broadcast_global_58.writeAction("GenLinkableBroadcast_hbtna_max_child_modular_eq_zero: mov_imm2reg X25 512")
    Broadcast__broadcast_global_58.writeAction("GenLinkableBroadcast_hbtna_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global_58.writeAction("evlb X28 59")
    Broadcast__broadcast_global_58.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global_58.writeAction("GenLinkableBroadcast_hbtna_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global_58.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global_58.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global_58.writeAction("sendops_wret X28 63 X8 8 X16")
    Broadcast__broadcast_global_58.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global_58.writeAction("blt X17 X25 GenLinkableBroadcast_hbtna_broadcast_loop")
    Broadcast__broadcast_global_58.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global_58.writeAction("yield")

    ## Broadcast__broadcast_node with ID 59
    Broadcast__broadcast_node_59 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 59)
    Broadcast__broadcast_node_59.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node_59.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node_59.writeAction("movir X16 32")
    Broadcast__broadcast_node_59.writeAction("bgt X25 X16 GenLinkableBroadcast_hbtna_max_child_modular_eq_zero")
    Broadcast__broadcast_node_59.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node_59.writeAction("beqi X16 0 GenLinkableBroadcast_hbtna_modular_eq_zero")
    Broadcast__broadcast_node_59.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node_59.writeAction("jmp GenLinkableBroadcast_hbtna_modular_eq_zero")
    Broadcast__broadcast_node_59.writeAction("GenLinkableBroadcast_hbtna_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node_59.writeAction("GenLinkableBroadcast_hbtna_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node_59.writeAction("evlb X28 60")
    Broadcast__broadcast_node_59.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node_59.writeAction("GenLinkableBroadcast_hbtna_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node_59.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node_59.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node_59.writeAction("sendops_wret X28 62 X8 8 X16")
    Broadcast__broadcast_node_59.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node_59.writeAction("blt X17 X25 GenLinkableBroadcast_hbtna_broadcast_loop")
    Broadcast__broadcast_node_59.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node_59.writeAction("yield")

    ## Broadcast__broadcast_ud with ID 60
    Broadcast__broadcast_ud_60 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 60)
    Broadcast__broadcast_ud_60.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud_60.writeAction("movir X25 64")
    Broadcast__broadcast_ud_60.writeAction("bgt X8 X25 GenLinkableBroadcast_hbtna_modular_eq_zero")
    Broadcast__broadcast_ud_60.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud_60.writeAction("GenLinkableBroadcast_hbtna_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud_60.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud_60.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud_60.writeAction("GenLinkableBroadcast_hbtna_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud_60.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud_60.writeAction("sendops_wret X28 61 X10 6 X16")
    Broadcast__broadcast_ud_60.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud_60.writeAction("blt X17 X25 GenLinkableBroadcast_hbtna_broadcast_loop")
    Broadcast__broadcast_ud_60.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud_60.writeAction("yield")

    ## Broadcast__broadcast_ud_fin with ID 61
    Broadcast__broadcast_ud_fin_61 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 61)
    Broadcast__broadcast_ud_fin_61.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin_61.writeAction("blt X26 X25 GenLinkableBroadcast_hbtna_continue")
    Broadcast__broadcast_ud_fin_61.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_ud_fin_61.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin_61.writeAction("GenLinkableBroadcast_hbtna_continue: yield")

    ## Broadcast__broadcast_node_fin with ID 62
    Broadcast__broadcast_node_fin_62 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 62)
    Broadcast__broadcast_node_fin_62.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin_62.writeAction("blt X26 X25 GenLinkableBroadcast_hbtna_continue")
    Broadcast__broadcast_node_fin_62.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin_62.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin_62.writeAction("GenLinkableBroadcast_hbtna_continue: yield")

    ## Broadcast__broadcast_global_fin with ID 63
    Broadcast__broadcast_global_fin_63 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 63)
    Broadcast__broadcast_global_fin_63.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin_63.writeAction("beq X26 X25 GenLinkableBroadcast_hbtna_global_bcst_finish")
    Broadcast__broadcast_global_fin_63.writeAction("yield")
    Broadcast__broadcast_global_fin_63.writeAction("GenLinkableBroadcast_hbtna_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin_63.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad with ID 64
    Broadcast__broadcast_value_to_scratchpad_64 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 64)
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad_64.writeAction("yieldt")



def main():
    efa = EFA([])
    efa.code_level = 'machine'
    efaProgram_js_udkvmsr_exe_nlb(efa)
    return efa