from EFA_v2 import EFA, State, Transition

def efaProgram_PagerankMsrEFA_rh_nlbstrm_on(efa):

    ## init_null_state with ID 0
    init_null_state_0 = State()
    efa.add_state(init_null_state_0)
    efa.add_initId(init_null_state_0.state_id)

    ## Broadcast__broadcast_global with ID 0
    Broadcast__broadcast_global_0 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 0)
    Broadcast__broadcast_global_0.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global_0.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global_0.writeAction("movir X16 512")
    Broadcast__broadcast_global_0.writeAction("bgt X25 X16 GenLinkableBroadcast_hjyfq_max_child_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global_0.writeAction("beqi X16 0 GenLinkableBroadcast_hjyfq_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global_0.writeAction("jmp GenLinkableBroadcast_hjyfq_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_hjyfq_max_child_modular_eq_zero: mov_imm2reg X25 512")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_hjyfq_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global_0.writeAction("evlb X28 1")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_hjyfq_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global_0.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global_0.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global_0.writeAction("sendops_wret X28 5 X8 8 X16")
    Broadcast__broadcast_global_0.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global_0.writeAction("blt X17 X25 GenLinkableBroadcast_hjyfq_broadcast_loop")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global_0.writeAction("yield")

    ## Broadcast__broadcast_node with ID 1
    Broadcast__broadcast_node_1 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 1)
    Broadcast__broadcast_node_1.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node_1.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node_1.writeAction("movir X16 32")
    Broadcast__broadcast_node_1.writeAction("bgt X25 X16 GenLinkableBroadcast_hjyfq_max_child_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node_1.writeAction("beqi X16 0 GenLinkableBroadcast_hjyfq_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node_1.writeAction("jmp GenLinkableBroadcast_hjyfq_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_hjyfq_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_hjyfq_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node_1.writeAction("evlb X28 2")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_hjyfq_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node_1.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node_1.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node_1.writeAction("sendops_wret X28 4 X8 8 X16")
    Broadcast__broadcast_node_1.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node_1.writeAction("blt X17 X25 GenLinkableBroadcast_hjyfq_broadcast_loop")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node_1.writeAction("yield")

    ## Broadcast__broadcast_ud with ID 2
    Broadcast__broadcast_ud_2 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 2)
    Broadcast__broadcast_ud_2.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud_2.writeAction("movir X25 64")
    Broadcast__broadcast_ud_2.writeAction("bgt X8 X25 GenLinkableBroadcast_hjyfq_modular_eq_zero")
    Broadcast__broadcast_ud_2.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_hjyfq_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_hjyfq_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud_2.writeAction("sendops_wret X28 3 X10 6 X16")
    Broadcast__broadcast_ud_2.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud_2.writeAction("blt X17 X25 GenLinkableBroadcast_hjyfq_broadcast_loop")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud_2.writeAction("yield")

    ## Broadcast__broadcast_ud_fin with ID 3
    Broadcast__broadcast_ud_fin_3 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 3)
    Broadcast__broadcast_ud_fin_3.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin_3.writeAction("blt X26 X25 GenLinkableBroadcast_hjyfq_continue")
    Broadcast__broadcast_ud_fin_3.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_ud_fin_3.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin_3.writeAction("GenLinkableBroadcast_hjyfq_continue: yield")

    ## Broadcast__broadcast_node_fin with ID 4
    Broadcast__broadcast_node_fin_4 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 4)
    Broadcast__broadcast_node_fin_4.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin_4.writeAction("blt X26 X25 GenLinkableBroadcast_hjyfq_continue")
    Broadcast__broadcast_node_fin_4.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin_4.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin_4.writeAction("GenLinkableBroadcast_hjyfq_continue: yield")

    ## Broadcast__broadcast_global_fin with ID 5
    Broadcast__broadcast_global_fin_5 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 5)
    Broadcast__broadcast_global_fin_5.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin_5.writeAction("beq X26 X25 GenLinkableBroadcast_hjyfq_global_bcst_finish")
    Broadcast__broadcast_global_fin_5.writeAction("yield")
    Broadcast__broadcast_global_fin_5.writeAction("GenLinkableBroadcast_hjyfq_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin_5.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad with ID 6
    Broadcast__broadcast_value_to_scratchpad_6 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 6)
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("yieldt")

    ## pr__map_shuffle_reduce with ID 7
    pr__map_shuffle_reduce_7 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 7)
    pr__map_shuffle_reduce_7.writeAction("addi X7 X20 112")
    pr__map_shuffle_reduce_7.writeAction("addi X1 X31 0")
    pr__map_shuffle_reduce_7.writeAction("move X31 0(X20) 0 8")
    pr__map_shuffle_reduce_7.writeAction("addi X8 X16 0")
    pr__map_shuffle_reduce_7.writeAction("addi X10 X27 0")
    pr__map_shuffle_reduce_7.writeAction("mul X9 X27 X19")
    pr__map_shuffle_reduce_7.writeAction("addi X2 X21 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X21 8")
    pr__map_shuffle_reduce_7.writeAction("addi X7 X20 224")
    pr__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("sendr_wcont X21 X21 X16 X19")
    pr__map_shuffle_reduce_7.writeAction("evi X2 X30 255 4")
    pr__map_shuffle_reduce_7.writeAction("evlb X30 9")
    pr__map_shuffle_reduce_7.writeAction("movir X17 128")
    pr__map_shuffle_reduce_7.writeAction("add X7 X17 X17")
    pr__map_shuffle_reduce_7.writeAction("movrl X27 0(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 18")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 8(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movrl X27  16(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movrl X0 24(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    pr__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 16")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    pr__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    pr__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 17")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    pr__map_shuffle_reduce_7.writeAction("addi X12 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8 ")
    pr__map_shuffle_reduce_7.writeAction("movir X26 0")
    pr__map_shuffle_reduce_7.writeAction("addi X9 X19 0")
    pr__map_shuffle_reduce_7.writeAction("perflog 1 0 'UDKVMSR Initialization setup finished.' ")
    pr__map_shuffle_reduce_7.writeAction("yield")

    ## pr__finish_init_udkvmsr with ID 8
    pr__finish_init_udkvmsr_8 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 8)
    pr__finish_init_udkvmsr_8.writeAction("addi X26 X26 1")
    pr__finish_init_udkvmsr_8.writeAction("bgei X26 4 GenMSRPagerankEFA_txaek_finish_initialize_udkvmsr")
    pr__finish_init_udkvmsr_8.writeAction("yield")
    pr__finish_init_udkvmsr_8.writeAction("GenMSRPagerankEFA_txaek_finish_initialize_udkvmsr: addi X2 X30 0")
    pr__finish_init_udkvmsr_8.writeAction("evlb X30 19")
    pr__finish_init_udkvmsr_8.writeAction("perflog 1 0 'UDKVMSR Initialization Finished.' ")
    pr__finish_init_udkvmsr_8.writeAction("sendr_wcont X30 X31 X16 X19")
    pr__finish_init_udkvmsr_8.writeAction("yield")

    ## pr__broadcast_global with ID 9
    pr__broadcast_global_9 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 9)
    pr__broadcast_global_9.writeAction("addi X8 X27 0")
    pr__broadcast_global_9.writeAction("sri X27 X25 11")
    pr__broadcast_global_9.writeAction("movir X16 512")
    pr__broadcast_global_9.writeAction("bgt X25 X16 GenMSRPagerankEFA_txaek_max_child_modular_eq_zero")
    pr__broadcast_global_9.writeAction("andi X27 X16 2047")
    pr__broadcast_global_9.writeAction("beqi X16 0 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__broadcast_global_9.writeAction("addi X25 X25 1")
    pr__broadcast_global_9.writeAction("jmp GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_txaek_max_child_modular_eq_zero: mov_imm2reg X25 512")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_global_9.writeAction("evlb X28 10")
    pr__broadcast_global_9.writeAction("mov_imm2reg X17 0")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: lshift X17 X16 11")
    pr__broadcast_global_9.writeAction("add X0 X16 X16")
    pr__broadcast_global_9.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_global_9.writeAction("sendops_wret X28 14 X8 8 X16")
    pr__broadcast_global_9.writeAction("addi X17 X17 1")
    pr__broadcast_global_9.writeAction("blt X17 X25 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__broadcast_global_9.writeAction("mov_imm2reg X26 0")
    pr__broadcast_global_9.writeAction("yield")

    ## pr__broadcast_node with ID 10
    pr__broadcast_node_10 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 10)
    pr__broadcast_node_10.writeAction("addi X1 X29 0")
    pr__broadcast_node_10.writeAction("sri X8 X25 6")
    pr__broadcast_node_10.writeAction("movir X16 32")
    pr__broadcast_node_10.writeAction("bgt X25 X16 GenMSRPagerankEFA_txaek_max_child_modular_eq_zero")
    pr__broadcast_node_10.writeAction("andi X8 X16 63")
    pr__broadcast_node_10.writeAction("beqi X16 0 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__broadcast_node_10.writeAction("addi X25 X25 1")
    pr__broadcast_node_10.writeAction("jmp GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_txaek_max_child_modular_eq_zero: mov_imm2reg X25 32")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_node_10.writeAction("evlb X28 11")
    pr__broadcast_node_10.writeAction("mov_imm2reg X17 0")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: lshift X17 X16 6")
    pr__broadcast_node_10.writeAction("add X0 X16 X16")
    pr__broadcast_node_10.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_node_10.writeAction("sendops_wret X28 13 X8 8 X16")
    pr__broadcast_node_10.writeAction("addi X17 X17 1")
    pr__broadcast_node_10.writeAction("blt X17 X25 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__broadcast_node_10.writeAction("mov_imm2reg X26 0")
    pr__broadcast_node_10.writeAction("yield")

    ## pr__broadcast_ud with ID 11
    pr__broadcast_ud_11 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 11)
    pr__broadcast_ud_11.writeAction("addi X1 X29 0")
    pr__broadcast_ud_11.writeAction("movir X25 64")
    pr__broadcast_ud_11.writeAction("bgt X8 X25 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__broadcast_ud_11.writeAction("addi X8 X25 0")
    pr__broadcast_ud_11.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_ud_11.writeAction("ev X28 X28 X9 X9 1")
    pr__broadcast_ud_11.writeAction("mov_imm2reg X17 0")
    pr__broadcast_ud_11.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: add X0 X17 X16")
    pr__broadcast_ud_11.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_ud_11.writeAction("sendops_wret X28 12 X10 6 X16")
    pr__broadcast_ud_11.writeAction("addi X17 X17 1")
    pr__broadcast_ud_11.writeAction("blt X17 X25 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__broadcast_ud_11.writeAction("mov_imm2reg X26 0")
    pr__broadcast_ud_11.writeAction("yield")

    ## pr__broadcast_ud_fin with ID 12
    pr__broadcast_ud_fin_12 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 12)
    pr__broadcast_ud_fin_12.writeAction("addi X26 X26 1")
    pr__broadcast_ud_fin_12.writeAction("blt X26 X25 GenMSRPagerankEFA_txaek_continue")
    pr__broadcast_ud_fin_12.writeAction("sendr_reply X0 X2 X16")
    pr__broadcast_ud_fin_12.writeAction("yield_terminate")
    pr__broadcast_ud_fin_12.writeAction("GenMSRPagerankEFA_txaek_continue: yield")

    ## pr__broadcast_node_fin with ID 13
    pr__broadcast_node_fin_13 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 13)
    pr__broadcast_node_fin_13.writeAction("addi X26 X26 1")
    pr__broadcast_node_fin_13.writeAction("blt X26 X25 GenMSRPagerankEFA_txaek_continue")
    pr__broadcast_node_fin_13.writeAction("sendr_reply X0 X2 X16")
    pr__broadcast_node_fin_13.writeAction("yield_terminate")
    pr__broadcast_node_fin_13.writeAction("GenMSRPagerankEFA_txaek_continue: yield")

    ## pr__broadcast_global_fin with ID 14
    pr__broadcast_global_fin_14 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 14)
    pr__broadcast_global_fin_14.writeAction("addi X26 X26 1")
    pr__broadcast_global_fin_14.writeAction("beq X26 X25 GenMSRPagerankEFA_txaek_global_bcst_finish")
    pr__broadcast_global_fin_14.writeAction("yield")
    pr__broadcast_global_fin_14.writeAction("GenMSRPagerankEFA_txaek_global_bcst_finish: sendr_reply X0 X2 X16")
    pr__broadcast_global_fin_14.writeAction("yieldt")

    ## pr__broadcast_value_to_scratchpad with ID 15
    pr__broadcast_value_to_scratchpad_15 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 15)
    pr__broadcast_value_to_scratchpad_15.writeAction("sri X8 X16 32")
    pr__broadcast_value_to_scratchpad_15.writeAction("add X7 X16 X16")
    pr__broadcast_value_to_scratchpad_15.writeAction("andi X8 X17 15")
    pr__broadcast_value_to_scratchpad_15.writeAction("bcpyol X9 X16 X17")
    pr__broadcast_value_to_scratchpad_15.writeAction("sendr_reply X1 X2 X16")
    pr__broadcast_value_to_scratchpad_15.writeAction("yieldt")

    ## pr__init_input_kvset_on_lane with ID 16
    pr__init_input_kvset_on_lane_16 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 16)
    pr__init_input_kvset_on_lane_16.writeAction("movir X16 224")
    pr__init_input_kvset_on_lane_16.writeAction("add X7 X16 X16")
    pr__init_input_kvset_on_lane_16.writeAction("bcpyoli X8 X16 2")
    pr__init_input_kvset_on_lane_16.writeAction("sendr_reply X0 X16 X28")
    pr__init_input_kvset_on_lane_16.writeAction("yield_terminate")

    ## pr__init_output_kvset_on_lane with ID 17
    pr__init_output_kvset_on_lane_17 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 17)
    pr__init_output_kvset_on_lane_17.writeAction("movir X16 288")
    pr__init_output_kvset_on_lane_17.writeAction("add X7 X16 X16")
    pr__init_output_kvset_on_lane_17.writeAction("bcpyoli X8 X16  2")
    pr__init_output_kvset_on_lane_17.writeAction("sendr_reply X0 X16 X28")
    pr__init_output_kvset_on_lane_17.writeAction("yield_terminate")

    ## pr__init_sp_lane with ID 18
    pr__init_sp_lane_18 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 18)
    pr__init_sp_lane_18.writeAction("mov_imm2reg UDPR_0 0")
    pr__init_sp_lane_18.writeAction("addi X7 X20 64")
    pr__init_sp_lane_18.writeAction("move UDPR_0 0(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move UDPR_0 8(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move UDPR_0 24(X20) 0 8")
    pr__init_sp_lane_18.writeAction("movir X28 226")
    pr__init_sp_lane_18.writeAction("move X28 32(X20) 0 8")
    pr__init_sp_lane_18.writeAction("subi X8 X28 1")
    pr__init_sp_lane_18.writeAction("move X28 40(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move X9 56(X20) 0 8")
    pr__init_sp_lane_18.writeAction("movir X16 -1")
    pr__init_sp_lane_18.writeAction("movir X19 2000")
    pr__init_sp_lane_18.writeAction("movir X17 352")
    pr__init_sp_lane_18.writeAction("add X7 X17 X17")
    pr__init_sp_lane_18.writeAction("mov_imm2reg X18 0")
    pr__init_sp_lane_18.writeAction("GenMSRPagerankEFA_txaek_init_cache_loop: movwrl X16 X17(X18,1,1)")
    pr__init_sp_lane_18.writeAction("blt X18 X19 GenMSRPagerankEFA_txaek_init_cache_loop")
    pr__init_sp_lane_18.writeAction("sendr_reply X0 X16 X28")
    pr__init_sp_lane_18.writeAction("yield_terminate")

    ## pr__init_global_master with ID 19
    pr__init_global_master_19 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 19)
    pr__init_global_master_19.writeAction("mul X27 X9 X24")
    pr__init_global_master_19.writeAction("sri X27 X25 11")
    pr__init_global_master_19.writeAction("movir X28 512")
    pr__init_global_master_19.writeAction("bgt X25 X28 GenMSRPagerankEFA_txaek_max_child_modular_eq_zero")
    pr__init_global_master_19.writeAction("andi X27 X28 2047")
    pr__init_global_master_19.writeAction("beqi X28 0 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__init_global_master_19.writeAction("addi X25 X25 1")
    pr__init_global_master_19.writeAction("jmp GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_txaek_max_child_modular_eq_zero: mov_imm2reg X25 512")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: mov_imm2reg X22 2048")
    pr__init_global_master_19.writeAction("bge X27 X22 GenMSRPagerankEFA_txaek_global_master_full_child")
    pr__init_global_master_19.writeAction("addi X27 X22 0")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_txaek_global_master_full_child: mul X22 X9 X20")
    pr__init_global_master_19.writeAction("lshift X20 X18 4")
    pr__init_global_master_19.writeAction("mov_reg2reg X0 X23")
    pr__init_global_master_19.writeAction("movir X21 0")
    pr__init_global_master_19.writeAction("evi X2 X30 255 4")
    pr__init_global_master_19.writeAction("evlb X30 23")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_txaek_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    pr__init_global_master_19.writeAction("sendr3_wret X30 20             X16 X18 X27 X28")
    pr__init_global_master_19.writeAction("add X22 X23 X23")
    pr__init_global_master_19.writeAction("add X18 X16 X16 ")
    pr__init_global_master_19.writeAction("addi X21 X21 1")
    pr__init_global_master_19.writeAction("blt X21 X25 GenMSRPagerankEFA_txaek_glb_master_loop")
    pr__init_global_master_19.writeAction("mul X21 X20 X17")
    pr__init_global_master_19.writeAction("mov_imm2reg X19 0")
    pr__init_global_master_19.writeAction("yield")

    ## pr__global_master with ID 20
    pr__global_master_20 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 20)
    pr__global_master_20.writeAction("add X8 X19 X19")
    pr__global_master_20.writeAction("bge X17 X24 GenMSRPagerankEFA_txaek_global_master_fin_fetch")
    pr__global_master_20.writeAction("sendr3_wret X1 20             X16 X18 X27 X28")
    pr__global_master_20.writeAction("add X20 X17 X17")
    pr__global_master_20.writeAction("add X18 X16 X16 ")
    pr__global_master_20.writeAction("yield")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_txaek_global_master_fin_fetch: subi X21 X21 1")
    pr__global_master_20.writeAction("addi X1 X30 0")
    pr__global_master_20.writeAction("evlb X30 25")
    pr__global_master_20.writeAction("sendr_wcont X30 X2 X16 X16")
    pr__global_master_20.writeAction("beqi X21 0 GenMSRPagerankEFA_txaek_global_master_fin_map")
    pr__global_master_20.writeAction("yield")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_txaek_global_master_fin_map: evii X30, 9 255 5")
    pr__global_master_20.writeAction("movir X29 128")
    pr__global_master_20.writeAction("add X7 X29 X29")
    pr__global_master_20.writeAction("movrl X27 0(X29) 0 8")
    pr__global_master_20.writeAction("movir X28 0")
    pr__global_master_20.writeAction("evlb X28 56")
    pr__global_master_20.writeAction("movrl X28 8(X29) 0 8")
    pr__global_master_20.writeAction("movir X28 1")
    pr__global_master_20.writeAction("movrl X28  16(X29) 0 8")
    pr__global_master_20.writeAction("evii X28 57 255 5")
    pr__global_master_20.writeAction("send_wcont X30 X28 X29 8")
    pr__global_master_20.writeAction("bnei X19 0 GenMSRPagerankEFA_txaek_global_master_init_sync")
    pr__global_master_20.writeAction("movir X28 -1")
    pr__global_master_20.writeAction("sri X28 X28 1")
    pr__global_master_20.writeAction("sendr_wcont X31 X28 X27 X19")
    pr__global_master_20.writeAction("print 'returning to user cont %lx' X31")
    pr__global_master_20.writeAction("yieldt")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_txaek_global_master_init_sync: evi X2 X30 255 4")
    pr__global_master_20.writeAction("evlb X30 35")
    pr__global_master_20.writeAction("addi X2 X28 0")
    pr__global_master_20.writeAction("evlb X28 21")
    pr__global_master_20.writeAction("sendr_wcont X30 X28 X27 X19")
    pr__global_master_20.writeAction("yield")

    ## pr__cache_flush with ID 21
    pr__cache_flush_21 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 21)
    pr__cache_flush_21.writeAction("movir X20 128")
    pr__cache_flush_21.writeAction("add X20 X7 X20")
    pr__cache_flush_21.writeAction("movrl X27 0(X20) 0 8")
    pr__cache_flush_21.writeAction("movir X28 0")
    pr__cache_flush_21.writeAction("evlb X28 47")
    pr__cache_flush_21.writeAction("movrl X28 8(X20) 0 8")
    pr__cache_flush_21.writeAction("evi X2 X30 255 4")
    pr__cache_flush_21.writeAction("evlb X30 9")
    pr__cache_flush_21.writeAction("send_wret X30 22 X20 8 X28")
    pr__cache_flush_21.writeAction("yield")

    ## pr__cache_flush_return with ID 22
    pr__cache_flush_return_22 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 22)
    pr__cache_flush_return_22.writeAction("movir X28 -1")
    pr__cache_flush_return_22.writeAction("sri X28 X28 1")
    pr__cache_flush_return_22.writeAction("sendr_wcont X31 X28 X19 X19")
    pr__cache_flush_return_22.writeAction("yieldt")

    ## pr__init_node_master with ID 23
    pr__init_node_master_23 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 23)
    pr__init_node_master_23.writeAction("movir X26 0")
    pr__init_node_master_23.writeAction("mov_reg2reg X1 X31")
    pr__init_node_master_23.writeAction("mov_reg2reg X8 X16")
    pr__init_node_master_23.writeAction("mov_reg2reg X10 X27")
    pr__init_node_master_23.writeAction("sri X27 X25 6")
    pr__init_node_master_23.writeAction("movir X28 32")
    pr__init_node_master_23.writeAction("bgt X25 X28 GenMSRPagerankEFA_txaek_max_child_modular_eq_zero")
    pr__init_node_master_23.writeAction("andi X27 X28 63")
    pr__init_node_master_23.writeAction("beqi X28 0 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__init_node_master_23.writeAction("addi X25 X25 1")
    pr__init_node_master_23.writeAction("jmp GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_txaek_max_child_modular_eq_zero: mov_imm2reg X25 32")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: add X9 X16 X24")
    pr__init_node_master_23.writeAction("mov_imm2reg X21 0")
    pr__init_node_master_23.writeAction("mov_imm2reg X22 64")
    pr__init_node_master_23.writeAction("bge X27 X22 GenMSRPagerankEFA_txaek_node_master_full_child")
    pr__init_node_master_23.writeAction("addi X27 X22 0")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_txaek_node_master_full_child: div X9 X25 X18")
    pr__init_node_master_23.writeAction("addi X0 X23 0")
    pr__init_node_master_23.writeAction("evi X2 X30 255 4")
    pr__init_node_master_23.writeAction("evlb X30 26")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_txaek_node_master_loop: ev X30 X30 X23 X23 8")
    pr__init_node_master_23.writeAction("sendr3_wret X30 24             X16 X18 X27 X28")
    pr__init_node_master_23.writeAction("add X22 X23 X23")
    pr__init_node_master_23.writeAction("add X18 X16 X16 ")
    pr__init_node_master_23.writeAction("addi X21 X21 1")
    pr__init_node_master_23.writeAction("addi X26 X26 1")
    pr__init_node_master_23.writeAction("blt X21 X25 GenMSRPagerankEFA_txaek_node_master_loop")
    pr__init_node_master_23.writeAction("mov_imm2reg X19 0")
    pr__init_node_master_23.writeAction("yield")

    ## pr__node_master with ID 24
    pr__node_master_24 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 24)
    pr__node_master_24.writeAction("add X8 X19 X19")
    pr__node_master_24.writeAction("bge X16 X24 GenMSRPagerankEFA_txaek_node_master_fin_fetch")
    pr__node_master_24.writeAction("sendr3_wret X1 24             X16 X18 X27 X28")
    pr__node_master_24.writeAction("add X18 X16 X16 ")
    pr__node_master_24.writeAction("yield")
    pr__node_master_24.writeAction("GenMSRPagerankEFA_txaek_node_master_fin_fetch: subi X21 X21 1")
    pr__node_master_24.writeAction("addi X1 X30 0")
    pr__node_master_24.writeAction("evlb X30 28")
    pr__node_master_24.writeAction("sendr_wcont X30 X2 X16 X22")
    pr__node_master_24.writeAction("beqi X21 0 GenMSRPagerankEFA_txaek_node_master_fin_partition")
    pr__node_master_24.writeAction("yield")
    pr__node_master_24.writeAction("GenMSRPagerankEFA_txaek_node_master_fin_partition: sendr_wret X31 23             X19 X19 X28")
    pr__node_master_24.writeAction("mov_imm2reg X19 0")
    pr__node_master_24.writeAction("yield")

    ## pr__termiante_node_master with ID 25
    pr__termiante_node_master_25 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 25)
    pr__termiante_node_master_25.writeAction("yield_terminate")

    ## pr__init_updown_master with ID 26
    pr__init_updown_master_26 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 26)
    pr__init_updown_master_26.writeAction("movir X26 0")
    pr__init_updown_master_26.writeAction("mov_reg2reg X1 X31")
    pr__init_updown_master_26.writeAction("mov_reg2reg X8 X16")
    pr__init_updown_master_26.writeAction("mov_reg2reg X10 X27")
    pr__init_updown_master_26.writeAction("movir X25 64")
    pr__init_updown_master_26.writeAction("bgt X27 X25 GenMSRPagerankEFA_txaek_modular_eq_zero")
    pr__init_updown_master_26.writeAction("addi X27 X25 0")
    pr__init_updown_master_26.writeAction("GenMSRPagerankEFA_txaek_modular_eq_zero: add X9 X16 X24")
    pr__init_updown_master_26.writeAction("mov_imm2reg X21 0")
    pr__init_updown_master_26.writeAction("mov_imm2reg X18 16")
    pr__init_updown_master_26.writeAction("movir X29 208")
    pr__init_updown_master_26.writeAction("add X7 X29 X29")
    pr__init_updown_master_26.writeAction("mul X25 X18 X28")
    pr__init_updown_master_26.writeAction("add X16 X28 X28")
    pr__init_updown_master_26.writeAction("movrl X28 0(X29) 0 8")
    pr__init_updown_master_26.writeAction("movir X29 216")
    pr__init_updown_master_26.writeAction("add X7 X29 X29")
    pr__init_updown_master_26.writeAction("movrl X24 0(X29) 0 8")
    pr__init_updown_master_26.writeAction("mov_reg2reg X0 X23")
    pr__init_updown_master_26.writeAction("evi X2 X30 255 4")
    pr__init_updown_master_26.writeAction("evlb X30 29")
    pr__init_updown_master_26.writeAction("GenMSRPagerankEFA_txaek_updown_master_loop: ev X30 X30 X23 X23 8")
    pr__init_updown_master_26.writeAction("sendr3_wret X30 27                 X16 X18 X21 X28")
    pr__init_updown_master_26.writeAction("addi X23 X23 1")
    pr__init_updown_master_26.writeAction("add X18 X16 X16 ")
    pr__init_updown_master_26.writeAction("addi X21 X21 1")
    pr__init_updown_master_26.writeAction("addi X26 X26 1")
    pr__init_updown_master_26.writeAction("blt X21 X25 GenMSRPagerankEFA_txaek_updown_master_loop")
    pr__init_updown_master_26.writeAction("mov_imm2reg X19 0")
    pr__init_updown_master_26.writeAction("addi X21 X22 0")
    pr__init_updown_master_26.writeAction("yield")

    ## pr__updown_master with ID 27
    pr__updown_master_27 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 27)
    pr__updown_master_27.writeAction("add X8 X19 X19")
    pr__updown_master_27.writeAction("bge X16 X24 GenMSRPagerankEFA_txaek_updown_master_fin_fetch")
    pr__updown_master_27.writeAction("addi X22 X22 1")
    pr__updown_master_27.writeAction("add X18 X16 X16 ")
    pr__updown_master_27.writeAction("yield")
    pr__updown_master_27.writeAction("GenMSRPagerankEFA_txaek_updown_master_fin_fetch: subi X21 X21 1")
    pr__updown_master_27.writeAction("blei X21 0 GenMSRPagerankEFA_txaek_updown_master_fin_partition")
    pr__updown_master_27.writeAction("yield")
    pr__updown_master_27.writeAction("GenMSRPagerankEFA_txaek_updown_master_fin_partition: sendr_wret X31             26 X19 X19 X28")
    pr__updown_master_27.writeAction("mov_imm2reg X19 0")
    pr__updown_master_27.writeAction("yield")

    ## pr__terminate_updown_master with ID 28
    pr__terminate_updown_master_28 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 28)
    pr__terminate_updown_master_28.writeAction("yield_terminate")

    ## pr__lane_master_init with ID 29
    pr__lane_master_init_29 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 29)
    pr__lane_master_init_29.writeAction("addi X1 X31 0")
    pr__lane_master_init_29.writeAction("send_dmlm_ld_wret X8 31 2 X28")
    pr__lane_master_init_29.writeAction("movir X16 0")
    pr__lane_master_init_29.writeAction("movir X17 24")
    pr__lane_master_init_29.writeAction("mov_imm2reg X19 0")
    pr__lane_master_init_29.writeAction("addi X7 X22 64")
    pr__lane_master_init_29.writeAction("move X19 0(X22) 0 8")
    pr__lane_master_init_29.writeAction("addi X2 X28 0")
    pr__lane_master_init_29.writeAction("evlb X28 30")
    pr__lane_master_init_29.writeAction("addi X7 X29 80")
    pr__lane_master_init_29.writeAction("move X28 0(X29) 0 8")
    pr__lane_master_init_29.writeAction("addi X2 X20 0")
    pr__lane_master_init_29.writeAction("evlb X20 32")
    pr__lane_master_init_29.writeAction("evi X2 X21 255 4")
    pr__lane_master_init_29.writeAction("evlb X21 65")
    pr__lane_master_init_29.writeAction("movir X25 0")
    pr__lane_master_init_29.writeAction("movir X28 200")
    pr__lane_master_init_29.writeAction("add X7 X28 X28")
    pr__lane_master_init_29.writeAction("movrl X1 0(X28) 0 8")
    pr__lane_master_init_29.writeAction("yield")

    ## pr__lane_master_loop with ID 30
    pr__lane_master_loop_30 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 30)
    pr__lane_master_loop_30.writeAction("subi X16 X16 1")
    pr__lane_master_loop_30.writeAction("beqi X23 1 GenMSRPagerankEFA_txaek_lane_master_loop_continue")
    pr__lane_master_loop_30.writeAction("bge X23 X24 GenMSRPagerankEFA_txaek_lane_master_reach_end")
    pr__lane_master_loop_30.writeAction("addi X23 X28 32")
    pr__lane_master_loop_30.writeAction("sendr_wcont X20 X20 X28 X24")
    pr__lane_master_loop_30.writeAction("send_dmlm_ld X23 X21 4")
    pr__lane_master_loop_30.writeAction("addi X16 X16 1")
    pr__lane_master_loop_30.writeAction("movir X23 1")
    pr__lane_master_loop_30.writeAction("yield")
    pr__lane_master_loop_30.writeAction("GenMSRPagerankEFA_txaek_lane_master_reach_end: bgti X16 0 GenMSRPagerankEFA_txaek_lane_master_loop_continue")
    pr__lane_master_loop_30.writeAction("movlr 0(X22) X19 0 8")
    pr__lane_master_loop_30.writeAction("sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_loop_30.writeAction("mov_imm2reg X19 0")
    pr__lane_master_loop_30.writeAction("movrl X19 0(X22) 0 8")
    pr__lane_master_loop_30.writeAction("addi X2 X30 0")
    pr__lane_master_loop_30.writeAction("evlb X30 34")
    pr__lane_master_loop_30.writeAction("sendr_wcont X30 X2 X28 X28")
    pr__lane_master_loop_30.writeAction("GenMSRPagerankEFA_txaek_lane_master_loop_continue: yield")

    ## pr__lane_master_read_partition with ID 31
    pr__lane_master_read_partition_31 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 31)
    pr__lane_master_read_partition_31.writeAction("bge X8 X9 GenMSRPagerankEFA_txaek_lane_master_empty_partition")
    pr__lane_master_read_partition_31.writeAction("addi X8 X28 32")
    pr__lane_master_read_partition_31.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__lane_master_read_partition_31.writeAction("send_dmlm_ld X8 X21 4")
    pr__lane_master_read_partition_31.writeAction("addi X16 X16 1")
    pr__lane_master_read_partition_31.writeAction("movir X23 1")
    pr__lane_master_read_partition_31.writeAction("yield")
    pr__lane_master_read_partition_31.writeAction("GenMSRPagerankEFA_txaek_lane_master_empty_partition: addi X2 X30 0")
    pr__lane_master_read_partition_31.writeAction("evlb X30 34")
    pr__lane_master_read_partition_31.writeAction("sendr_wcont X30 X2 X28 X28")
    pr__lane_master_read_partition_31.writeAction("GenMSRPagerankEFA_txaek_empty_part_ret_to_ud_mstr: sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_read_partition_31.writeAction("yield")

    ## pr__lane_master_get_next_return with ID 32
    pr__lane_master_get_next_return_32 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 32)
    pr__lane_master_get_next_return_32.writeAction("bge X16 X17 GenMSRPagerankEFA_txaek_lane_master_break_iterate_loop")
    pr__lane_master_get_next_return_32.writeAction("bge X8 X9 GenMSRPagerankEFA_txaek_lane_master_break_iterate_loop")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X28 32")
    pr__lane_master_get_next_return_32.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__lane_master_get_next_return_32.writeAction("send_dmlm_ld X8 X21 4")
    pr__lane_master_get_next_return_32.writeAction("addi X16 X16 1")
    pr__lane_master_get_next_return_32.writeAction("yield")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_txaek_lane_master_break_iterate_loop: movir X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X9 X24 0")
    pr__lane_master_get_next_return_32.writeAction("yield")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_txaek_lane_master_iterator_pass_end: subi X16 X16 1")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X9 X24 0")
    pr__lane_master_get_next_return_32.writeAction("bgti X16 0 GenMSRPagerankEFA_txaek_lane_master_loop_continue")
    pr__lane_master_get_next_return_32.writeAction("movlr 0(X22) X19 0 8")
    pr__lane_master_get_next_return_32.writeAction("sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_get_next_return_32.writeAction("addi X2 X30 0")
    pr__lane_master_get_next_return_32.writeAction("evlb X30 34")
    pr__lane_master_get_next_return_32.writeAction("sendr_wcont X30 X2 X28 X28")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_txaek_lane_master_loop_continue: yield")

    ## pr__lane_master_terminate with ID 33
    pr__lane_master_terminate_33 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 33)
    pr__lane_master_terminate_33.writeAction("yield_terminate")

    ## pr__lane_master_launch_worker with ID 34
    pr__lane_master_launch_worker_34 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 34)
    pr__lane_master_launch_worker_34.writeAction("GenMSRPagerankEFA_txaek_prepare_launch_workers: evii X30 49 255 5")
    pr__lane_master_launch_worker_34.writeAction("movir X28 -5")
    pr__lane_master_launch_worker_34.writeAction("GenMSRPagerankEFA_txaek_launch_workers: bgei X25 1 GenMSRPagerankEFA_txaek_lane_master_loop_continue")
    pr__lane_master_launch_worker_34.writeAction("sendr_wret X30 30 X28 X28 X29")
    pr__lane_master_launch_worker_34.writeAction("addi X25 X25 1")
    pr__lane_master_launch_worker_34.writeAction("jmp GenMSRPagerankEFA_txaek_launch_workers")
    pr__lane_master_launch_worker_34.writeAction("GenMSRPagerankEFA_txaek_lane_master_loop_continue: yieldt")

    ## pr__init_global_snyc with ID 35
    pr__init_global_snyc_35 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 35)
    pr__init_global_snyc_35.writeAction("sri X8 X16 11")
    pr__init_global_snyc_35.writeAction("movir X28 512")
    pr__init_global_snyc_35.writeAction("bgt X16 X28 GenMSRPagerankEFA_txaek_max_child_max_node")
    pr__init_global_snyc_35.writeAction("andi X8 X28 2047")
    pr__init_global_snyc_35.writeAction("beqi X28 0 GenMSRPagerankEFA_txaek_max_node")
    pr__init_global_snyc_35.writeAction("addi X16 X16 1")
    pr__init_global_snyc_35.writeAction("jmp GenMSRPagerankEFA_txaek_max_node")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_max_child_max_node: mov_imm2reg X16 512")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_max_node: addi X16 X16 0")
    pr__init_global_snyc_35.writeAction("sri X8 X17 6")
    pr__init_global_snyc_35.writeAction("movir X28 32")
    pr__init_global_snyc_35.writeAction("bgt X17 X28 GenMSRPagerankEFA_txaek_max_child_max_ud_per_nd")
    pr__init_global_snyc_35.writeAction("andi X8 X28 63")
    pr__init_global_snyc_35.writeAction("beqi X28 0 GenMSRPagerankEFA_txaek_max_ud_per_nd")
    pr__init_global_snyc_35.writeAction("addi X17 X17 1")
    pr__init_global_snyc_35.writeAction("jmp GenMSRPagerankEFA_txaek_max_ud_per_nd")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_max_ud_per_nd: addi X17 X17 0")
    pr__init_global_snyc_35.writeAction("movir X18 64")
    pr__init_global_snyc_35.writeAction("bgt X8 X18 GenMSRPagerankEFA_txaek_max_ln_per_ud")
    pr__init_global_snyc_35.writeAction("addi X8 X18 0")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_max_ln_per_ud: addi X18 X18 0")
    pr__init_global_snyc_35.writeAction("mov_reg2reg X1 X19")
    pr__init_global_snyc_35.writeAction("mov_reg2reg X9 X21")
    pr__init_global_snyc_35.writeAction("evi X2 X30 255 4")
    pr__init_global_snyc_35.writeAction("evlb X30 36")
    pr__init_global_snyc_35.writeAction("mov_imm2reg X29 0")
    pr__init_global_snyc_35.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: lshift X29 X28 11")
    pr__init_global_snyc_35.writeAction("add X0 X28 X28")
    pr__init_global_snyc_35.writeAction("ev X30 X30 X28 X28 8")
    pr__init_global_snyc_35.writeAction("sendr_wret X30 38 X17 X18  X28")
    pr__init_global_snyc_35.writeAction("addi X29 X29 1")
    pr__init_global_snyc_35.writeAction("blt X29 X16 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__init_global_snyc_35.writeAction("mov_imm2reg X20 0")
    pr__init_global_snyc_35.writeAction("mov_imm2reg X22 0")
    pr__init_global_snyc_35.writeAction("yield")

    ## pr__init_node_sync with ID 36
    pr__init_node_sync_36 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 36)
    pr__init_node_sync_36.writeAction("mov_reg2reg X8 X17")
    pr__init_node_sync_36.writeAction("evi X2 X30 255 4")
    pr__init_node_sync_36.writeAction("evlb X30 37")
    pr__init_node_sync_36.writeAction("mov_imm2reg X29 0")
    pr__init_node_sync_36.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: lshift X29 X28 6")
    pr__init_node_sync_36.writeAction("add X0 X28 X28")
    pr__init_node_sync_36.writeAction("ev X30 X30 X28 X28 8")
    pr__init_node_sync_36.writeAction("sendr_wret X30 39 X9 EQT  X28")
    pr__init_node_sync_36.writeAction("addi X29 X29 1")
    pr__init_node_sync_36.writeAction("blt X29 X17 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__init_node_sync_36.writeAction("mov_imm2reg X20 0")
    pr__init_node_sync_36.writeAction("mov_imm2reg X22 0")
    pr__init_node_sync_36.writeAction("mov_reg2reg X1 X19")
    pr__init_node_sync_36.writeAction("yield")

    ## pr__ud_accumulate with ID 37
    pr__ud_accumulate_37 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 37)
    pr__ud_accumulate_37.writeAction("mov_imm2reg X20 0")
    pr__ud_accumulate_37.writeAction("mov_imm2reg X22 0")
    pr__ud_accumulate_37.writeAction("GenMSRPagerankEFA_txaek_accumulate_loop: lshift X20 X17 16")
    pr__ud_accumulate_37.writeAction("add X7 X17 X17")
    pr__ud_accumulate_37.writeAction("addi X17 X17 72")
    pr__ud_accumulate_37.writeAction("move 0(X17) X28 0 8")
    pr__ud_accumulate_37.writeAction("add X28 X22 X22")
    pr__ud_accumulate_37.writeAction("addi X20 X20 1")
    pr__ud_accumulate_37.writeAction("blt X20 X8 GenMSRPagerankEFA_txaek_accumulate_loop")
    pr__ud_accumulate_37.writeAction("sendr_reply X22 X22 X28")
    pr__ud_accumulate_37.writeAction("yield_terminate")

    ## pr__global_sync_return with ID 38
    pr__global_sync_return_38 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 38)
    pr__global_sync_return_38.writeAction("addi X20 X20 1")
    pr__global_sync_return_38.writeAction("add X8 X22 X22")
    pr__global_sync_return_38.writeAction("blt X20 X16 GenMSRPagerankEFA_txaek_continue")
    pr__global_sync_return_38.writeAction("bge X22 X21 GenMSRPagerankEFA_txaek_sync_finish")
    pr__global_sync_return_38.writeAction("mov_imm2reg X29 0")
    pr__global_sync_return_38.writeAction("GenMSRPagerankEFA_txaek_broadcast_loop: lshift X29 X28 11")
    pr__global_sync_return_38.writeAction("add X0 X28 X28")
    pr__global_sync_return_38.writeAction("ev X30 X30 X28 X28 8")
    pr__global_sync_return_38.writeAction("sendr_wret X30 38 X17 X18  X28")
    pr__global_sync_return_38.writeAction("addi X29 X29 1")
    pr__global_sync_return_38.writeAction("blt X29 X16 GenMSRPagerankEFA_txaek_broadcast_loop")
    pr__global_sync_return_38.writeAction("mov_imm2reg X20 0")
    pr__global_sync_return_38.writeAction("mov_imm2reg X22 0")
    pr__global_sync_return_38.writeAction("GenMSRPagerankEFA_txaek_continue: yield")
    pr__global_sync_return_38.writeAction("GenMSRPagerankEFA_txaek_sync_finish: movir X30 -1")
    pr__global_sync_return_38.writeAction("sri X30 X30 1")
    pr__global_sync_return_38.writeAction("sendr_wcont X19 X30 X22 X22")
    pr__global_sync_return_38.writeAction("yield_terminate")

    ## pr__node_sync_return with ID 39
    pr__node_sync_return_39 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 39)
    pr__node_sync_return_39.writeAction("addi X20 X20 1")
    pr__node_sync_return_39.writeAction("add X8 X22 X22")
    pr__node_sync_return_39.writeAction("blt X20 X17 GenMSRPagerankEFA_txaek_continue")
    pr__node_sync_return_39.writeAction("sendr_wcont X19 EQT X22 X22")
    pr__node_sync_return_39.writeAction("yield_terminate")
    pr__node_sync_return_39.writeAction("GenMSRPagerankEFA_txaek_continue: yield")

    ## pr__kv_map_emit with ID 40
    pr__kv_map_emit_40 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 40)
    pr__kv_map_emit_40.writeAction("addi X7 X25 64")
    pr__kv_map_emit_40.writeAction("movlr 40(X25) X23 0 8")
    pr__kv_map_emit_40.writeAction("movlr 56(X25) X26 0 8")
    pr__kv_map_emit_40.writeAction("movir X24 0")
    pr__kv_map_emit_40.writeAction("hash X8 X24")
    pr__kv_map_emit_40.writeAction("and X24 X23 X24")
    pr__kv_map_emit_40.writeAction("add X24 X26 X24")
    pr__kv_map_emit_40.writeAction("evi X2 X30 255 4")
    pr__kv_map_emit_40.writeAction("evlb X30 43")
    pr__kv_map_emit_40.writeAction("evi X2 X27 255 4")
    pr__kv_map_emit_40.writeAction("evlb X27 46")
    pr__kv_map_emit_40.writeAction("ev X30  X30  X24 X24 8")
    pr__kv_map_emit_40.writeAction("sendops_wcont X30 X27 X8 2")
    pr__kv_map_emit_40.writeAction("move 0(X25) X29  0 8")
    pr__kv_map_emit_40.writeAction("addi X29 X29 1")
    pr__kv_map_emit_40.writeAction("move X29 0(X25) 0 8")
    pr__kv_map_emit_40.writeAction("yield_terminate")

    ## pr__kv_reduce_emit with ID 41
    pr__kv_reduce_emit_41 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 41)
    pr__kv_reduce_emit_41.writeAction("movir X16 128")
    pr__kv_reduce_emit_41.writeAction("add X16 X7 X16")
    pr__kv_reduce_emit_41.writeAction("movir X29 288")
    pr__kv_reduce_emit_41.writeAction("add X7 X29 X29")
    pr__kv_reduce_emit_41.writeAction("movlr 0(X29) X28 0 8")
    pr__kv_reduce_emit_41.writeAction("lshift X8 X29 3")
    pr__kv_reduce_emit_41.writeAction("add X29 X28 X28")
    pr__kv_reduce_emit_41.writeAction("subi X16 X16 8")
    pr__kv_reduce_emit_41.writeAction("send_dmlm X28 X1 X16 1")
    pr__kv_reduce_emit_41.writeAction("yieldt")

    ## pr__kv_map_return with ID 42
    pr__kv_map_return_42 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 42)
    pr__kv_map_return_42.writeAction("addi X7 X16 80")
    pr__kv_map_return_42.writeAction("move 0(X16) X29 0 8")
    pr__kv_map_return_42.writeAction("sendops_wcont X29 X2 X8 2")
    pr__kv_map_return_42.writeAction("yieldt")

    ## pr__init_reduce_thread with ID 43
    pr__init_reduce_thread_43 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 43)
    pr__init_reduce_thread_43.writeAction("movir X21 2000")
    pr__init_reduce_thread_43.writeAction("mod X8 X21 X21")
    pr__init_reduce_thread_43.writeAction("sli X21 X16 4")
    pr__init_reduce_thread_43.writeAction("add X7 X16 X16")
    pr__init_reduce_thread_43.writeAction("addi X16 X16 352")
    pr__init_reduce_thread_43.writeAction("movlr 0(X16) X17 0 8")
    pr__init_reduce_thread_43.writeAction("beq X17 X8 GenMSRPagerankEFA_txaek_cache_hit")
    pr__init_reduce_thread_43.writeAction("movir X21 1")
    pr__init_reduce_thread_43.writeAction("sli X21 X21 63")
    pr__init_reduce_thread_43.writeAction("or X21 X8 X25")
    pr__init_reduce_thread_43.writeAction("beq X25 X17 GenMSRPagerankEFA_txaek_cache_hit")
    pr__init_reduce_thread_43.writeAction("rshift X17 X24 63")
    pr__init_reduce_thread_43.writeAction("beqi X24 1 GenMSRPagerankEFA_txaek_cache_evict")
    pr__init_reduce_thread_43.writeAction("beqi X17 -1 GenMSRPagerankEFA_txaek_cache_evict")
    pr__init_reduce_thread_43.writeAction("evi X2 X24 255 4")
    pr__init_reduce_thread_43.writeAction("sendops_wcont X24 X1 X8 2")
    pr__init_reduce_thread_43.writeAction("yieldt")
    pr__init_reduce_thread_43.writeAction("GenMSRPagerankEFA_txaek_cache_hit: move 8(X16) X22 0 8")
    pr__init_reduce_thread_43.writeAction("fadd.64 X9 X22 X22")
    pr__init_reduce_thread_43.writeAction("movrl X22 8(X16) 0 8")
    pr__init_reduce_thread_43.writeAction("sendr_wcont X1 X2 X8 X17 ")
    pr__init_reduce_thread_43.writeAction("addi X7 X18 64")
    pr__init_reduce_thread_43.writeAction("move 8(X18) X24 0 8")
    pr__init_reduce_thread_43.writeAction("addi X24 X24 1")
    pr__init_reduce_thread_43.writeAction("move X24 8(X18) 0 8")
    pr__init_reduce_thread_43.writeAction("yieldt")
    pr__init_reduce_thread_43.writeAction("GenMSRPagerankEFA_txaek_cache_evict: addi X7 X18 64")
    pr__init_reduce_thread_43.writeAction("move 24(X18) X24 0 8")
    pr__init_reduce_thread_43.writeAction("move 32(X18) X25 0 8")
    pr__init_reduce_thread_43.writeAction("bgt X25 X24 GenMSRPagerankEFA_txaek_thread_available")
    pr__init_reduce_thread_43.writeAction("evi X2 X24 255 4")
    pr__init_reduce_thread_43.writeAction("sendops_wcont X24 X1 X8 2")
    pr__init_reduce_thread_43.writeAction("yieldt")
    pr__init_reduce_thread_43.writeAction("GenMSRPagerankEFA_txaek_thread_available: addi X24 X24 1")
    pr__init_reduce_thread_43.writeAction("move X24  24(X18) 0 8")
    pr__init_reduce_thread_43.writeAction("movrl X8 0(X16) 1 8")
    pr__init_reduce_thread_43.writeAction("movir X19 0")
    pr__init_reduce_thread_43.writeAction("beqi X17 -1 GenMSRPagerankEFA_txaek_skip_flush")
    pr__init_reduce_thread_43.writeAction("sub X17 X21 X17")
    pr__init_reduce_thread_43.writeAction("addi X16 X22 0")
    pr__init_reduce_thread_43.writeAction("addi X7 X18 128")
    pr__init_reduce_thread_43.writeAction("addi X2 X21 0")
    pr__init_reduce_thread_43.writeAction("evlb X21 45")
    pr__init_reduce_thread_43.writeAction("movir X25 288")
    pr__init_reduce_thread_43.writeAction("add X7 X25 X25")
    pr__init_reduce_thread_43.writeAction("movlr 0(X25) X24 0 8")
    pr__init_reduce_thread_43.writeAction("lshift X17 X25 3")
    pr__init_reduce_thread_43.writeAction("add X25 X24 X24")
    pr__init_reduce_thread_43.writeAction("send_dmlm X24 X21 X22 1")
    pr__init_reduce_thread_43.writeAction("addi X22 X22 8")
    pr__init_reduce_thread_43.writeAction("addi X19 X19 1")
    pr__init_reduce_thread_43.writeAction("GenMSRPagerankEFA_txaek_skip_flush: addi X2 X21 0")
    pr__init_reduce_thread_43.writeAction("evlb X21 44")
    pr__init_reduce_thread_43.writeAction("movir X25 288")
    pr__init_reduce_thread_43.writeAction("add X7 X25 X25")
    pr__init_reduce_thread_43.writeAction("movlr 0(X25) X24 0 8")
    pr__init_reduce_thread_43.writeAction("lshift X8 X25 3")
    pr__init_reduce_thread_43.writeAction("add X25 X24 X24")
    pr__init_reduce_thread_43.writeAction("send_dmlm_ld X24 X21 1")
    pr__init_reduce_thread_43.writeAction("move X9 0(X16) 0 8")
    pr__init_reduce_thread_43.writeAction("addi X8 X17 0")
    pr__init_reduce_thread_43.writeAction("addi X1 X20 0")
    pr__init_reduce_thread_43.writeAction("addi X19 X19 1")
    pr__init_reduce_thread_43.writeAction("yield")

    ## pr__combine_get_pair with ID 44
    pr__combine_get_pair_44 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 44)
    pr__combine_get_pair_44.writeAction("move 0(X16) X22 0 8")
    pr__combine_get_pair_44.writeAction("fadd.64 X22 X8 X22")
    pr__combine_get_pair_44.writeAction("move X22 0(X16) 0 8")
    pr__combine_get_pair_44.writeAction("GenMSRPagerankEFA_txaek_get_fail: subi X19 X19 1")
    pr__combine_get_pair_44.writeAction("bnei X19 0 GenMSRPagerankEFA_txaek_contiue")
    pr__combine_get_pair_44.writeAction("movir X21 1")
    pr__combine_get_pair_44.writeAction("sli X21 X21 63")
    pr__combine_get_pair_44.writeAction("or X21 X17 X17")
    pr__combine_get_pair_44.writeAction("movrl X17 -8(X16) 0 8")
    pr__combine_get_pair_44.writeAction("sendr_wcont X20 X2 X2 X17 ")
    pr__combine_get_pair_44.writeAction("addi X7 X18 64")
    pr__combine_get_pair_44.writeAction("move 24(X18) X24  0 8")
    pr__combine_get_pair_44.writeAction("subi X24 X24 1")
    pr__combine_get_pair_44.writeAction("move X24  24(X18) 0 8")
    pr__combine_get_pair_44.writeAction("move 8(X18) X24 0 8")
    pr__combine_get_pair_44.writeAction("addi X24 X24 1")
    pr__combine_get_pair_44.writeAction("move X24 8(X18) 0 8")
    pr__combine_get_pair_44.writeAction("yieldt")
    pr__combine_get_pair_44.writeAction("GenMSRPagerankEFA_txaek_contiue: yield")

    ## pr__combine_put_pair_ack with ID 45
    pr__combine_put_pair_ack_45 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 45)
    pr__combine_put_pair_ack_45.writeAction("subi X19 X19 1")
    pr__combine_put_pair_ack_45.writeAction("bnei X19 0 GenMSRPagerankEFA_txaek_contiue")
    pr__combine_put_pair_ack_45.writeAction("movir X21 1")
    pr__combine_put_pair_ack_45.writeAction("sli X21 X21 63")
    pr__combine_put_pair_ack_45.writeAction("or X21 X17 X17")
    pr__combine_put_pair_ack_45.writeAction("movrl X17 -8(X16) 0 8")
    pr__combine_put_pair_ack_45.writeAction("sendr_wcont X20 X2 X2 X17 ")
    pr__combine_put_pair_ack_45.writeAction("addi X7 X18 64")
    pr__combine_put_pair_ack_45.writeAction("move 24(X18) X24  0 8")
    pr__combine_put_pair_ack_45.writeAction("subi X24 X24 1")
    pr__combine_put_pair_ack_45.writeAction("move X24  24(X18) 0 8")
    pr__combine_put_pair_ack_45.writeAction("move 8(X18) X24 0 8")
    pr__combine_put_pair_ack_45.writeAction("addi X24 X24 1")
    pr__combine_put_pair_ack_45.writeAction("move X24 8(X18) 0 8")
    pr__combine_put_pair_ack_45.writeAction("yieldt")
    pr__combine_put_pair_ack_45.writeAction("GenMSRPagerankEFA_txaek_contiue: yield")

    ## pr__kv_reduce_return with ID 46
    pr__kv_reduce_return_46 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 46)
    pr__kv_reduce_return_46.writeAction("yieldt")

    ## pr__combine_flush_lane with ID 47
    pr__combine_flush_lane_47 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 47)
    pr__combine_flush_lane_47.writeAction("addi X1 X17 0")
    pr__combine_flush_lane_47.writeAction("addi X7 X20 352")
    pr__combine_flush_lane_47.writeAction("movir X16 2000")
    pr__combine_flush_lane_47.writeAction("sli X16 X16 4")
    pr__combine_flush_lane_47.writeAction("add X16 X20 X16")
    pr__combine_flush_lane_47.writeAction("movir X19 0")
    pr__combine_flush_lane_47.writeAction("movir X22 -1")
    pr__combine_flush_lane_47.writeAction("addi X2 X23 0")
    pr__combine_flush_lane_47.writeAction("evlb X23 48")
    pr__combine_flush_lane_47.writeAction("addi X7 X18 128")
    pr__combine_flush_lane_47.writeAction("GenMSRPagerankEFA_txaek_flush_loop: bge X20 X16 GenMSRPagerankEFA_txaek_break_flush_loop")
    pr__combine_flush_lane_47.writeAction("movlr 0(X20) X21 0 8")
    pr__combine_flush_lane_47.writeAction("beq X21 X22 GenMSRPagerankEFA_txaek_continue_flush_loop")
    pr__combine_flush_lane_47.writeAction("sli X21 X21 1")
    pr__combine_flush_lane_47.writeAction("sri X21 X21 1")
    pr__combine_flush_lane_47.writeAction("addi X20 X20 8")
    pr__combine_flush_lane_47.writeAction("movir X25 288")
    pr__combine_flush_lane_47.writeAction("add X7 X25 X25")
    pr__combine_flush_lane_47.writeAction("movlr 0(X25) X24 0 8")
    pr__combine_flush_lane_47.writeAction("lshift X21 X25 3")
    pr__combine_flush_lane_47.writeAction("add X25 X24 X24")
    pr__combine_flush_lane_47.writeAction("send_dmlm X24 X23 X20 1")
    pr__combine_flush_lane_47.writeAction("addi X20 X20 8")
    pr__combine_flush_lane_47.writeAction("addi X19 X19 1")
    pr__combine_flush_lane_47.writeAction("jmp GenMSRPagerankEFA_txaek_flush_loop")
    pr__combine_flush_lane_47.writeAction("GenMSRPagerankEFA_txaek_continue_flush_loop: addi X20 X20 16")
    pr__combine_flush_lane_47.writeAction("jmp GenMSRPagerankEFA_txaek_flush_loop")
    pr__combine_flush_lane_47.writeAction("GenMSRPagerankEFA_txaek_break_flush_loop: beqi X19 0 GenMSRPagerankEFA_txaek_empty_cache")
    pr__combine_flush_lane_47.writeAction("yield")
    pr__combine_flush_lane_47.writeAction("GenMSRPagerankEFA_txaek_empty_cache: movir X21 -1")
    pr__combine_flush_lane_47.writeAction("sri X21 X21 1")
    pr__combine_flush_lane_47.writeAction("sendr_wcont X17 X21 X2 X16 ")
    pr__combine_flush_lane_47.writeAction("yieldt")

    ## pr__combine_flush_ack with ID 48
    pr__combine_flush_ack_48 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 48)
    pr__combine_flush_ack_48.writeAction("subi X19 X19 1")
    pr__combine_flush_ack_48.writeAction("bnei X19 0 GenMSRPagerankEFA_txaek_continue_flush_loop")
    pr__combine_flush_ack_48.writeAction("movir X21 -1")
    pr__combine_flush_ack_48.writeAction("sri X21 X21 1")
    pr__combine_flush_ack_48.writeAction("sendr_wcont X17 X21 X2 X16 ")
    pr__combine_flush_ack_48.writeAction("yieldt")
    pr__combine_flush_ack_48.writeAction("GenMSRPagerankEFA_txaek_continue_flush_loop: yield")

    ## pr__worker_init with ID 49
    pr__worker_init_49 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 49)
    pr__worker_init_49.writeAction("addi X1 X31 0")
    pr__worker_init_49.writeAction("movir UDPR_5 -1")
    pr__worker_init_49.writeAction("movir UDPR_0 0")
    pr__worker_init_49.writeAction("addi X0 UDPR_6 0")
    pr__worker_init_49.writeAction("andi X0 X28 63")
    pr__worker_init_49.writeAction("sli X28 X28 16")
    pr__worker_init_49.writeAction("sub X7 X28 UDPR_3")
    pr__worker_init_49.writeAction("movir UDPR_7 216")
    pr__worker_init_49.writeAction("add UDPR_7 UDPR_3 UDPR_7")
    pr__worker_init_49.writeAction("movlr 0(UDPR_7) UDPR_2 0 8")
    pr__worker_init_49.writeAction("addi X2 X30 0")
    pr__worker_init_49.writeAction("evlb X30 50")
    pr__worker_init_49.writeAction("movir X28 -6")
    pr__worker_init_49.writeAction("sendr_wcont X30 X2 X28 X28")
    pr__worker_init_49.writeAction("yield")

    ## pr__worker_work with ID 50
    pr__worker_work_50 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 50)
    pr__worker_work_50.writeAction("GenMSRPagerankEFA_txaek_claim_work: bgei UDPR_5 0 GenMSRPagerankEFA_txaek_claim_remote_work")
    pr__worker_work_50.writeAction("addi X2 X30 0")
    pr__worker_work_50.writeAction("evlb X30 51")
    pr__worker_work_50.writeAction("sendr_wcont X30 X2 X8 X9")
    pr__worker_work_50.writeAction("yield")
    pr__worker_work_50.writeAction("GenMSRPagerankEFA_txaek_claim_remote_work: addi X2 X30 0")
    pr__worker_work_50.writeAction("evlb X30 52")
    pr__worker_work_50.writeAction("sendr_wcont X30 X2 X8 X9")
    pr__worker_work_50.writeAction("yield")

    ## pr__worker_claim_local with ID 51
    pr__worker_claim_local_51 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 51)
    pr__worker_claim_local_51.writeAction("movir UDPR_7 208")
    pr__worker_claim_local_51.writeAction("add UDPR_3 UDPR_7 UDPR_7")
    pr__worker_claim_local_51.writeAction("GenMSRPagerankEFA_txaek_claiming_local_maps: movlr 0(UDPR_7) X28 0 8")
    pr__worker_claim_local_51.writeAction("beq X28 UDPR_2 GenMSRPagerankEFA_txaek_local_maps_finished")
    pr__worker_claim_local_51.writeAction("addi X28 X29 16")
    pr__worker_claim_local_51.writeAction("cswp UDPR_7 UDPR_8 X28 X29")
    pr__worker_claim_local_51.writeAction("beq X28 UDPR_8 GenMSRPagerankEFA_txaek_claimed_local_maps")
    pr__worker_claim_local_51.writeAction("jmp GenMSRPagerankEFA_txaek_claiming_local_maps")
    pr__worker_claim_local_51.writeAction("GenMSRPagerankEFA_txaek_claimed_local_maps: evii X30 58 255 5")
    pr__worker_claim_local_51.writeAction("movir UDPR_7 200")
    pr__worker_claim_local_51.writeAction("add X7 UDPR_7 UDPR_7")
    pr__worker_claim_local_51.writeAction("movlr 0(UDPR_7) X29 0 8")
    pr__worker_claim_local_51.writeAction("sendr_wcont X30 X2 X28 X29")
    pr__worker_claim_local_51.writeAction("yield")
    pr__worker_claim_local_51.writeAction("GenMSRPagerankEFA_txaek_local_maps_finished: movir UDPR_5 0")
    pr__worker_claim_local_51.writeAction("GenMSRPagerankEFA_txaek_claim_remote_work: addi X2 X30 0")
    pr__worker_claim_local_51.writeAction("evlb X30 52")
    pr__worker_claim_local_51.writeAction("sendr_wcont X30 X2 X28 X28")
    pr__worker_claim_local_51.writeAction("GenMSRPagerankEFA_txaek_claiming_finished: yield")

    ## pr__worker_claim_remote with ID 52
    pr__worker_claim_remote_52 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 52)
    pr__worker_claim_remote_52.writeAction("GenMSRPagerankEFA_txaek_claim_work: movir UDPR_7 192")
    pr__worker_claim_remote_52.writeAction("add X7 UDPR_7 UDPR_7")
    pr__worker_claim_remote_52.writeAction("movlr 0(UDPR_7) X28 0 8")
    pr__worker_claim_remote_52.writeAction("beqi X28 1 GenMSRPagerankEFA_txaek_worker_finished")
    pr__worker_claim_remote_52.writeAction("beqi UDPR_0 1 GenMSRPagerankEFA_txaek_send_claim_msg")
    pr__worker_claim_remote_52.writeAction("movir UDPR_7 64")
    pr__worker_claim_remote_52.writeAction("add X7 UDPR_7 UDPR_7")
    pr__worker_claim_remote_52.writeAction("movlr 56(UDPR_7) UDPR_11 0 8")
    pr__worker_claim_remote_52.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    pr__worker_claim_remote_52.writeAction("addi UDPR_6 UDPR_6 64")
    pr__worker_claim_remote_52.writeAction("movlr 40(UDPR_7) X29 0 8")
    pr__worker_claim_remote_52.writeAction("addi X29 X29 1")
    pr__worker_claim_remote_52.writeAction("mod UDPR_6 X29 UDPR_6")
    pr__worker_claim_remote_52.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    pr__worker_claim_remote_52.writeAction("bne X0 UDPR_6 GenMSRPagerankEFA_txaek_send_claim_msg")
    pr__worker_claim_remote_52.writeAction("bgei UDPR_5 3 GenMSRPagerankEFA_txaek_worker_finished")
    pr__worker_claim_remote_52.writeAction("bgei UDPR_5 2 GenMSRPagerankEFA_txaek_early_finished")
    pr__worker_claim_remote_52.writeAction("sub UDPR_6 UDPR_11 UDPR_6")
    pr__worker_claim_remote_52.writeAction("addi UDPR_6 UDPR_6 64")
    pr__worker_claim_remote_52.writeAction("mod UDPR_6 X29 UDPR_6")
    pr__worker_claim_remote_52.writeAction("add UDPR_6 UDPR_11 UDPR_6")
    pr__worker_claim_remote_52.writeAction("GenMSRPagerankEFA_txaek_send_claim_msg: movir UDPR_0 0")
    pr__worker_claim_remote_52.writeAction("evii X30 55 255 5")
    pr__worker_claim_remote_52.writeAction("ev X30 X30 UDPR_6 UDPR_6 8")
    pr__worker_claim_remote_52.writeAction("movir X28 1")
    pr__worker_claim_remote_52.writeAction("sli X28 X28 59")
    pr__worker_claim_remote_52.writeAction("or X28 X30 X30")
    pr__worker_claim_remote_52.writeAction("movir X29 1")
    pr__worker_claim_remote_52.writeAction("movir UDPR_4 1")
    pr__worker_claim_remote_52.writeAction("sendr_wret X30 50 X29 X29 X28")
    pr__worker_claim_remote_52.writeAction("yield")
    pr__worker_claim_remote_52.writeAction("GenMSRPagerankEFA_txaek_early_finished: yieldt")
    pr__worker_claim_remote_52.writeAction("GenMSRPagerankEFA_txaek_worker_finished: yieldt")

    ## pr__worker_helper with ID 53
    pr__worker_helper_53 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 53)
    pr__worker_helper_53.writeAction("yield")

    ## pr__worker_claimed_map with ID 54
    pr__worker_claimed_map_54 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 54)
    pr__worker_claimed_map_54.writeAction("addi X1 UDPR_9 0")
    pr__worker_claimed_map_54.writeAction("movir UDPR_0 1")
    pr__worker_claimed_map_54.writeAction("GenMSRPagerankEFA_txaek_launch_mappers: evii X30 58 255 5")
    pr__worker_claimed_map_54.writeAction("sendr_wret X30 50 X9 X10 X28")
    pr__worker_claimed_map_54.writeAction("yield")

    ## pr__receiver_claim_work with ID 55
    pr__receiver_claim_work_55 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 55)
    pr__receiver_claim_work_55.writeAction("andi X0 X28 63")
    pr__receiver_claim_work_55.writeAction("sli X28 X28 16")
    pr__receiver_claim_work_55.writeAction("sub X7 X28 UDPR_4")
    pr__receiver_claim_work_55.writeAction("movir UDPR_7 208")
    pr__receiver_claim_work_55.writeAction("add UDPR_4 UDPR_7 UDPR_7")
    pr__receiver_claim_work_55.writeAction("movlr 0(UDPR_7) X28 0 8")
    pr__receiver_claim_work_55.writeAction("movlr 8(UDPR_7) UDPR_9 0 8")
    pr__receiver_claim_work_55.writeAction("GenMSRPagerankEFA_txaek_claim_maps: beq X28 UDPR_9 GenMSRPagerankEFA_txaek_local_work_resolved")
    pr__receiver_claim_work_55.writeAction("addi X28 X29 16")
    pr__receiver_claim_work_55.writeAction("cswp UDPR_7 UDPR_5 X28 X29")
    pr__receiver_claim_work_55.writeAction("beq X28 UDPR_5 GenMSRPagerankEFA_txaek_claimed_maps")
    pr__receiver_claim_work_55.writeAction("movlr 0(UDPR_7) X28 0 8")
    pr__receiver_claim_work_55.writeAction("jmp GenMSRPagerankEFA_txaek_claim_maps")
    pr__receiver_claim_work_55.writeAction("GenMSRPagerankEFA_txaek_claimed_maps: evii UDPR_15 57 255 5")
    pr__receiver_claim_work_55.writeAction("addi X1 X30 0")
    pr__receiver_claim_work_55.writeAction("evlb X30 54")
    pr__receiver_claim_work_55.writeAction("movir UDPR_7 200")
    pr__receiver_claim_work_55.writeAction("add X7 UDPR_7 UDPR_7")
    pr__receiver_claim_work_55.writeAction("movlr 0(UDPR_7) X29 0 8")
    pr__receiver_claim_work_55.writeAction("movir X28 -3")
    pr__receiver_claim_work_55.writeAction("sendr3_wcont X30 UDPR_15 X28 UDPR_5 X29")
    pr__receiver_claim_work_55.writeAction("yieldt")
    pr__receiver_claim_work_55.writeAction("GenMSRPagerankEFA_txaek_check_terminate_bit: movir UDPR_7 192")
    pr__receiver_claim_work_55.writeAction("add X7 UDPR_7 UDPR_7")
    pr__receiver_claim_work_55.writeAction("movlr 0(UDPR_7) X28 0 8")
    pr__receiver_claim_work_55.writeAction("blti X28 0 GenMSRPagerankEFA_txaek_local_work_resolved")
    pr__receiver_claim_work_55.writeAction("GenMSRPagerankEFA_txaek_local_work_resolved: movir X28 -2")
    pr__receiver_claim_work_55.writeAction("sendr_wcont X1 X2 X28 X29")
    pr__receiver_claim_work_55.writeAction("GenMSRPagerankEFA_txaek_receiver_claim_work_end: yieldt")

    ## pr__receiver_set_terminate_bit with ID 56
    pr__receiver_set_terminate_bit_56 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 56)
    pr__receiver_set_terminate_bit_56.writeAction("movir UDPR_7 192")
    pr__receiver_set_terminate_bit_56.writeAction("add X7 UDPR_7 UDPR_7")
    pr__receiver_set_terminate_bit_56.writeAction("movrl X8 0(UDPR_7) 0 8")
    pr__receiver_set_terminate_bit_56.writeAction("bnei X8 1 GenMSRPagerankEFA_txaek_terminate")
    pr__receiver_set_terminate_bit_56.writeAction("sendr_reply X28 X28 X28")
    pr__receiver_set_terminate_bit_56.writeAction("GenMSRPagerankEFA_txaek_terminate: yieldt")

    ## pr__receiver_set_terminate_bit_ret with ID 57
    pr__receiver_set_terminate_bit_ret_57 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 57)
    pr__receiver_set_terminate_bit_ret_57.writeAction("yieldt")

    ## pr__mapper_control_init with ID 58
    pr__mapper_control_init_58 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 58)
    pr__mapper_control_init_58.writeAction("addi X1 X31 0")
    pr__mapper_control_init_58.writeAction("addi X9 X18 0")
    pr__mapper_control_init_58.writeAction("send_dmlm_ld_wret X8 59 2 X28")
    pr__mapper_control_init_58.writeAction("movir X16 0")
    pr__mapper_control_init_58.writeAction("movir X17 24")
    pr__mapper_control_init_58.writeAction("movir X19 0")
    pr__mapper_control_init_58.writeAction("movir X22 64")
    pr__mapper_control_init_58.writeAction("add X7 X22 X22")
    pr__mapper_control_init_58.writeAction("addi X2 X28 0")
    pr__mapper_control_init_58.writeAction("evlb X28 61")
    pr__mapper_control_init_58.writeAction("movir X29 80")
    pr__mapper_control_init_58.writeAction("add X7 X29 X29")
    pr__mapper_control_init_58.writeAction("move X28 0(X29) 0 8")
    pr__mapper_control_init_58.writeAction("addi X2 X20 0")
    pr__mapper_control_init_58.writeAction("evlb X20 60")
    pr__mapper_control_init_58.writeAction("evi X2 X21 255 4")
    pr__mapper_control_init_58.writeAction("evlb X21 65")
    pr__mapper_control_init_58.writeAction("yield")

    ## pr__mapper_control_read_partition with ID 59
    pr__mapper_control_read_partition_59 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 59)
    pr__mapper_control_read_partition_59.writeAction("bge X8 X9 GenMSRPagerankEFA_txaek_lane_master_empty_partition")
    pr__mapper_control_read_partition_59.writeAction("addi X8 X28 32")
    pr__mapper_control_read_partition_59.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__mapper_control_read_partition_59.writeAction("send_dmlm_ld X8 X21 4")
    pr__mapper_control_read_partition_59.writeAction("addi X16 X16 1")
    pr__mapper_control_read_partition_59.writeAction("movir X23 1")
    pr__mapper_control_read_partition_59.writeAction("yield")
    pr__mapper_control_read_partition_59.writeAction("GenMSRPagerankEFA_txaek_lane_master_empty_partition: movir X29 -6")
    pr__mapper_control_read_partition_59.writeAction("sendr_wcont X18 X2 X19 X19")
    pr__mapper_control_read_partition_59.writeAction("sendr_wcont X31 X2 X29 X19")
    pr__mapper_control_read_partition_59.writeAction("yieldt")

    ## pr__mapper_control_get_next_return with ID 60
    pr__mapper_control_get_next_return_60 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 60)
    pr__mapper_control_get_next_return_60.writeAction("bge X16 X17 GenMSRPagerankEFA_txaek_mapper_control_break_iterate_loop")
    pr__mapper_control_get_next_return_60.writeAction("bge X8 X9 GenMSRPagerankEFA_txaek_mapper_control_break_iterate_loop")
    pr__mapper_control_get_next_return_60.writeAction("addi X8 X28 32")
    pr__mapper_control_get_next_return_60.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__mapper_control_get_next_return_60.writeAction("send_dmlm_ld X8 X21 4")
    pr__mapper_control_get_next_return_60.writeAction("addi X16 X16 1")
    pr__mapper_control_get_next_return_60.writeAction("yield")
    pr__mapper_control_get_next_return_60.writeAction("GenMSRPagerankEFA_txaek_mapper_control_break_iterate_loop: movir X23 0")
    pr__mapper_control_get_next_return_60.writeAction("addi X8 X23 0")
    pr__mapper_control_get_next_return_60.writeAction("addi X9 X24 0")
    pr__mapper_control_get_next_return_60.writeAction("yield")
    pr__mapper_control_get_next_return_60.writeAction("GenMSRPagerankEFA_txaek_mapper_control_iterator_pass_end: subi X16 X16 1")
    pr__mapper_control_get_next_return_60.writeAction("addi X8 X23 0")
    pr__mapper_control_get_next_return_60.writeAction("addi X9 X24 0")
    pr__mapper_control_get_next_return_60.writeAction("bgti X16 0 GenMSRPagerankEFA_txaek_lane_master_loop_continue")
    pr__mapper_control_get_next_return_60.writeAction("movlr 0(X22) X19 0 8")
    pr__mapper_control_get_next_return_60.writeAction("movir X29 -6")
    pr__mapper_control_get_next_return_60.writeAction("sendr_wcont X31 X2 X29 X19")
    pr__mapper_control_get_next_return_60.writeAction("sendr_wcont X18 X2 X29 X19")
    pr__mapper_control_get_next_return_60.writeAction("yieldt")
    pr__mapper_control_get_next_return_60.writeAction("GenMSRPagerankEFA_txaek_lane_master_loop_continue: yield")

    ## pr__mapper_control_loop with ID 61
    pr__mapper_control_loop_61 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 61)
    pr__mapper_control_loop_61.writeAction("subi X16 X16 1")
    pr__mapper_control_loop_61.writeAction("beqi X23 1 GenMSRPagerankEFA_txaek_mapper_control_loop_continue")
    pr__mapper_control_loop_61.writeAction("bge X23 X24 GenMSRPagerankEFA_txaek_mapper_control_reach_end")
    pr__mapper_control_loop_61.writeAction("addi X23 X28 32")
    pr__mapper_control_loop_61.writeAction("sendr_wcont X20 X20 X28 X24")
    pr__mapper_control_loop_61.writeAction("send_dmlm_ld X23 X21 4")
    pr__mapper_control_loop_61.writeAction("addi X16 X16 1")
    pr__mapper_control_loop_61.writeAction("movir X23 1")
    pr__mapper_control_loop_61.writeAction("yield")
    pr__mapper_control_loop_61.writeAction("GenMSRPagerankEFA_txaek_mapper_control_reach_end: bgti X16 0 GenMSRPagerankEFA_txaek_mapper_control_loop_continue")
    pr__mapper_control_loop_61.writeAction("movlr 0(X22) X19 0 8")
    pr__mapper_control_loop_61.writeAction("movir X29 -6")
    pr__mapper_control_loop_61.writeAction("sendr_wcont X18 X2 X19 X19")
    pr__mapper_control_loop_61.writeAction("sendr_wcont X31 X2 X29 X19")
    pr__mapper_control_loop_61.writeAction("mov_imm2reg X19 0")
    pr__mapper_control_loop_61.writeAction("movrl X19 0(X22) 0 8")
    pr__mapper_control_loop_61.writeAction("yieldt")
    pr__mapper_control_loop_61.writeAction("GenMSRPagerankEFA_txaek_mapper_control_loop_continue: yield")

    ## pr__lane_remote_mapper_finished with ID 62
    pr__lane_remote_mapper_finished_62 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 62)
    pr__lane_remote_mapper_finished_62.writeAction("yieldt")

    ## updown_init with ID 63
    updown_init_63 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 63)
    updown_init_63.writeAction("movir UDPR_2 128")
    updown_init_63.writeAction("add X7 UDPR_2 UDPR_2")
    updown_init_63.writeAction("movrl X8 0(UDPR_2) 0 8")
    updown_init_63.writeAction("movrl X9 8(UDPR_2) 0 8")
    updown_init_63.writeAction("movrl X10 16(UDPR_2) 0 8")
    updown_init_63.writeAction("addi X7 UDPR_1 224")
    updown_init_63.writeAction("movrl UDPR_1 24(UDPR_2) 0 8")
    updown_init_63.writeAction("movrl X11 0(UDPR_1) 1 8")
    updown_init_63.writeAction("movrl X12 0(UDPR_1) 1 8")
    updown_init_63.writeAction("movrl UDPR_1 32(UDPR_2) 0 8")
    updown_init_63.writeAction("movrl X13 0(UDPR_1) 1 8")
    updown_init_63.writeAction("movrl X14 0(UDPR_1) 1 8")
    updown_init_63.writeAction("movrl UDPR_1 40(UDPR_2) 0 8")
    updown_init_63.writeAction("movrl X15 0(UDPR_1) 1 8")
    updown_init_63.writeAction("evii UDPR_9 7 255 5")
    updown_init_63.writeAction("send_wret UDPR_9 64 UDPR_2 6 UDPR_0")
    updown_init_63.writeAction("movir UDPR_0 0")
    updown_init_63.writeAction("addi X7 UDPR_1 0")
    updown_init_63.writeAction("move UDPR_0 0(UDPR_1) 0 8")
    updown_init_63.writeAction("yield")

    ## updown_terminate with ID 64
    updown_terminate_64 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 64)
    updown_terminate_64.writeAction("perflog 1 0 '[DEBUG][NWID %d] Event <updown_terminate> Finish PageRank' X0")
    updown_terminate_64.writeAction("movir UDPR_0 1")
    updown_terminate_64.writeAction("move UDPR_0 0(UDPR_1) 0 8")
    updown_terminate_64.writeAction("yield_terminate")

    ## pr__kv_map with ID 65
    pr__kv_map_65 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 65)
    pr__kv_map_65.writeAction("beqi X9 0 GenMSRPagerankEFA_txaek_empty")
    pr__kv_map_65.writeAction("addi X10 UDPR_0 0")
    pr__kv_map_65.writeAction("lshift X9 UDPR_1 3")
    pr__kv_map_65.writeAction("add UDPR_0 UDPR_1 UDPR_1")
    pr__kv_map_65.writeAction("movir UDPR_7 0")
    pr__kv_map_65.writeAction("movir UDPR_9 32")
    pr__kv_map_65.writeAction("GenMSRPagerankEFA_txaek_array_load: bge UDPR_0 UDPR_1 GenMSRPagerankEFA_txaek_array_load_fin")
    pr__kv_map_65.writeAction("send_dmlm_ld_wret UDPR_0 66 8 UDPR_14")
    pr__kv_map_65.writeAction("addi UDPR_0 UDPR_0 64")
    pr__kv_map_65.writeAction("addi UDPR_7 UDPR_7 8")
    pr__kv_map_65.writeAction("bge UDPR_7 UDPR_9 GenMSRPagerankEFA_txaek_array_load_fin")
    pr__kv_map_65.writeAction("jmp GenMSRPagerankEFA_txaek_array_load")
    pr__kv_map_65.writeAction("GenMSRPagerankEFA_txaek_array_load_fin: fcnvt.i64.64 X9 UDPR_4")
    pr__kv_map_65.writeAction("fdiv.64 X11 UDPR_4 UDPR_3")
    pr__kv_map_65.writeAction("addi X9 UDPR_4 0")
    pr__kv_map_65.writeAction("addi X7 UDPR_10 0")
    pr__kv_map_65.writeAction("movlr 104(UDPR_10) UDPR_8 0 8")
    pr__kv_map_65.writeAction("evi X2 UDPR_11 255 4")
    pr__kv_map_65.writeAction("evlb UDPR_11 43")
    pr__kv_map_65.writeAction("evi X2 UDPR_12 255 4")
    pr__kv_map_65.writeAction("evlb UDPR_12 46")
    pr__kv_map_65.writeAction("movir UDPR_7 0")
    pr__kv_map_65.writeAction("yield")
    pr__kv_map_65.writeAction("GenMSRPagerankEFA_txaek_empty: addi X2 X30 0")
    pr__kv_map_65.writeAction("evlb X30 42")
    pr__kv_map_65.writeAction("sendr_wcont X30 X2 EQT EQT")
    pr__kv_map_65.writeAction("yield")

    ## pr__map_load_return with ID 66
    pr__map_load_return_66 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 66)
    pr__map_load_return_66.writeAction("bge UDPR_0 UDPR_1 GenMSRPagerankEFA_txaek_finish_fetch")
    pr__map_load_return_66.writeAction("send_dmlm_ld_wret UDPR_0 66 8 UDPR_14")
    pr__map_load_return_66.writeAction("addi UDPR_0 UDPR_0 64")
    pr__map_load_return_66.writeAction("GenMSRPagerankEFA_txaek_finish_fetch: addi X3 UDPR_9 0")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X8 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X9 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X10 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X11 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X12 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X13 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X14 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_txaek_broadcast_continue")
    pr__map_load_return_66.writeAction("evii UDPR_11 40 255 5")
    pr__map_load_return_66.writeAction("sendr_wcont UDPR_11 X2 X15 UDPR_3")
    pr__map_load_return_66.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_66.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_66.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_txaek_finish_broadcast")
    pr__map_load_return_66.writeAction("GenMSRPagerankEFA_txaek_broadcast_continue: yield")
    pr__map_load_return_66.writeAction("GenMSRPagerankEFA_txaek_finish_broadcast: movir UDPR_2 0")
    pr__map_load_return_66.writeAction("addi X2 X30 0")
    pr__map_load_return_66.writeAction("evlb X30 42")
    pr__map_load_return_66.writeAction("sendr_wcont X30 X2 UDPR_2 UDPR_6")
    pr__map_load_return_66.writeAction("yield")



def main():
    efa = EFA([])
    efa.code_level = 'machine'
    efaProgram_PagerankMsrEFA_rh_nlbstrm_on(efa)
    return efa