all: duplicate_coo duplicate_csr

duplicate_coo: duplicate_coo.cpp
	g++ -o duplicate_coo duplicate_coo.cpp

duplicate_csr: duplicate_csr.cpp
	g++ -o duplicate_csr duplicate_csr.cpp

clean:
	rm duplicate_coo duplicate_csr
